### PR TITLE
Instrumentation for interval loop invariants

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
This PR  adds:

1. Multiple instrumentation modes for the interval analysis
2. A new instrumentation mode which will add only restrictions for loop variables.

This is mostly so I can start running more experiments. I will avoid adding explicit flags for now

### CODE REVIEW

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
@rafaelsamenezes: could you please run this PR over the SV-COMP benchmarks?

**Comment by rafaelsamenezes** [comment]
Master

```
Statistics:          23805 Files
  correct:           15091
    correct true:     8534
    correct false:    6557
  incorrect:            45
    incorrect true:     17
    incorrect false:    28
  unknown:            8669
  Score:             22633 (max: 38482)
```

This PR:

```
Statistics:          23805 Files
  correct:           15105
    correct true:     8545
    correct false:    6560
  incorrect:            45
    incorrect true:     17
    incorrect false:    28
  unknown:            8655
  Score:             22658 (max: 38482)
```

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Comment by rafaelsamenezes** [comment]
I will merge this for now. @fbrausse let me know if you have any comments.

**Pull request merged**
