### PR TITLE
[C++ verification] update isnan OM

### PR DESCRIPTION
**Pull request by XLiZHI**
Follow suggestion in https://github.com/esbmc/esbmc/pull/2008#issuecomment-2318404541

### CODE REVIEW

**Review by fbrausse — COMMENTED** [review]
I believe we'll also need `isnanf` and `isnanl`. That's what the CIMPORT1 macro has been for.

**Comment by XLiZHI** [comment]
> I believe we'll also need `isnanf` and `isnanl`. That's what the CIMPORT1 macro has been for.

Hi @fbrausse, What I learned was `__builtin_isnan`, which handles all types. `isnanf` and `isnanl` exist for compatibility reasons; compilers other than _clang_ and _gcc_ do not support this built-in function.

**Review by mikhailramalho — APPROVED** [review]
Please add test cases that include "cmath" and others that include "math.h"

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @XLiZHI.

**Pull request merged**
