### PR TITLE
[clang-c] adjust also symbol's type and handle VLAs in adjust_type()

### LINKED ISSUE #1070: ESBMC crash - ERROR: Select operation applied to tuple
ESBMC 7.2 crash for this small C program with `ERROR: Select operation applied to tuple
Aborted (core dumped)`

```c
//FormAI DATASET v0.1 Category: Building a HTTP Client ; Style: high level of detail
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <unistd.h>
#define BUFSIZE 4096

int main(int argc, char* argv[]) {
    if (argc < 2) {
        printf("Usage: %s <url>\n", argv[0]);
        return 1;
    }

    const char delimiter[2] = "/";
    char* host, *path;
    char url[strlen(argv[1])];
    strcpy(url, argv[1]);

    strtok(url, delimiter); // http:
    strtok(NULL, delimiter); // empty
    strtok(NULL, delimiter); // host

    host = strtok(NULL, delimiter); // path
    path = "/";
    while (host != NULL) {
        path = strcat(path, "/");
        path = strcat(path, host);
        host = strtok(NULL, delimiter);
    }

    char request[BUFSIZE];
    sprintf(request, "GET %s HTTP/1.1\r\n"
                      "Host: %s\r\n"
                      "Connection: close\r\n\r\n"
            , path, argv[1]);

    struct sockaddr_in server;
    memset(&server, 0, sizeof(server));
    server.sin_family = AF_INET;
    server.sin_addr.s_addr = inet_addr(argv[1]);
    server.sin_port = htons(80);

    int sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock < 0) {
        perror("Socket error.");
        return 1;
    }

    if (connect(sock, (struct sockaddr*) &server, sizeof(server)) < 0) {
        perror("Connection error.");
        return 1;
    }

    send(sock, request, strlen(request), 0);

    char buffer[BUFSIZE];
    while (recv(sock, buffer, BUFSIZE, 0) > 0) {
        printf("%s", buffer);
        memset(buffer, 0, BUFSIZE);
    }

    close(sock);
    return 0;
}
```

ESBMC output:

```
esbmc --unwind 1 DATA3/FormAI_31168.c
ESBMC version 7.2.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.290s
GOTO program processing time: 0.004s
Starting Bounded Model Checking
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
Not unwinding 
no body for function inet_addr
no body for function socket
no body for function perror
no body for function connect
no body for function perror
Not unwinding 
no body for function send
no body for function recv
Not unwinding 
no body for function close
Symex completed in: 0.315s (442 assignments)
Slicing time: 0.005s (removed 242 assignments)
Generated 102 VCC(s), 75 remaining after simplification (200 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
ERROR: Select operation applied to tuple
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by fbrausse**
Fixes crash in #1070.

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
Well done, @fbrausse  ;-)

**Comment by fbrausse** [comment]
> Well done, @fbrausse ;-)

Many thanks, @lucasccordeiro! I've added the regression test from #1070, which works with Boolector, Bitwuzla and Yices, but it fails with assertion errors when using Z3, CVC4 or MathSAT. Is it possible to put solver-specific versions into the regression suite or should this be handled differently?

**Comment by lucasccordeiro** [comment]
@fbrausse: we should support all solvers in our regression. However, @rafaelsamenezes can confirm that.

**Comment by rafaelsamenezes** [comment]
> @fbrausse: we should support all solvers in our regression. However, @rafaelsamenezes can confirm that.

Hm, there is no rule of thumb here:

- In https://github.com/esbmc/esbmc/pull/1042 I am moving solver specific tests to their own folders. So, feel free to create a directory and just add the tests as KNOWNBUG/CORE.
- You can also just add the solver flag as usual with THOROUGH or KNOWNBUG. When I came with naming I decided to put THOROUGH for long tests (+30s) or that needed a specific solver/os.

**Comment by rafaelsamenezes** [comment]
>  Z3, CVC4 or MathSAT

I would also try using the flatteners, since it is working for Boolector.

**Comment by fbrausse** [comment]
Thanks @rafaelsamenezes, I'll add separate directories for those solvers that don't have one, yet. Though I'm wondering whether in the long run (and maybe even before duplicating test cases that might need deduplication later) it would make more sense to extend the testing script to pass the solver to those tests that are explicitly meant to work with any solver. In other words, whether the majority of test cases that are "generic" should be run with all supported backends.

I'll also give the flatterners a try, though there still are issues combining them with Z3 and CVC4 (at least), see #595.

**Comment by fbrausse** [comment]
> deduplication

@rafaelsamenezes does Git on Windows handle symlinks in the repository?

**Comment by rafaelsamenezes** [comment]
> > deduplication
> 
> @rafaelsamenezes does Git on Windows handle symlinks in the repository?

I never tried it

**Comment by fbrausse** [comment]
I've opened #1085 containing some information as to how the issue occurs, but I am unable to fix it at the moment.

**Comment by fbrausse** [comment]
> > @rafaelsamenezes does Git on Windows handle symlinks in the repository?
> 
> I never tried it

Seems to work fine.

**Comment by fbrausse** [comment]
> > Z3, CVC4 or MathSAT
> 
> I would also try using the flatteners, since it is working for Boolector.

No luck, neither flattener makes any of those work right now.

**Comment by lucasccordeiro** [comment]
@fbrausse : can I ask you whether you would have further changes to this PR?

**Comment by fbrausse** [comment]
@lucasccordeiro This is all for this PR.

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Many thanks, @fbrausse.

**Pull request merged**
