### PR TITLE
Test case Generation

### PR DESCRIPTION
**Pull request by rafaelsamenezes**

### CODE REVIEW

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
@rafaelsamenezes: could you please create some regression tests?

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes : what is the status of this PR?

**Comment by rafaelsamenezes** [comment]
> @rafaelsamenezes : what is the status of this PR?

- It generates a testcase and test description
- It fixes the slicer issue of removing nondet symbols.

**Comment by lucasccordeiro** [comment]
Can you rebase this branch with the master?

**Comment by rafaelsamenezes** [comment]
> Can you rebase this branch with the master?

Done

**Review by lucasccordeiro — APPROVED** [review]

**Review by ChenfengWei0 — APPROVED** [review]
LGTM

**Pull request merged**
