### PR TITLE
[WiP] CSmith Fuzzing Regression Tests

### PR DESCRIPTION
**Pull request by ericksonalves**
This PR adds regression test cases generated by csmith.

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
@mikhailramalho, @rafaelsamenezes, and @feliperodri: This PR intends to increase the code coverage of ESBMC by adding test cases produced by CSmith. 

According to some preliminary evaluation, this PR increases the code coverage from 43.78% to 44.47%. This PR is the first step towards producing test cases that can achieve high code coverage in ESBMC.

May I ask you to review it?

**Review by lucasccordeiro — COMMENTED** [review]
@ericksonalves: We have just seven test descriptions in total. All of them are marked as `KNOWNBUG'. Is that correct?

**Comment by rafaelsamenezes** [comment]
@ericksonalves could you tell which modules are getting more cover? 

Also, not a requirement but it would be nice to know what is the bug being triggered and if possible reference the issue or create one.

**Comment by lsergiobp** [comment]
The modules that got covered by the tests:
- Clang-c-frontend 
- Esbmc
- Goto-programs 
- Goto-symex 
- Util

All of those had tests coverage increased.

**Review by lucasccordeiro — APPROVED** [review]

**Review by rafaelsamenezes — APPROVED** [review]

**Pull request merged**
