### PR TITLE
[c++17] replaced gnu::unused for maybe_unused

### LINKED ISSUE #792: C++17
Should we update the repository into it? If so, we can finally replace the `gnu unused` with `maybe_unused`

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
Should close #792

### CODE REVIEW

**Review by fbrausse — APPROVED** [review]
Nice!

**Review by lucasccordeiro — APPROVED** [review]
Thanks for this PR, @rafaelsamenezes!

**Comment by fbrausse** [comment]
With (at least) C++17 mandated, we could now also remove https://github.com/esbmc/esbmc/blob/f3d0b40e21ba08f32cfd2fea689b0585a16cd7aa/src/pointer-analysis/dereference.cpp#L35-L41

**Review by mikhailramalho — APPROVED** [review]
LGTM

**Pull request merged**
