### PR TITLE
[dereference] fix #1068 and segfault in #723

### LINKED ISSUE #1068: ESBMC crash - Unexpectedly array type'd argument to construct_struct_ref
In this  small C example ESBMC crashes with `ERROR: Unexpectedly array type'd argument to construct_struct_ref
Aborted (core dumped)`

```c
//FormAI DATASET v0.1 Category: Network Topology Mapper ; Style: ephemeral


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

// Constants
#define MAX_NODES 100
#define MAX_LINKS 1000
#define MAX_HOPS  6

// Structs
typedef struct {
    int node_ID;
    int cost;
} Link;

typedef struct {
    int node_ID;
    Link links[MAX_NODES];
} Node;

// Global Variables
Node network[MAX_NODES];
int num_nodes = 0;
int num_links = 0;

// Forward Declarations
bool is_existing_node(int node_ID);
Node* get_node(int node_ID);
void add_node(int node_ID);
Link* get_link(int node_ID, int connected_node_ID);
void add_link(int node_ID, int connected_node_ID, int cost);
void print_topology_map();

// Main Function
int main() {

    // Create some nodes
    add_node(1);
    add_node(2);
    add_node(3);
    add_node(4);
    add_node(5);

    // Connect the nodes with links and associated costs
    add_link(1, 2, 1);
    add_link(1, 3, 2);
    add_link(2, 3, 1);
    add_link(2, 4, 1);
    add_link(3, 4, 2);
    add_link(4, 5, 1);

    // Print the topology map of the network
    print_topology_map();

    return 0;
}

// Helper Functions

// Checks if a node already exists in the network
bool is_existing_node(int node_ID) {
    for(int i = 0; i < num_nodes; i++) {
        if(network[i].node_ID == node_ID) {
            return true;
        }
    }
    return false;
}

// Returns a pointer to a given node
Node* get_node(int node_ID) {
    for(int i = 0; i < num_nodes; i++) {
        if(network[i].node_ID == node_ID) {
            return &network[i];
        }
    }
    return NULL;
}

// Adds a new node to the network
void add_node(int node_ID) {
    if(!is_existing_node(node_ID)) {
        Node new_node;
        new_node.node_ID = node_ID;
        network[num_nodes] = new_node;
        num_nodes++;
    }
}

// Returns a pointer to a link between two nodes
Link* get_link(int node_ID, int connected_node_ID) {
    Node* node = get_node(node_ID);
    if(node != NULL) {
        for(int i = 0; i < MAX_NODES; i++) {
            if(node->links[i].node_ID == connected_node_ID) {
                return &node->links[i];
            }
        }
    }
    return NULL;
}

// Adds a new link between two nodes to the network
void add_link(int node_ID, int connected_node_ID, int cost) {
    if(is_existing_node(node_ID) && is_existing_node(connected_node_ID)) {
        Link new_link;
        new_link.node_ID = connected_node_ID;
        new_link.cost = cost;
        Link* existing_link = get_link(node_ID, connected_node_ID);
        if(existing_link != NULL) {
            *existing_link = new_link;
        }
        else {
            Node* node = get_node(node_ID);
            if(node != NULL) {
                node->links[node->node_ID] = new_link;
            }
        }
        num_links++;
    }
}

// Prints the topology map of the network
void print_topology_map() {
    printf("------- Network Topology Map -------\n");
    printf("Node ID | Connected Nodes (Costs)\n");
    printf("------------------------------------\n");
    for(int i = 0; i < num_nodes; i++) {
        Node node = network[i];
        printf("%d      | ", node.node_ID);
        for(int j = 0; j < MAX_NODES; j++) {
            if(node.links[j].node_ID != 0) {
                printf("%d (%d)  ", node.links[j].node_ID, node.links[j].cost);
            }
        }
        printf("\n");
    }
    printf("------------------------------------\n");
}
```
ESBMC crash output:

```
esbmc --overflow --unwind 1 DATA3/FormAI_33453.c
ESBMC version 7.2.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.323s
GOTO program processing time: 0.006s
Starting Bounded Model Checking
no body for function socket
no body for function perror
Not unwinding 
Not unwinding 
ERROR: Unexpectedly array type'd argument to construct_struct_ref
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by fbrausse**
The method construct_struct_ref_from_const_offset() assumed that it itself was also responsible for handling members. It is not, as the member could well be an array.

Fix this by delegating back to the entry point build_reference_rec().

Fixes #1068 and resolves the crash in #723. The latter is still valid as the result is wrong. I'll update the issue once this PR passed.

### CODE REVIEW

**Comment by fbrausse** [comment]
Z3 fails on this test case in a debug build with
```
Encoding to solver time: 0.013s
Solving with solver Z3 v4.11.2
Runtime decision procedure: 1.331s
Building error trace
esbmc: /home/kane/scorch/esbmc/src/solvers/z3/z3_conv.cpp:1084: virtual expr2tc z3_convt::tuple_get(const type2tc&, smt_astt): Assertion `is_pointer_type(type)' failed.
```
where `type` is
```
struct
* members : 
  0: signedbv
    * width : 32
  1: array
    * subtype : struct
        * members : 
          0: signedbv
            * width : 32
          1: signedbv
            * width : 32

        * member_names : 
          0: node_ID
          1: cost

        * member_pretty_names : 
          0: node_ID
          1: cost

        * typename : Link
        * packed : false
    * array_size : constant_int
        * value : 100
        * type : signedbv
          * width : 32
    * size_is_infinite : false

* member_names : 
  0: node_ID
  1: links

* member_pretty_names : 
  0: node_ID
  1: links

* typename : Node
* packed : false
```
Investigating.

**Comment by lucasccordeiro** [comment]
Thanks, @fbrausse.

**Comment by fbrausse** [comment]
The failing Windows test is a timeout, as has happened some times before, cf. https://github.com/esbmc/esbmc/pull/1065#issuecomment-1587262962. Maybe we should mark `regression/esbmc/22_schedule2` as THOROUGH.

**Comment by lucasccordeiro** [comment]
@fbrausse: I fully agree.

**Comment by fbrausse** [comment]
> Investigating.

I've added a fix for the Z3 backend bug. It was an oversight in an earlier commit 139cc366943.

**Comment by fbrausse** [comment]
> The failing Windows test is a timeout, as has happened some times before, cf. [#1065 (comment)](https://github.com/esbmc/esbmc/pull/1065#issuecomment-1587262962). Maybe we should mark `regression/esbmc/22_schedule2` as THOROUGH.

Mh, unfortunately it is a KNOWNBUG and our regression run script doesn't support two annotations simultaneously. @lucasccordeiro if it's OK with you, I'll move it to `regressions/disabled`.

**Comment by lucasccordeiro** [comment]
That's fine.

Thanks, @fbrausse.

**Review by lucasccordeiro — APPROVED** [review]

**Review by rafaelsamenezes — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Many thanks, @fbrausse. We will merge this PR as soon as CI is green.

**Comment by fbrausse** [comment]
> Many thanks, @fbrausse. We will merge this PR as soon as CI is green.

Since this PR touches dereferencing, it might be worth running it over the benchmarks.

**Comment by lucasccordeiro** [comment]
Fine by me.

Can you start it soon?

**Comment by fbrausse** [comment]
> Fine by me.
> 
> Can you start it soon?

Sure, I've started a 30s run over the entire set at https://github.com/esbmc/esbmc/actions/runs/5265683677.

**Comment by lucasccordeiro** [comment]
This PR:

````
2023-06-14T21:38:33.0272097Z Statistics:          26459 Files
2023-06-14T21:38:33.0273542Z   correct:           14374
2023-06-14T21:38:33.0274998Z     correct true:     8162
2023-06-14T21:38:33.0275547Z     correct false:    6212
2023-06-14T21:38:33.0278156Z   incorrect:            61
2023-06-14T21:38:33.0279464Z     incorrect true:     30
2023-06-14T21:38:33.0279975Z     incorrect false:    31
2023-06-14T21:38:33.0280704Z   unknown:           12024
2023-06-14T21:38:33.0281586Z   Score:             21080 (max: 43043)
````

Master:

````
Statistics:          26459 Files
  correct:           14374
    correct true:     8157
    correct false:    6217
  incorrect:            61
    incorrect true:     30
    incorrect false:    31
  unknown:           12024
  Score:             21075 (max: 43043)
````

**Comment by lucasccordeiro** [comment]
@fbrausse: could you please rebase this PR with the master branch?

**Comment by lucasccordeiro** [comment]
Many thanks for submitting this PR, @fbrausse.

**Pull request merged**
