### PR TITLE
Add memory cleanup check

### LINKED ISSUE #325: Option for the valid-memcleanup property
our `--memory-leak-check is actually` to check `G valid-memcleanup`, not `G valid-memtrack`.

### LINKED ISSUE #1257: Wrapper script passing unknown option
Since updating for SV-COMP 2023 (364d95660eec69b146e5911688b41af2dbecea31) we're passing the option `--memory-cleanup-check` here: https://github.com/esbmc/esbmc/blob/b6964a0b5a236ee6025165378bebf257d9891414/scripts/competitions/svcomp/esbmc-wrapper.py#L261

However, ESBMC does not know this option. So all 65 in `valid-memcleanup.MemSafety-MemCleanup` are unknown:
```
ERROR: ESBMC error: unrecognised option '--memory-cleanup-check'
```

### PR DESCRIPTION
**Pull request by fbrausse**
Add option `--no-reachable-memory-leak`. Giving this option in addition to `--memory-leak-check`, we remove some "forgotten memory" results. According to my interpretation in https://github.com/esbmc/esbmc/issues/1029#issuecomment-1674415387 this is in line with what SV-COMP thinks "memsafety" should mean, in terms of what valgrind reports as "reachable":
- memsafety: check for leaks so that no pointer in the program can point to allocated memory anymore
- memcleanup: check for any leaks

So what this PR does: if `--no-reachable-memory-leak` is given, remove - by adding more conditions - leaks of symbols that are referenced in the value-set of globally reachable symbols, where reachable is transitive. In that sense, this `--no-reachable-memleaks` is just an approximation. Additionally, the esbmc-wrapper.py is changed to pass this new option for "memsafety" and to not pass it for "memcleanup".

The changes in this PR may still be a bit rough. I'm happy about any input how to make them better.

### CODE REVIEW

**Comment by fbrausse** [comment]
30s valid-memsafety only:
[Master](https://github.com/esbmc/esbmc/actions/runs/5832919691) (eb7ccc6519fe32e4e6e1e0169fd8c98db40a6281):
```
Statistics:           4541 Files
  correct:            3082
    correct true:     2000
    correct false:    1082
  incorrect:            24
    incorrect true:      1
    incorrect false:    23
  unknown:            1435
  Score:              4682 (max: 7270)
```
[This PR](https://github.com/esbmc/esbmc/actions/runs/5831343981) (d71756d4039178c095137b393249c7b8384b5e18):
```
Statistics:           4541 Files
  correct:            3104
    correct true:     2029
    correct false:    1075
  incorrect:            25
    incorrect true:      3
    incorrect false:    22
  unknown:            1412
  Score:              4685 (max: 7270)
```

valid-memcleanup we didn't support (see also #1257), now [this PR](https://github.com/esbmc/esbmc/actions/runs/5831341036) (d71756d4039178c095137b393249c7b8384b5e18):
```
Statistics:             65 Files
  correct:              64
    correct true:        2
    correct false:      62
  incorrect:             0
    incorrect true:      0
    incorrect false:     0
  unknown:               1
  Score:                66 (max: 67)
```

**Comment by fbrausse** [comment]
Also fixes the example in #1029.

**Comment by fbrausse** [comment]
Getting somewhere with memsafety. [Master](https://github.com/esbmc/esbmc/actions/runs/5832919691) (eb7ccc6519fe32e4e6e1e0169fd8c98db40a6281):
```
Statistics:           4541 Files
  correct:            3082
    correct true:     2000
    correct false:    1082
  incorrect:            24
    incorrect true:      1
    incorrect false:    23
  unknown:            1435
  Score:              4682 (max: 7270)
```
[This PR](https://github.com/esbmc/esbmc/actions/runs/5840990544) (9f52f55b7520bf10d79c9311015d1786206414ea):
```
Statistics:           4541 Files
  correct:            3090
    correct true:     2024
    correct false:    1066
  incorrect:            23
    incorrect true:      3
    incorrect false:    20
  unknown:            1428
  Score:              4698 (max: 7270)
```
But memcleanup isn't as nice anymore as above. https://github.com/esbmc/esbmc/actions/runs/5840989059
```
Statistics:             65 Files
  correct:              36
    correct true:        2
    correct false:      34
  incorrect:             2
    incorrect true:      2
    incorrect false:     0
  unknown:              27
  Score:               -26 (max: 67)
```
I suspect it has something to do with `--no-abnormal-memory-leak`. Still investigating.

**Comment by fbrausse** [comment]
Update for memsafety. [Master](https://github.com/esbmc/esbmc/actions/runs/5832919691) (eb7ccc6519fe32e4e6e1e0169fd8c98db40a6281)
```
Statistics:           4541 Files
  correct:            3082
    correct true:     2000
    correct false:    1082
  incorrect:            24
    incorrect true:      1
    incorrect false:    23
  unknown:            1435
  Score:              4682 (max: 7270)
```
[This PR](https://github.com/esbmc/esbmc/actions/runs/5846768866) (08c7fb3bfa253218ab06de9714811b1c74293096) (a):
```
Statistics:           4541 Files
  correct:            3103
    correct true:     2021
    correct false:    1082
  incorrect:            24
    incorrect true:      2
    incorrect false:    22
  unknown:            1414
  Score:              4708 (max: 7270)
```
And when the wrapper returns the correct fail_memtrack result (b):
https://github.com/esbmc/esbmc/actions/runs/5850183583
```
Statistics:           4541 Files
  correct:            3587
    correct true:     2018
    correct false:    1569
  incorrect:            52
    incorrect true:      1
    incorrect false:    51
  unknown:             902
  Score:              4757 (max: 7270)
```
Appearently, for memcleanup it's better to not use `--no-abnormal-memory-leak`: https://github.com/esbmc/esbmc/actions/runs/5847051448
```
Statistics:             65 Files
  correct:              64
    correct true:        2
    correct false:      62
  incorrect:             0
    incorrect true:      0
    incorrect false:     0
  unknown:               1
  Score:                66 (max: 67)
```
I'll run a full test with merged master and the wrapper still returning "unknown".

**Comment by fbrausse** [comment]
Full run, 30s. [Master](https://github.com/esbmc/esbmc/actions/runs/5846152963/) (80c72be8a5b88c2f485929d44df69a9dbeb590d4):
```
Statistics:          26459 Files
  correct:           14695
    correct true:     8454
    correct false:    6241
  incorrect:            60
    incorrect true:     30
    incorrect false:    30
  unknown:           11704
  Score:             21709 (max: 43043)
```
[This PR](https://github.com/esbmc/esbmc/actions/runs/5853305071) (aeb0b2bb0fb4813556419e476d20134df6852808):
```
Statistics:          26459 Files
  correct:           14763
    correct true:     8466
    correct false:    6297
  incorrect:            59
    incorrect true:     30
    incorrect false:    29
  unknown:           11637
  Score:             21805 (max: 43043)
```

**Comment by lucasccordeiro** [comment]
Excellent, @fbrausse! Well done!

If there are further suggestions/improvements, I would recommend we open an issue to address in another PR.

**Review by lucasccordeiro — APPROVED** [review]

**Pull request merged**
