### PR TITLE
[C++ verification] added memory deallocation check

### PR DESCRIPTION
**Pull request by XLiZHI**
see https://github.com/esbmc/esbmc/pull/1670#discussion_r1486085149

### CODE REVIEW

**Review by fbrausse — COMMENTED** [review]
Great, thank you @XLiZHI! Could you add a positive test case as well (just a modification of the one you already added)?

As a next step, not necessarily in this PR, we might want to consider to disallow passing `new` (and `new[]`) allocated pointers to free(). Same for malloc and delete, I guess.

**Comment by XLiZHI** [comment]
> Great, thank you @XLiZHI! Could you add a positive test case as well (just a modification of the one you already added)?

Hi @fbrausse ,

A positive one could be:
```
int main()
{
  int* IntArray = new int[5];

  delete[] IntArray; 

  return 0;
}
```
But since we already have many similar TCs in the regression, I think maybe we don't need to add it?

**Review by fbrausse — APPROVED** [review]
> But since we already have many similar TCs in the regression, I think maybe we don't need to add it?

I don't really have an overview of the current C++ regression tests. If you believe that's already there, I'm fine with this PR as it is.

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @XLiZHI.

**Pull request merged**
