### PR TITLE
Handle arrays before recursion via build_reference_rec()

### LINKED ISSUE #1336: ESBMC 7.3.0 is crashing with "Can't construct rvalue reference to array type during dereference"
ESBMC 7.3.0 crass in the folllowing small C program:

command : ` esbmc DATASET/FormAI_75935.c --unwind 1`

This isssue is vey similar to the already closed issue: https://github.com/esbmc/esbmc/issues/1087

```c
//FormAI DATASET v1.0 Category: Data mining ; Style: Dennis Ritchie
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define MAX_LINE_LENGTH 256
#define MAX_ENTRIES 1000
#define MAX_CHARS_PER_ENTRY 50
#define MAX_VALUES_PER_ENTRY 5

typedef struct {
    char values[MAX_VALUES_PER_ENTRY][MAX_CHARS_PER_ENTRY];
} Entry;

typedef struct {
    char labels[MAX_VALUES_PER_ENTRY][MAX_CHARS_PER_ENTRY];
    int num_entries;
    Entry entries[MAX_ENTRIES];
} Dataset;

// function to parse a CSV file and populate a Dataset struct
void parse_csv_file(char *filename, Dataset *dataset) {
    FILE *fp;
    char line[MAX_LINE_LENGTH];
    char *token;

    fp = fopen(filename, "r");
    if (fp == NULL) {
        printf("Could not open file %s.", filename);
        exit(EXIT_FAILURE);
    }

    // read the first row as labels
    fgets(line, MAX_LINE_LENGTH, fp);
    token = strtok(line, ",");
    int i = 0;
    while (token != NULL) {
        strcpy(dataset->labels[i], token);
        token = strtok(NULL, ",");
        i++;
    }

    // read the rest of the file as entries
    i = 0;
    while (fgets(line, MAX_LINE_LENGTH, fp) != NULL) {
        Entry entry;
        token = strtok(line, ",");
        int j = 0;
        while (token != NULL) {
            strcpy(entry.values[j], token);
            token = strtok(NULL, ",");
            j++;
        }
        dataset->entries[i] = entry;
        i++;
    }
    dataset->num_entries = i;

    fclose(fp);
}

// function to print the dataset
void print_dataset(Dataset dataset) {
    printf("Num Entries: %d\n", dataset.num_entries);
    printf("Labels: ");
    for (int i = 0; i < MAX_VALUES_PER_ENTRY; i++) {
        printf("%s, ", dataset.labels[i]);
    }
    printf("\n");
    for (int i = 0; i < dataset.num_entries; i++) {
        for (int j = 0; j < MAX_VALUES_PER_ENTRY; j++) {
            printf("%s, ", dataset.entries[i].values[j]);
        }
        printf("\n");
    }
}

int main() {
    Dataset dataset;
    parse_csv_file("data.csv", &dataset);
    print_dataset(dataset);
    return 0;
}
```

OUTPUT: 
```
esbmc DATASET/FormAI_75935.c --unwind 1
ESBMC version 7.3.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing DATASET/FormAI_75935.c
Converting
Generating GOTO Program
GOTO program creation time: 0.106s
GOTO program processing time: 0.001s
Starting Bounded Model Checking
Not unwinding loop 2 iteration 1   file io.c line 126 column 3 function fgets
Not unwinding loop 22 iteration 1   file string.c line 165 column 5 function strspn
Not unwinding loop 23 iteration 1   file string.c line 163 column 3 function strspn
Not unwinding loop 20 iteration 1   file string.c line 127 column 3 function strchr
Not unwinding loop 24 iteration 1   file string.c line 182 column 3 function strcspn
Not unwinding loop 12 iteration 1   file string.c line 30 column 3 function strcpy
Not unwinding loop 22 iteration 1   file string.c line 165 column 5 function strspn
Not unwinding loop 23 iteration 1   file string.c line 163 column 3 function strspn
Not unwinding loop 20 iteration 1   file string.c line 127 column 3 function strchr
Not unwinding loop 24 iteration 1   file string.c line 182 column 3 function strcspn
Not unwinding loop 34 iteration 1   file FormAI_75935.c line 36 column 5 function parse_csv_file
Not unwinding loop 2 iteration 1   file io.c line 126 column 3 function fgets
Not unwinding loop 22 iteration 1   file string.c line 165 column 5 function strspn
Not unwinding loop 23 iteration 1   file string.c line 163 column 3 function strspn
Not unwinding loop 20 iteration 1   file string.c line 127 column 3 function strchr
Not unwinding loop 24 iteration 1   file string.c line 182 column 3 function strcspn
Not unwinding loop 12 iteration 1   file string.c line 30 column 3 function strcpy
Not unwinding loop 22 iteration 1   file string.c line 165 column 5 function strspn
Not unwinding loop 23 iteration 1   file string.c line 163 column 3 function strspn
Not unwinding loop 20 iteration 1   file string.c line 127 column 3 function strchr
Not unwinding loop 24 iteration 1   file string.c line 182 column 3 function strcspn
Not unwinding loop 35 iteration 1   file FormAI_75935.c line 48 column 9 function parse_csv_file
ERROR: Can't construct rvalue reference to array type during dereference
(It isn't allowed by C anyway)
```

### PR DESCRIPTION
**Pull request by fbrausse**
This avoids calling build_reference_rec() for array typed members in multi-dir arrays, and fixes #1336.

The rework mentioned in <https://github.com/esbmc/esbmc/issues/1336#issuecomment-1721067709> has not been done, yet. But it would be good in order to clean up the dereference implementation.

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
Master (https://github.com/esbmc/esbmc/actions/runs/9480972776)

````
2024-06-12T14:26:33.0086102Z Statistics:          23805 Files
2024-06-12T14:26:33.0087166Z   correct:           14192
2024-06-12T14:26:33.0112265Z     correct true:     7804
2024-06-12T14:26:33.0114238Z     correct false:    6388
2024-06-12T14:26:33.0115591Z   incorrect:            42
2024-06-12T14:26:33.0116493Z     incorrect true:     13
2024-06-12T14:26:33.0117552Z     incorrect false:    29
2024-06-12T14:26:33.0118415Z   unknown:            9571
2024-06-12T14:26:33.0145493Z   Score:             21116 (max: 38482)
````

This PR (https://github.com/esbmc/esbmc/actions/runs/9482005398):

````
2024-06-12T15:41:54.0555596Z Statistics:          23805 Files
2024-06-12T15:41:54.0556411Z   correct:           14196
2024-06-12T15:41:54.0557120Z     correct true:     7807
2024-06-12T15:41:54.0558059Z     correct false:    6389
2024-06-12T15:41:54.0558763Z   incorrect:            42
2024-06-12T15:41:54.0559829Z     incorrect true:     13
2024-06-12T15:41:54.0560652Z     incorrect false:    29
2024-06-12T15:41:54.0561338Z   unknown:            9567
2024-06-12T15:41:54.0562047Z   Score:             21123 (max: 38482)
````

**Review by lucasccordeiro — APPROVED** [review]

**Review by rafaelsamenezes — COMMENTED** [review]
@fbrausse would be possible to have a small simple example? I am having trouble identifying the affected cases.

**Comment by fbrausse** [comment]
> @fbrausse would be possible to have a small simple example? I am having trouble identifying the affected cases.

Trying to build a reduced example I noticed another instance of the error. Here is the reduced example:
```c
#include <stdlib.h>
#include <string.h>

typedef struct {
    char values[1][1];
} Entry;

typedef struct {
    Entry entries[1];
} Dataset;

void parse_csv_file(Dataset *dataset) {
    int i = 0;
    Entry entry;
    dataset->entries[i] = entry;
}

int main() {
    Dataset dataset;
    parse_csv_file(&dataset);
    return 0;
}
```
As it still fails with this PR, I'll keep it a draft until that's resolved.

**Comment by fbrausse** [comment]
With latest change, master:
```
Statistics:          23805 Files
  correct:           14192
    correct true:     7804
    correct false:    6388
  incorrect:            42
    incorrect true:     13
    incorrect false:    29
  unknown:            9571
  Score:             21116 (max: 38482)

https://github.com/esbmc/esbmc/actions/runs/9480972776
```
This PR:
```
Statistics:          23805 Files
  correct:           14184
    correct true:     7797
    correct false:    6387
  incorrect:            42
    incorrect true:     13
    incorrect false:    29
  unknown:            9579
  Score:             21101 (max: 38482)

https://github.com/esbmc/esbmc/actions/runs/9489071374
```

**Comment by fbrausse** [comment]
@rafaelsamenezes I can't reduce the example any further. `dataset->entries[i] = entry;` is where construct_from_multidir_array() is being called from construct_struct_ref_from_dyn_offs_rec() for the `Entry::values` member. The original case from the issue was with
```c
char values[1][2];
```
in the above example, where the call stack now looks like this:
```
dereferencet::construct_from_array // case overflows_boundaries; i.e., byte extraction
dereferencet::construct_from_multidir_array
dereferencet::construct_from_array // case is_array_type(arr_subtype)
dereferencet::construct_struct_ref_from_dyn_offs_rec // case is_array_type(value->type) && get_base_array_subtype(value->type)->get_width() == 8
dereferencet::construct_struct_ref_from_dyn_offs_rec // case is_struct_type(value->type)
dereferencet::construct_struct_ref_from_dyn_offs_rec // case is_array_type(value->type) && get_base_array_subtype(value->type)->get_width() != 8
dereferencet::construct_struct_ref_from_dyn_offs_rec // case is_struct_type(value->type)
dereferencet::construct_struct_ref_from_dyn_offset
dereferencet::build_reference_rec
dereferencet::build_reference_to
```
For
```c
char values[1][1];
```
on the other hand the call stack now is this:
```
dereferencet::construct_from_array // case overflows_boundaries; i.e., byte extraction
dereferencet::construct_struct_ref_from_dyn_offs_rec // case is_array_type(value->type) && get_base_array_subtype(value->type)->get_width() == 8
dereferencet::construct_struct_ref_from_dyn_offs_rec // case is_struct_type(value->type)
dereferencet::construct_struct_ref_from_dyn_offset
dereferencet::build_reference_rec
dereferencet::build_reference_to
```

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @fbrausse.

**Pull request merged**
