### PR TITLE
Disable pointer relation check

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
Added the `no-pointer-relation-check` option to assume that all relation comparisons between pointer are legal

### CODE REVIEW

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
Could you please rename the option to "--no-pointer-rel-check"?

Could you also please add this option to "--help" menu?

**Review by lucasccordeiro — APPROVED** [review]

**Comment by mikhailramalho** [comment]
I'm confused here: this patch does nothing, right? I mean, it only adds a new guard to prevent adding checks that are already guarded by `--no-pointer-check` (like all pointers-related checks). 

Even the test cases don't even seem to cover cases like pointer to dynamically allocated memory.

**Comment by rafaelsamenezes** [comment]
> I'm confused here: this patch does nothing, right? I mean, it only adds a new guard to prevent adding checks that are already guarded by `--no-pointer-check` (like all pointers-related checks). 

Wasn't that the ideia? This should make the user able to compare pointers. All the other checks should be enabled

```
int a,b;
return &a<&b;
```

> Even the test cases don't even seem to cover cases like pointer to dynamically allocated memory.

Now I am lost. You mean in a comparation? Doesn't the first test-case do that? Or you meant checking if this doesn't break the other checks over dynamic?

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: Could you add the C program in this issue https://github.com/esbmc/esbmc/issues/273 as a test case in this PR?

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
@mikhailramalho: do you still have comments about this issue?

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: could you please update this branch?

**Pull request merged**
