### PR TITLE
deleted function call for else condition

### PR DESCRIPTION
**Pull request by vanderson-rocha**
Deleted function call for else condition in line 257. The true or false code called the same function

### CODE REVIEW

**Review by mikhailramalho — CHANGES_REQUESTED** [review]
Could you please remove the merge commits from the git tree?

**Comment by vanderson-rocha** [comment]
> Could you please remove the merge commits from the git tree?

Sorry Mikhail. I accidentally clicked on the merge. I don't know how to proceed. Could you help me?

**Comment by mikhailramalho** [comment]
This should work: 
`git pull --rebase`
`git rebase origin master`
`git push -f`

**Comment by vanderson-rocha** [comment]
Removed the merge commits from the git tree. Is it correct now?

**Comment by mikhailramalho** [comment]
Nope, the merge commit is still there.

**Comment by vanderson-rocha** [comment]
I will send  changes in another PR.

**Pull request closed without merging**
