### PR TITLE
Updates C++ regression test suite

### PR DESCRIPTION
**Pull request by feliperodri**
This is the latest version of our C++ benchmarks.

### CODE REVIEW

**Comment by rafaelsamenezes** [comment]
@feliperodri  could you rebase this branch with master? Also, be sure that no file path contains "<", "=" or ">". They tend to break the Windows checkout

**Comment by feliperodri** [comment]
@rafaelsamenezes @mikhailramalho any suggestions/comments before we merge it?

**Comment by rafaelsamenezes** [comment]
This is removing some of the newer tags from esbmc-cpp/cpp which is broking the CI for Linux. I think they should be fixed before the merge.

**Comment by feliperodri** [comment]
@rafaelsamenezes @mikhailramalho any suggestions/comments before we merge it?

**Review by rafaelsamenezes — APPROVED** [review]
LGTM

**Pull request merged**
