### PR TITLE
[clang-cpp-frontend] Fixed error reporting

### PR DESCRIPTION
**Pull request by kunjsong01**
Fixed error reporting in PR #712.
Replaced all `assert(!"error XYZ")` with standard `msg.error` and `fmt` interfaces. 

This PR should have resolved all the outstanding comments, except for [this one](https://github.com/esbmc/esbmc/pull/712#discussion_r889099727) w.r.t to `#include <fmt/core.h>`. Without this line, we won't be able to use the fmt interfaces to report errors.

### CODE REVIEW

**Review by mikhailramalho — APPROVED** [review]
LGTM.

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Review by rafaelsamenezes — APPROVED** [review]

**Review by fbrausse — COMMENTED** [review]
Would you make the function declaration in the class https://github.com/esbmc/esbmc/blob/51bfe6869351687f1088a28a93e51e43caafde19/src/clang-c-frontend/clang_c_convert.h#L67 `static`? Otherwise LGTM.

**Comment by kunjsong01** [comment]
> Would you make the function declaration in the class static? 

Done

**Comment by kunjsong01** [comment]
Commit 068ceb6fd613 fixed issue https://github.com/esbmc/esbmc/issues/720.
The corresponding test cases are added in commit c2d223a5942f.

**Review by fbrausse — APPROVED** [review]
Thank you, LGTM.

**Comment by kunjsong01** [comment]
```
The following tests FAILED:
	1275 - regression/k-induction/cpp_sum_class_bug (Failed)
	1646 - regression/esbmc-cpp/cpp/cpp_sum_class_bug (Failed)
```

These test cases were reported failing because they are marked "KNOWNBUG". But the actual results are correct. I'm enabling both test cases.

**Comment by kunjsong01** [comment]
In our mac CI, the failing test case `regression/k-induction/cpp_sum_class_bug` gives error message: 
```yaml
ESBMC version 6.10.0 64-bit x86_64 macos
Target: 64-bit little-endian x86_64-unknown-macos with esbmc libc
file /Users/runner/work/esbmc/esbmc/regression/k-induction/cpp_sum_class_bug/main.cpp: Parsing
Converting
### ERROR: 
Declaration has an empty name:
CXXConstructorDecl 0x7f84ca92a868 </Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:88:9> col:9 implicit  'void ()' inline default trivial noexcept-unevaluated 0x7f84ca92a868
```
I'm not able to re-produce this error on local mac. The test case works perfectly fine. Output log can be found here. 
[output.txt](https://github.com/esbmc/esbmc/files/8863425/output.txt)

Also tried including the XCode library `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/`, the test case still pass. 
```
./esbmc main.cpp \
-I ../library/ \
--k-induction --verbosity 10 \
-I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/
```

**Pull request merged**
