### PR TITLE
do not call tuple_node_flattener for constant arrays of unions

### PR DESCRIPTION
**Pull request by fbrausse**
This PR addresses #873.

The issue affects Boolector (and maybe others), but not for instance Z3. The memory error is due to a wrong type-cast of an `array_ast` node to a `btor_smt_ast` node despite the Boolector converter implementing `array_iface`. This behaviour was triggered by a construction like this:
```c
union {} f[];
```
~This PR fixes the issue by referring to whatever the actual array-interface of the SMT context is.~ See https://github.com/esbmc/esbmc/pull/917#issuecomment-1459976827

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Review by rafaelsamenezes — APPROVED** [review]

**Review by mikhailramalho — APPROVED** [review]
LGTM.

@rafaelsamenezes can you run it on sv-comp to make sure it doesn't break anything?

**Comment by fbrausse** [comment]
Oh dear, I'll take a look at this fallout.

**Comment by lucasccordeiro** [comment]
@fbrausse : can you please rebase this branch with the master branch?

**Comment by fbrausse** [comment]
Turns out, I had the wrong approach. Sorry about that. The issue is still the same. This PR

1. adds assertions in the debug path for `array_downcast`, `to_solver_smt_ast` and `to_solver_smt_sort` that the casting works
2. now hopefully correctly fixes the #873
3. *edit:* remove harmful `array_downcast` for members of `array_ast` (fixes the issues found in the regression suite after item 1.)

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

Many thanks, @fbrausse.

**Review by mikhailramalho — APPROVED** [review]
LGTM. I would just test it in sv-comp that is no regressions.

**Comment by fbrausse** [comment]
Adding the asserts to the down-casts in solvers/smt caused these to fail with assertion errors:
```
	306 - regression/esbmc-unix2/23_picosat-846_05 (Failed)
	784 - regression/esbmc/struct_bitfields_17 (Failed)
	1900 - regression/nonz3/29_exStbHwAcc (Failed)
```
I've marked them KNOWNBUG but now the `testing_tool_test` complains. What can I do (short of fixing the issues with those tests in this PR)?

**Comment by lucasccordeiro** [comment]
Hi @fbrausse,

> What can I do (short of fixing the issues with those tests in this PR)?

Yes, that would be super if you could fix these issues in this PR.

Many thanks.

**Comment by fbrausse** [comment]
Done.

**Comment by lucasccordeiro** [comment]
> Done.

Thanks, @fbrausse.

**Comment by lucasccordeiro** [comment]
Current Master:

```
Statistics:          26501 Files
correct:           13824
correct true:     8275
correct false:    5549
incorrect:           919
incorrect true:    761
incorrect false:   158
unknown:           11758
Score:             -4781 (max: 43098)
```

This PR:

```
Statistics:          26459 Files
correct:           13796
correct true:     8280
correct false:    5516
incorrect:           916
incorrect true:    761
incorrect false:   155
unknown:           11747
Score:             -4756 (max: 43043)
```

**Comment by lucasccordeiro** [comment]
@fbrausse : could please rebase this branch with the master branch?

**Comment by fbrausse** [comment]
@lucasccordeiro Done, but I think you got the wrong numbers for master. https://github.com/esbmc/esbmc/actions/runs/4365029237 has:
```
Statistics:          26459 Files
  correct:           13792
    correct true:     8275
    correct false:    5517
  incorrect:           916
    incorrect true:    761
    incorrect false:   155
  unknown:           11751
  Score:             -4765 (max: 43043)
```
Those for this PR are correct.

**Comment by lucasccordeiro** [comment]
You are correct, @fbrausse.

Many thanks for working on this issue.

I will merge it as soon as we get the green light from our CI.

**Pull request merged**
