### PR TITLE
esbmc-wrapper: handle no-data-race property

### PR DESCRIPTION
**Pull request by fbrausse**
I'm not sure about the `"FALSE_DATARACE"` string. Where are the possible result output strings listed for each (sub-)property?

An svcomp23 run of this PR just over the no-data-race RunSet is under way: https://github.com/esbmc/esbmc/actions/runs/6822429829

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes might be able to debug this option "FALSE_DATARACE".

**Comment by rafaelsamenezes** [comment]
@fbrausse were you referring to this? https://github.com/sosy-lab/benchexec/blob/7e09a24f1d2b72aa2414df12049246e59f2a8483/benchexec/tools/esbmc.py#L48C5-L48C5

**Comment by fbrausse** [comment]
@rafaelsamenezes I guess I was, thanks for the link! But I see no string (except "FALSE") that would fit for a no-data-race violation.

**Comment by rafaelsamenezes** [comment]
> @rafaelsamenezes I guess I was, thanks for the link! But I see no string (except "FALSE") that would fit for a no-data-race violation.

I guess this was long removed from us. We need to add in there as well.

**Comment by fbrausse** [comment]
> > I guess I was, thanks for the link! But I see no string (except "FALSE") that would fit for a no-data-race violation.
> 
> I guess this was long removed from us. We need to add in there as well.

PR against benchexec?

**Comment by rafaelsamenezes** [comment]
> > > I guess I was, thanks for the link! But I see no string (except "FALSE") that would fit for a no-data-race violation.
> > 
> > I guess this was long removed from us. We need to add in there as well.
> 
> PR against benchexec?

Yeah, but I can't find what should be the actual result for data-race.

**Comment by fbrausse** [comment]
Maybe `RESULT_FALSE_PROP + "(no-data-race)"` similar to the others: https://github.com/sosy-lab/benchexec/blob/7e09a24f1d2b72aa2414df12049246e59f2a8483/benchexec/result.py#L67-L86

**Comment by fbrausse** [comment]
It seemed to work as it is, benchexec classifies this as "false(unreach-call)" and marks it green when it matches the "false" verdict from the .yml file.
```
Statistics:            783 Files
  correct:             333
    correct true:      303
    correct false:      30
  incorrect:            24
    incorrect true:     20
    incorrect false:     4
  unknown:             426
  Score:               -68 (max: 1488)

https://github.com/esbmc/esbmc/actions/runs/6822429829
```
Incorrect true (IT) and false (IF) ones:
- c/pthread-lit/qw2004-2.yml [IT]
- c/goblint-regression/02-base_24-malloc_races.yml [IT]
- c/goblint-regression/02-base_25-malloc_race_cp.yml [IT]
- c/goblint-regression/02-base_26-malloc_struct.yml [IT]
- c/goblint-regression/04-mutex_10-ptrmunge_nr.yml [IF]
- c/goblint-regression/04-mutex_11-ptr_rc.yml [IT]
- c/goblint-regression/04-mutex_14-funarg_rc.yml [IT]
- c/goblint-regression/04-mutex_20-stdfun_rc.yml [IT]
- c/goblint-regression/04-mutex_21-sound_base.yml [IT]
- c/goblint-regression/04-mutex_22-deref_read.yml [IF]
- c/goblint-regression/04-mutex_25-single_acc.yml [IT]
- c/goblint-regression/04-mutex_27-base_rc.yml [IT]
- c/goblint-regression/04-mutex_37-indirect_rc.yml [IT]
- c/goblint-regression/04-mutex_45-escape_rc.yml [IT]
- c/goblint-regression/04-mutex_47-fun_write.yml [IT]
- c/goblint-regression/04-mutex_50-funptr_rc.yml [IT]
- c/goblint-regression/04-mutex_55-pt_rwlock_rr.yml [IT]
- c/goblint-regression/05-lval_ls_08-glob_fld_2_rc.yml [IT]
- c/goblint-regression/05-lval_ls_15-fldunknown_access.yml [IT]
- c/goblint-regression/06-symbeq_02-funloop_norace.yml [IF]
- c/goblint-regression/06-symbeq_10-equ_rc.yml [IT]
- c/goblint-regression/06-symbeq_15-list_entry_nr.yml [IF]
- c/goblint-regression/09-regions_03-list2_rc.yml [IT]
- c/goblint-regression/09-regions_28-list2alloc.yml [IT]

**Comment by lucasccordeiro** [comment]
Excellent! Many thanks, @fbrausse. I'm fine to merge this PR.

@XLiZHI: could you please check the incorrect results?

**Comment by lucasccordeiro** [comment]
BTW, I believe once we merge this PR https://github.com/esbmc/esbmc/pull/1463, we might get better results here.

**Comment by fbrausse** [comment]
> I'm fine to merge this PR.

Great, after that let's update @XLiZHI's #1460 branch and see how it does on the sv-comp benchmarks.

**Comment by lucasccordeiro** [comment]
@fbrausse: can I ask you please to rerun this PR over the concurrency benchmarks?

**Comment by fbrausse** [comment]
Not a big change.
```
Statistics:            783 Files
  correct:             335
    correct true:      305
    correct false:      30
  incorrect:            24
    incorrect true:     20
    incorrect false:     4
  unknown:             424
  Score:               -64 (max: 1488)

https://github.com/esbmc/esbmc/actions/runs/6833596642
```

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @fbrausse.

**Comment by lucasccordeiro** [comment]
> Incorrect true (IT) and false (IF) ones:

The current master seems to fix some of these incorrect results.

**Comment by lucasccordeiro** [comment]
Source: https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/goblint-regression/04-mutex_11-ptr_rc.c?ref_type=heads

````C
#include <pthread.h>
#include <stdio.h>

int myglobal;
pthread_mutex_t mutex1 = PTHREAD_MUTEX_INITIALIZER;
pthread_mutex_t mutex2 = PTHREAD_MUTEX_INITIALIZER;

void *t_fun(void *arg) {
  int *p = &myglobal;
  pthread_mutex_lock(&mutex1);
  *p = *p + 1; // RACE!
  pthread_mutex_unlock(&mutex1);
  return NULL;
}

int main(void) {
  pthread_t id;
  pthread_create(&id, NULL, t_fun, NULL);
  pthread_mutex_lock(&mutex2);
  myglobal=myglobal+1; // RACE!
  pthread_mutex_unlock(&mutex2);
  pthread_join (id, NULL);
  return 0;
}
````

ESBMC counterexample:

````
State 3 file data-race4.c line 20 column 3 function main thread 0
----------------------------------------------------
Violated property:
  file data-race4.c line 20 column 3 function main
  W/W data race on c:@myglobal
  !tmp_c:@myglobal


VERIFICATION FAILED
````

**Comment by lucasccordeiro** [comment]
@fbrausse: After merging this PR https://github.com/esbmc/esbmc/pull/1477, can I ask you whether we still provide incorrect results for the data-race check?

**Comment by fbrausse** [comment]
> @fbrausse: After merging this PR #1477, can I ask you whether we still provide incorrect results for the data-race check?

Here they are, very promising: https://github.com/esbmc/esbmc/pull/1477#issuecomment-1808589904

**Comment by lucasccordeiro** [comment]
> Here they are, very promising: [#1477 (comment)](https://github.com/esbmc/esbmc/pull/1477#issuecomment-1808589904)

I fully agree ;-)

**Pull request merged**
