### PR TITLE
Infinity array bounds are no longer checked

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
Following #1431 , this PR disables checking bounds of infinity arrays.

The test `regression/esbmc-unix2/28_memory_leak_01` is now marked as a KNOWNBUG. The "verification failed" was due to the out-of-bounds issue and the test never found the actual memleak.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: can you please run this PR over the SV-COMP benchmarks?

**Comment by rafaelsamenezes** [comment]
This PR
```
Statistics:          23805 Files
  correct:           14216
    correct true:     7830
    correct false:    6386
  incorrect:            20
    incorrect true:      5
    incorrect false:    15
  unknown:            9569
  Score:             21646 (max: 38482)
```

Master (30s)
```
Statistics:          23805 Files
  correct:           14200
    correct true:     7816
    correct false:    6384
  incorrect:            19
    incorrect true:      4
    incorrect false:    15
  unknown:            9586
  Score:             21648 (max: 38482)
```

Apparently, it increased the correct true at the cost of a few correct false. Also, it solves some previous unknown case.

~~I will check the extra incorrect true, it might be unrelated to the PR itself.~~ The extra  incorrect true is noise, the test used to be a timeout in other runs.

**Comment by lucasccordeiro** [comment]
Excellent! 

Many thanks, @rafaelsamenezes.

**Review by lucasccordeiro — APPROVED** [review]

**Review by fbrausse — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @rafaelsamenezes.

**Pull request merged**
