### PR TITLE
[Operational Model] Replaced malloc with __ESBMC_alloca in getenv

### PR DESCRIPTION
**Pull request by lucasccordeiro**

### CODE REVIEW

**Comment by mikhailramalho** [comment]
alloca won't fix the problem, see https://github.com/esbmc/esbmc/issues/652#issuecomment-1664036227

**Comment by lucasccordeiro** [comment]
This PR (with the original SV-COMP script):
GitHub Actions: https://github.com/esbmc/esbmc/actions/runs/5749018775/job/15583770577
````
 Statistics:          26459 Files
   correct:           14374
     correct true:     8171
     correct false:    6203
   incorrect:            59
     incorrect true:     29
     incorrect false:    30
   unknown:           12026
   Score:             21137 (max: 43043)
````

[Master](https://github.com/esbmc/esbmc/actions/runs/5744047334) (406a09073c9bc301390bea1671999e4295dbbc2c):
```
Statistics:          26459 Files
  correct:           14366
    correct true:     8139
    correct false:    6227
  incorrect:            59
    incorrect true:     29
    incorrect false:    30
  unknown:           12034
  Score:             21097 (max: 43043)
```

**Comment by lucasccordeiro** [comment]
I'm now running this PR with the memory-leak check enabled in the SV-COMP script:

https://github.com/esbmc/esbmc/actions/runs/5769027423

**Comment by lucasccordeiro** [comment]
@fbrausse: can I ask you whether you could check the difference in the correct false and true?

**Comment by fbrausse** [comment]
This SV-COMP run was on a branch without the #1248 merged yet, so these previous [master](https://github.com/esbmc/esbmc/actions/runs/5699725875) (8bf4ef883c3cac2b49961bbc38382904ee9780ff) values make more sense to compare to:
```
Statistics:          26459 Files
  correct:           14365
    correct true:     8166
    correct false:    6199
  incorrect:            59
    incorrect true:     29
    incorrect false:    30
  unknown:           12035
  Score:             21123 (max: 43043)
```
vs this PR (f4032de4905a6d86778cc804bacc373ff0c0a9e8) from Lucas' above comment
```
 Statistics:          26459 Files
   correct:           14374
     correct true:     8171
     correct false:    6203
   incorrect:            59
     incorrect true:     29
     incorrect false:    30
   unknown:           12026
   Score:             21137 (max: 43043)
```
There is some usual timeout fluctuation. Besides that:
- c/recursive-simple/fibo_20-1
- c/recursive-simple/fibo_20-2
- c/recursive-simple/fibo_2calls_20-1.c
- c/recursive-simple/fibo_2calls_20-2.c
- c/ldv-linux-3.4-simple/32_1_cilled_ok_nondet_linux-3.4-32_1-drivers--mtd--devices--mtdram.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i

got measurably faster (timeout 30s -> 10-20 seconds), while others got slower (15-20s -> timeout):
- c/aws-c-common/aws_linked_list_pop_front_harness_negated.i
- c/aws-c-common/aws_linked_list_swap_contents_harness_negated.i

In valid-memsafety we have 2x unknown -> timeout:
- c/ldv-linux-3.14-races/linux-3.14--drivers--net--irda--w83977af_ir.ko.cil.i
- c/pthread-C-DAC/pthread-numerical-integration.i

That's all the changes I can see.

**Comment by lucasccordeiro** [comment]
This PR with the memory-leak check enabled in the SV-COMP scripts:
GitHub actions: https://github.com/esbmc/esbmc/actions/runs/5769027423
````
 Statistics:          26459 Files
   correct:           14857
     correct true:     8166
     correct false:    6691
   incorrect:           189
     incorrect true:     29
     incorrect false:   160
   unknown:           11413
   Score:             19535 (max: 43043)
````

**Comment by lucasccordeiro** [comment]
I have open this issue to investigate the memory leak check in ESBMC: https://github.com/esbmc/esbmc/issues/1259

**Pull request merged**
