### PR TITLE
Changed default sv-benchmarks tag to svcomp23

### LINKED ISSUE #1249: [sv-comp] check whether we're using the SV-COMP 2023 benchmarks
Our statistics show 26459 file, but SV-COMP reports only 23805.

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
As disscussed at https://github.com/esbmc/esbmc/issues/1315#issuecomment-1715272865

I also started a full 5s run just to double check.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Comment by rafaelsamenezes** [comment]
Just to note: I removed the "coreutils" benchmarks as suggested by @fbrausse. However, in the svcomp report it says that the svcomp23 of the definitions should be https://gitlab.com/sosy-lab/sv-comp/bench-defs/-/blob/svcomp23/benchmark-defs/esbmc-kind.xml?ref_type=tags which contain the coreutils.

**Comment by fbrausse** [comment]
Interesting, thanks @rafaelsamenezes. Is there maybe a switch for the benchexec tool to ignore these empty set definitions, which they are using?

**Comment by rafaelsamenezes** [comment]
They basically run this script: https://gitlab.com/sosy-lab/benchmarking/competition-scripts/-/blob/main/execute_runs/execute-runcollection.sh?ref_type=heads

With these flags: https://gitlab.com/sosy-lab/benchmarking/competition-scripts/#executing-only-runs-for-producing-results

**Review by fbrausse — APPROVED** [review]

**Comment by rafaelsamenezes** [comment]
Ok, apparently everything went fine with the 5s run: https://github.com/esbmc/esbmc/actions/runs/6157829101

**Pull request merged**
