### PR TITLE
[clang-c*-frontend] Minor fixes

### PR DESCRIPTION
**Pull request by kunjsong01**
some minor fixes.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Review by fbrausse — COMMENTED** [review]
`irep_idt` parameters don't need to be `const` (or const-ref): it is just a fancy wrapper around an integer.

**Comment by kunjsong01** [comment]
> irep_idt parameters don't need to be const

@fbrausse Why does it not need to be const? 

Is it because of:
1. `irep_idt` is `dstring`
2. the unsigned integer `dstring.no` is a private number
3. there is no public setter method to set `dstring.no`

So `dstring.no` is inherently immutable?

That's just my guess. I tend to write the code in a more defensive way, sometimes could be unnecessary, of course.

**Comment by fbrausse** [comment]
> Is it because of: [123]

Actually nothing that involved. The previous version had a non-const parameter `const char *mode`. `mode` itself is a non-const variable passed by-value. And that's fine, since it's just a pointer. Same now: `irep_idt` is just an integer that can be passed by-value. It's being copied into the `::mode` member (or passed to follow-up ctors by-value) anyway, there is no need to qualify it in any way, it's just visual noise.

**Comment by fbrausse** [comment]
I'm talking about the parameters to the constructors, the member `::mode` itself can be `const`. Sorry for the confusion.

**Comment by kunjsong01** [comment]
>Same now: irep_idt is just an integer that can be passed by-value. It's being copied into the ::mode member (or passed to follow-up ctors by-value) anyway,

I see. Thanks for the answer. 
Removed the const qualifier.

**Review by fbrausse — APPROVED** [review]
Great, many thanks for addressing my comments!

**Comment by kunjsong01** [comment]
> Great, many thanks for addressing my comments!

np thanks for the reviewing

**Comment by kunjsong01** [comment]
CI: 
Windows build failed with step "install gnu tools"

**Comment by fbrausse** [comment]
@kunjsong01 might be temporary; the CI on another PR seems to be able to do this. After all tasks here are finished, you can (probably?) restart the failed tasks here. "Details" -> "Re-run jobs" (upper right).

**Pull request merged**
