### PR TITLE
implemented push/pop for Bitwuzla and Boolector

### PR DESCRIPTION
**Pull request by lucasccordeiro**
This PR implements the pus/pop methods for incremental solving with the SMT solvers Bitwuzla and Boolector.

### CODE REVIEW

**Review by mikhailramalho — APPROVED** [review]
LGTM

**Review by rafaelsamenezes — CHANGES_REQUESTED** [review]
The code itself looks good, however from the [docs](https://bitwuzla.github.io/docs/c/interface.html?highlight=pop) for both push and pop:

```
Requires that incremental solving has been enabled via bitwuzla_set_option().
```

**Comment by mikhailramalho** [comment]
> The code itself looks good, however from the [docs](https://bitwuzla.github.io/docs/c/interface.html?highlight=pop) for both push and pop:
> 
> ```
> Requires that incremental solving has been enabled via bitwuzla_set_option().
> ```

And I suspect Boolector needs the same option to enable incremental solving.

**Comment by lucasccordeiro** [comment]
It is already in the master from a previous PR: https://github.com/esbmc/esbmc/blob/master/src/solvers/boolector/boolector_conv.cpp#L39

**Review by rafaelsamenezes — APPROVED** [review]
LGTM

**Pull request merged**
