### PR TITLE
Added sscanf OM

### PR DESCRIPTION
**Pull request by rafaelsamenezes**

### CODE REVIEW

**Review by fbrausse — APPROVED** [review]
Nice, fixes all 3 sv-comp tasks reorder_[25]-2 and twostage_3-2!

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @rafaelsamenezes.

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: could you please fix the CI?

**Comment by fbrausse** [comment]
The CI doesn't really say much, just
```
2023-11-23T08:49:03.6656622Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2023-11-23T08:49:03.6661614Z ##[error]Process completed with exit code 143.
```
My guess would be memory usage, possibly due to variables initialized with `sscanf` now having unbounded values in some regression tests.

**Comment by rafaelsamenezes** [comment]
@fbrausse yeah, most of then is because some loops are "symbolically bounded" now. I am running locally and setting a timeout on ctest to identify the ones that are affected. Most of time is just a matter of adding a strategy.

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: Thanks for submitting this PR.

**Pull request merged**
