### PR TITLE
Updated to newer Boolector version 3.2.2

### PR DESCRIPTION
**Pull request by lucasccordeiro**
This PR will evaluate the newer Boolector version 3.2.2 over the SV-COMP benchmarks.

### CODE REVIEW

**Review by rafaelsamenezes — CHANGES_REQUESTED** [review]
You also need to update in the following places:

1. https://github.com/esbmc/esbmc/blob/master/.github/workflows/build.yml#L111
2. https://github.com/esbmc/esbmc/blob/master/.github/workflows/release.yml#L23
3. https://github.com/esbmc/esbmc/blob/master/.github/workflows/release.yml#L50
4. https://github.com/esbmc/esbmc/blob/master/.github/workflows/benchexec.yml#L31

**Review by rafaelsamenezes — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
I'm now running this PR over the SV-COMP benchmarks at https://github.com/esbmc/esbmc/actions/runs/2542554237.

**Comment by lucasccordeiro** [comment]
This PR:

```
Statistics:          15648 Files
  correct:            8455
    correct true:     5128
    correct false:    3327
  incorrect:            53
    incorrect true:     24
    incorrect false:    29
  unknown:            7140
  Score:             12351 (max: 25567)
```

Master:

```
Statistics:          15648 Files
  correct:            8457
    correct true:     5137
    correct false:    3320
  incorrect:            54
    incorrect true:     25
    incorrect false:    29
  unknown:            7137
  Score:             12330 (max: 25567)
```

**Comment by fbrausse** [comment]
Should we update the building instructions? Or are they referring to the least version supported?

**Comment by lucasccordeiro** [comment]
Well spotted! I've just updated it via https://github.com/esbmc/esbmc/commit/7863612cf8dacf92741845520db5adb13ca29e59.

**Pull request merged**
