### PR TITLE
Bump boolector version

### PR DESCRIPTION
**Pull request by pmatos**

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Review by rafaelsamenezes — CHANGES_REQUESTED** [review]
Could you make this change for [macOS](https://github.com/esbmc/esbmc/blob/master/.github/workflows/build.yml#L63) as well?

**Comment by pmatos** [comment]
Sure. I will take a look. Give me a few hours...

**Comment by pmatos** [comment]
Updated macos, squashed commits and force-pushed.

**Review by rafaelsamenezes — APPROVED** [review]
LGTM

**Pull request merged**
