### PR TITLE
Turn smtlib build optional

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
They are dependencies for using the smtlib interface which:

- Makes windows builds depends on a third-party implementation of them.
- Should not be mandatory.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Comment by fbrausse** [comment]
If the smtlib backend is going to be optional, there should be a switch to enable or disable it. Building it depending on whether flex/bison is found on the host OS alone is never a good idea: Can't be sure of the build configuration on an unknown system + it's near impossible to give reliable instructions how to build ESBMC with the smtlib backend enabled.

**Comment by fbrausse** [comment]
Also, https://github.com/esbmc/esbmc/blob/c9cd2646987a91ad0b96ab287aee0c990a30a3fa/src/solvers/solve.cpp#L21 assumes that the smtlib backend is always available.

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
Shall we update the building instructions?

**Review by fbrausse — APPROVED** [review]
LGTM.

**Review by lucasccordeiro — APPROVED** [review]

**Pull request merged**
