### PR TITLE
[CUDA OM] replaced __ESBMC_alloca with infinite array size

### PR DESCRIPTION
**Pull request by lucasccordeiro**

### CODE REVIEW

**Review by mikhailramalho — COMMENTED** [review]
great idea!

**Comment by lucasccordeiro** [comment]
It reduced the verification time substantially!

**Comment by lucasccordeiro** [comment]
@fbrausse: could you please look at this issue about infinite array size?

regression/cuda/benchmarks/017_equality_abstraction_issue

````
e$ esbmc main.cu --force-malloc-success --co
ntext-bound 3 --unwind 9 --state-hashing --data-races-check --no-bounds-check
ESBMC version 7.3.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.740s
Adding Data Race Checks
terminate called after throwing an instance of 'array_type2t::inf_sized_array_excp'
Aborted
````

**Comment by lucasccordeiro** [comment]
Thanks for fixing the issue, @fbrausse.

**Pull request merged**
