### PR TITLE
[util] harden binary2integer

### PR DESCRIPTION
**Pull request by intrigus-lgtm**
This would have easily found https://github.com/esbmc/esbmc/pull/2131 instead of having to many, many hours trying to track down whether the counter example I got after 24 hours is bogus or not.
In hindsight I should have started to check whether values in the counter example trace are correct or not, but who really expects bugs there :cry: 

(**Depends on https://github.com/esbmc/esbmc/pull/2131 being merged before**)

### CODE REVIEW

**Comment by intrigus-lgtm** [comment]
Note: outside of debug builds, this would still happily return more or less bogus results.
I'm happy to change the code to `abort` also in release instead of returning `0` if this is acceptable to you.

(Let's see whether CI hits any code that relies on this IMHO weird behavior)

**Review by lucasccordeiro — APPROVED** [review]

**Review by mikhailramalho — APPROVED** [review]
LGTM.

Next time, use the PR summary to explain the issue it's fixing.

**Comment by lucasccordeiro** [comment]
@intrigus-lgtm: The following regression tests are failing:

````
The following tests FAILED:
	2196 - regression/bitwuzla/builtin-alloca-bad (Failed)
	2199 - regression/bitwuzla/double-free (Failed)
	2202 - regression/bitwuzla/github_536_bitwuzla (Failed)
	2204 - regression/bitwuzla/incremental-03 (Failed)
	2209 - regression/bitwuzla/union-bad (Failed)
Errors while running CTest
````

**Comment by intrigus-lgtm** [comment]
> @intrigus-lgtm: The following regression tests are failing:
> 
> ```
> The following tests FAILED:
> 	2196 - regression/bitwuzla/builtin-alloca-bad (Failed)
> 	2199 - regression/bitwuzla/double-free (Failed)
> 	2202 - regression/bitwuzla/github_536_bitwuzla (Failed)
> 	2204 - regression/bitwuzla/incremental-03 (Failed)
> 	2209 - regression/bitwuzla/union-bad (Failed)
> Errors while running CTest
> ```

Those should pass now after merging in master.

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @intrigus-lgtm.

**Pull request merged**
