### PR TITLE
[OM] Fix parse errors in string

### PR DESCRIPTION
**Pull request by kunjsong01**
Fixed all parse errors in https://github.com/esbmc/esbmc/issues/832 

N.B. The string OM file needs a retab when approved.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

@kunjsong01: Can we enable existing regression tests with this PR?

**Comment by kunjsong01** [comment]
> Can we enable existing regression tests with this PR?

@lucasccordeiro Not yet. After fixing all the parse errors, we got an assertion failure - https://github.com/esbmc/esbmc/issues/989

**Comment by lucasccordeiro** [comment]
@kunjsong01: if you can now concentrate on this assertion failure, that would be great.

**Review by rafaelsamenezes — COMMENTED** [review]
Why do you need these?

**Comment by kunjsong01** [comment]
> Why do you need these?

This PR fixed the parse errors in `string` OM for C++ std::string stuff.

**Pull request merged**
