### PR TITLE
[C verification] support Atomic typecast

### LINKED ISSUE #2142: false positive: incompatible pointer types passing 'bool *' (aka 'int *') to parameter of type '_Bool *'
This is a simple reproducer:
```
#include <stdatomic.h>
#include <stdbool.h>

int
main(void) {
        atomic_bool x = false;
        (void)atomic_compare_exchange_strong(&x, &(bool){ false }, true);

        return 0;
}
```

result is:

```
ESBMC version 7.7.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing a.c
a.c:7:43: warning: incompatible pointer types passing 'bool *' (aka 'int *') to parameter of type '_Bool *' [-Wincompatible-pointer-types]
        (void)atomic_compare_exchange_strong(&x, &(bool){ false }, true);
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/llvm-14/lib/clang/14.0.6/include/../include/stdatomic.h:135:112: note: expanded from macro 'atomic_compare_exchange_strong'
#define atomic_compare_exchange_strong(object, expected, desired) __c11_atomic_compare_exchange_strong(object, expected, desired, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST)
                                                                                                               ^~~~~~~~
Converting
ERROR: Conversion of unsupported clang cast operator: "NonAtomicToAtomic" to expression
ImplicitCastExpr 0x55dc528f8a50 </tmp/esbmc.b01a-675c-cb76/headers/stdbool.h:6:15> 'atomic_bool':'_Atomic(_Bool)' <NonAtomicToAtomic>
`-ImplicitCastExpr 0x55dc528f8a38 <col:15> '_Bool' <IntegralToBoolean>
  `-IntegerLiteral 0x55dc528f8a18 <col:15> 'int' 0

ERROR: CONVERSION ERROR
```

Unfortunately, even with:
```c
#include <stdatomic.h>
#include <stdbool.h>

int
main(void) {
        atomic_bool x = false;
        bool exp = false;
        (void)atomic_compare_exchange_strong(&x, &exp, true);

        return 0;
}
```

the error remains:

```
ESBMC version 7.7.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing a.c
a.c:8:43: warning: incompatible pointer types passing 'bool *' (aka 'int *') to parameter of type '_Bool *' [-Wincompatible-pointer-types]
        (void)atomic_compare_exchange_strong(&x, &exp, true);
                                                 ^~~~
/usr/lib/llvm-14/lib/clang/14.0.6/include/../include/stdatomic.h:135:112: note: expanded from macro 'atomic_compare_exchange_strong'
#define atomic_compare_exchange_strong(object, expected, desired) __c11_atomic_compare_exchange_strong(object, expected, desired, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST)
                                                                                                               ^~~~~~~~
Converting
ERROR: Conversion of unsupported clang cast operator: "NonAtomicToAtomic" to expression
ImplicitCastExpr 0x562683b63a20 </tmp/esbmc.8508-9d65-4ba0/headers/stdbool.h:6:15> 'atomic_bool':'_Atomic(_Bool)' <NonAtomicToAtomic>
`-ImplicitCastExpr 0x562683b63a08 <col:15> '_Bool' <IntegralToBoolean>
  `-IntegerLiteral 0x562683b639e8 <col:15> 'int' 0

ERROR: CONVERSION ERROR
```

My uneducated guess is that it has something to do with:

```c
#include <stdatomic.h>
#include <stdbool.h>

int
main(void) {
	_Atomic(_Bool) x = false;
	_Bool exp = false;
	(void)atomic_compare_exchange_strong(&x, &exp, true);

	return 0;
}
```

still erroring with:

```
ESBMC version 7.7.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing a.c
Converting
ERROR: Conversion of unsupported clang cast operator: "NonAtomicToAtomic" to expression
ImplicitCastExpr 0x5589b7c25a40 </tmp/esbmc.f476-19c0-1f2c/headers/stdbool.h:6:15> '_Atomic(_Bool)' <NonAtomicToAtomic>
`-ImplicitCastExpr 0x5589b7c25a28 <col:15> '_Bool' <IntegralToBoolean>
  `-IntegerLiteral 0x5589b7c25a08 <col:15> 'int' 0

ERROR: CONVERSION ERROR
```

### LINKED ISSUE #2148: [Clang-C Frontend] Conversion of unsupported clang cast operator: "NonAtomicToAtomic" to expression
$ esbmc butterfly.c

````C
// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2024 The SV-Benchmarks community
//
// SPDX-License-Identifier: Apache-2.0

#include <pthread.h>
#include <stdatomic.h>
#include <assert.h>

extern void abort(void);
void reach_error() { assert(0); }
void __VERIFIER_assert(int expression) { if (!expression) { ERROR: {reach_error();abort();}}; return; }

// For most memory models (including SC), it is not possible to derive all coherence orders in polynomial time [1].
// In fact, this program (coming from Fig. 6 in [2]) is a counter example to Theorem 2 in [3].

// [1] Florian Furbach, Roland Meyer, Klaus Schneider, Maximilian Senftleben: Memory-Model-Aware Testing: A Unified Complexity Analysis. ACM Trans. Embed. Comput. Syst. 14(4): 63:1-63:25 (2015)
// [2] Liangze Yin, Wei Dong, Wanwei Liu, Ji Wang: On Scheduling Constraint Abstraction for Multi-Threaded Program Verification. IEEE Trans. Software Eng. 46(5): 549-565 (2020)
// [3] Zhihang Sun, Hongyu Fan, Fei He: Consistency-preserving propagation for SMT solving of concurrent program verification. Proc. ACM Program. Lang. 6(OOPSLA2): 929-956 (2022)

// Contributed-by: Hernan Ponce de Leon (Dartagnan Team)

atomic_int m,n,x,y,w;
atomic_int success = 0;

void *p0(void *arg) {
    int rw = w; // w==2
    m = 1;
    int rx = x; // x==1
    if (rw == 2 && rx == 1) {
        success++;
    }
}

void *p1(void *arg) {
    int rw = w; // w==1
    n = 1;
    int ry = y; // y==2
    if (rw == 1 && ry == 2) {
        success++;
    }
}

void *p2(void *arg) {
    x = 1;
    w = 1;
    y = 1;
    int rn = n; // n == 2
    if (rn == 2) {
        success++;
    }
}

void *p3(void *arg) {
    y = 2;
    w = 2;
    x = 2;
    int rm = m; // m == 2
    if (rm == 2) {
        success++;
    }
}

void *p4(void *arg) {
    n = 2;
    int rw = w; // w==2
    if (rw == 2) {
        success++;
    }
}

void *p5(void *arg) {
    m = 2;
    int rw = w; // w==1
    if (rw == 1) {
        success++;
    }
}

int main()
{
    pthread_t t1, t2, t3, t4, t5, t6;

    pthread_create(&t1, NULL, p0, NULL);
    pthread_create(&t2, NULL, p1, NULL);
    pthread_create(&t3, NULL, p2, NULL);
    pthread_create(&t4, NULL, p3, NULL);
    pthread_create(&t5, NULL, p4, NULL);
    pthread_create(&t6, NULL, p5, NULL);

    pthread_join(t1, 0);
    pthread_join(t2, 0);
    pthread_join(t3, 0);
    pthread_join(t4, 0);
    pthread_join(t5, 0);
    pthread_join(t6, 0);

    __VERIFIER_assert(success < 6);

    return 0;
}
````

````
ESBMC version 7.7.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing butterfly.c
butterfly.c:35:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
butterfly.c:44:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
butterfly.c:54:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
butterfly.c:64:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
butterfly.c:72:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
butterfly.c:80:1: warning: non-void function does not return a value [-Wreturn-type]
}
^
Converting
ERROR: Conversion of unsupported clang cast operator: "NonAtomicToAtomic" to expression
ImplicitCastExpr 0x7aafaa8 <butterfly.c:26:22> 'atomic_int':'_Atomic(int)' <NonAtomicToAtomic>
`-IntegerLiteral 0x7aafa88 <col:22> 'int' 0

ERROR: CONVERSION ERROR
````

### LINKED ISSUE #2149: [Clang-C Frontend] ERROR: Conversion of unsupported clang cast operator: "AtomicToNonAtomic" to expression
$ esbmc exponential-nondet.c

````C
// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2024 Budapest University of Technology and Economics
//
// SPDX-License-Identifier: Apache-2.0

#define N __VERIFIER_nondet_int()

// This file is part of the SV-Benchmarks collection of verification tasks:
// https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks
//
// SPDX-FileCopyrightText: 2024 Budapest University of Technology and Economics
//
// SPDX-License-Identifier: Apache-2.0

#include <assert.h>
#include <pthread.h>
#include <stdatomic.h>
#include <limits.h>

extern int __VERIFIER_nondet_int();
extern void abort(void);
void assume_abort_if_not(int cond) {
  if(!cond) {abort();}
}
void reach_error() { assert(0); }
void __VERIFIER_assert(int expression) { if (!expression) { ERROR: {reach_error();abort();}}; return; }

atomic_uint y; // assignment to y is always between 0 and INT_MAX/2, therefore 2*y is always between 0 and INT_MAX
void *f1(void *arg) { // N threads with f1
  y = (y + 1) % (INT_MAX / 2);
  return 0;
}
void *f2(void *arg) { // N threads with f2
  y = (2 * y) % (INT_MAX / 2);
  return 0;
}
int main() {
  int _N = N;
  int x, p, i;
  unsigned int z;
  pthread_t t;
  p = 0;
  while(p < _N) {
    pthread_create(&t, 0, f1, 0);
    pthread_create(&t, 0, f2, 0);
    p++;
  }
  z = 0;
  i = 0;
  while(i < _N) {
    assume_abort_if_not(z < INT_MAX); // z is always between 0 and INT_MAX
    z = z + 2 * y; // the z % 2 == 0 predicate remains the same
                   // z and 2*y are always between 0 and INT_MAX, so z + 2*y fits in an unsigned int
    i++;
  }
  if(z % 2 == 0) { // z % 2 == 0 was initially true and have not been affected, so it is always true
    x = 0;
  } else {
    x = 1;
  }
  __VERIFIER_assert(x * y == 0); // x is always 0, so this always holds
  return 0;
}
````

````
ESBMC version 7.7.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing exponential-nondet.c
Converting
ERROR: Conversion of unsupported clang cast operator: "AtomicToNonAtomic" to expression
ImplicitCastExpr 0x7f79770 <exponential-nondet.c:32:8> 'unsigned int' <AtomicToNonAtomic>
`-ImplicitCastExpr 0x7f79758 <col:8> 'atomic_uint':'_Atomic(unsigned int)' <LValueToRValue>
  `-DeclRefExpr 0x7f79718 <col:8> 'atomic_uint':'_Atomic(unsigned int)' lvalue Var 0x7f79530 'y' 'atomic_uint':'_Atomic(unsigned int)'

ERROR: CONVERSION ERROR
````

### PR DESCRIPTION
**Pull request by XLiZHI**
This PR addresses the issue of unsupported type conversions, I haven't added #2148 and #2149 to regression yet because they have too much thread interleaving.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
@XLiZHI : you can add the option `--context-bound 1`` if the regression tests generate too many interleavings.

**Review by intrigus-lgtm — COMMENTED** [review]
Does this really implement the correct semantics?

**Comment by intrigus-lgtm** [comment]
There are multiple atomic loads and stores in this example and I currently don't see how this is modeled in this PR:
https://godbolt.org/z/qGG9afPdf

**Review by mikhailramalho — COMMENTED** [review]
How do we represent atomic variables in esbmc? Are we creating the right type when doing non-atomic to atomic?

**Comment by XLiZHI** [comment]
> @XLiZHI : you can add the option `--context-bound 1`` if the regression tests generate too many interleavings.

One example that I think is tricky is using undet_int to create threads:
```
#define N __VERIFIER_nondet_int()
  while(p < _N) {
    pthread_create(&t, 0, f1, 0);
    pthread_create(&t, 0, f2, 0);
    p++;
  }
```
This would be infinite thread interleaving in ESBMC.

> Does this really implement the correct semantics?
> How do we represent atomic variables in esbmc? Are we creating the right type when doing non-atomic to atomic?

Combined with the standard library atomic manipulation functions (c11_atomic_*)

We already have these fake calls: https://github.com/esbmc/esbmc/blob/242bb9c7851412c0ce83b2cb6e0dd8eecdb3e06a/src/clang-c-frontend/clang_c_convert.cpp#L3249-L3259

We are not implementing the functionality of atomic types.

Of course, this PR only solves type conversions, and the standard library atomic manipulation functions need to be implemented further.

**Comment by lucasccordeiro** [comment]
@XLiZHI: How does your PR work for these benchmarks https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/tree/main/c/pthread-theta?ref_type=heads?

**Comment by XLiZHI** [comment]
SVCOMP:
This PR:
https://github.com/esbmc/esbmc/actions/runs/11935341114

**Comment by lucasccordeiro** [comment]
@XLiZHI: Can I ask you for the status of this PR?

**Comment by XLiZHI** [comment]
> @XLiZHI: Can I ask you for the status of this PR?

I think we should first support the semantics of atomic types and then proceed with this PR.

**Comment by lucasccordeiro** [comment]
Thanks, @XLiZHI.

Can I ask you to open an issue and close this PR?

**Pull request closed without merging**
