### PR TITLE
Enable the value set analysis during the inductive step only

### PR DESCRIPTION
**Pull request by lucasccordeiro**
We should enable the value set analysis for pointers and add the assumes to the program during the inductive step only.

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
I'm now running this PR on `[root@fm12 value-set-inductive-step]#`.

**Review by mikhailramalho — CHANGES_REQUESTED** [review]
Since we are improving the code, we should:

1. Add custom builtin call when applying k-induction transformations.
2. During symex, add the pointer invariants.
3. Remove the current code that adds the invariants every time we call get_value_set.

**Comment by lucasccordeiro** [comment]
Results of this PR using k-induction and the value set analysis during the inductive step only:
```
Statistics:          15201 Files
  correct:            7712
    correct true:     4905
    correct false:    2807
  incorrect:            58
    incorrect true:     25
    incorrect false:    33
  unknown:            7431
  Score:             11289 (max: 24562)
```

Results of the master branch using k-induction:

```
Statistics:          15201 Files
  correct:            7701
    correct true:     4899
    correct false:    2802
  incorrect:            58
    incorrect true:     25
    incorrect false:    33
  unknown:            7442
  Score:             11272 (max: 24562)
```

**Comment by lucasccordeiro** [comment]
I'm now running `[root@fm12 value-set-inductive-step-15m-15gb]`

**Comment by lucasccordeiro** [comment]
This PR improves our current results. I have created this issue https://github.com/esbmc/esbmc/issues/484 to improve the invariant generation process even further.

**Pull request merged**
