### PR TITLE
Intrinsic memset claim fix

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
This PR now guards the memset claims to error only when we are actually pointing to the invalid object. This should fix `c/uthash-2.0.2/uthash_SFH_test6-2.i`

### CODE REVIEW

**Review by fbrausse — APPROVED** [review]
I guess "A -> false" can be simplified to "not(A)", but it fits nicely with the comment explaining the condition. LGTM! Thanks, @rafaelsamenezes, this fixes a bunch of sv-comp's uthash benchmarks!

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @rafaelsamenezes.

**Comment by lucasccordeiro** [comment]
BTW, could you please add some regression tests, @rafaelsamenezes?

**Comment by rafaelsamenezes** [comment]
> BTW, could you please add some regression tests,

Done

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Many thanks, @rafaelsamenezes.

**Pull request merged**
