### PR TITLE
[goto] prefixed adjust

### PR DESCRIPTION
**Pull request by XLiZHI**
A fix for issue #1147

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
@XLiZHI: could you please add the respective regression test here?

**Comment by XLiZHI** [comment]
> @XLiZHI: could you please add the respective regression test here?

Yes, sure. May I ask which folder is appropriate?

**Comment by lucasccordeiro** [comment]
regression/esbmc-unix ;-)

**Comment by lucasccordeiro** [comment]
https://github.com/esbmc/esbmc/tree/master/regression/esbmc-unix

**Review by kunjsong01 — APPROVED** [review]

**Comment by kunjsong01** [comment]
LGTM

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR.

**Pull request merged**
