### PR TITLE
[clang-cpp] fix return type of CXXMemberCalls

### PR DESCRIPTION
**Pull request by intrigus-lgtm**
`member_call.getType()` does not take into account references.
Just as is done for [CallExpr](https://github.com/esbmc/esbmc/blob/80c4e3b48bbd7bdf7ceb7b58d2458e68ddc917f7/src/clang-c-frontend/clang_c_convert.cpp#L1781) and [CXXOperatorCall](https://github.com/esbmc/esbmc/blob/80c4e3b48bbd7bdf7ceb7b58d2458e68ddc917f7/src/clang-cpp-frontend/clang_cpp_convert.cpp#L650), we use `getCallReturnType` instead.

Before:
```
struct a * return_value$_e$1;
// 27 no location
FUNCTION_CALL:  return_value$_e$1=e(&ag)
// 28 file cpptest.pre.cpp line 10 column 3 function main
the_kind=&return_value$_e$1;
//-------^
// 29 file cpptest.pre.cpp line 11 column 30 function main
ASSERT the_kind->f == 4 // assertion 
```

after:
```
struct a * return_value$_e$1;
// 27 no location
FUNCTION_CALL:  return_value$_e$1=e(&ag)
// 28 file cpptest.pre.cpp line 10 column 3 function main
the_kind=return_value$_e$1;
//-------^
// 29 file cpptest.pre.cpp line 11 column 30 function main
ASSERT the_kind->f == 4 // assertion 
```

### CODE REVIEW

**Comment by intrigus-lgtm** [comment]
The vector9 test is fixed by this PR, I just have to change KNOWNBUG to CORE.
However I don't understand https://github.com/esbmc/esbmc/blob/master/regression/esbmc-cpp/vector/vector14/main.cpp and why it is verified successfully instead of failing as it should.

**Comment by intrigus-lgtm** [comment]
I also don't understand why builtin_3 fails:
https://github.com/esbmc/esbmc/actions/runs/10585899048/job/29333550545?pr=2003#step:6:16770
But only on `dyn. llvm-13 DebugOpt / Build ESBMC (ubuntu-latest)`

**Comment by fbrausse** [comment]
> I also don't understand why builtin_3 fails: https://github.com/esbmc/esbmc/actions/runs/10585899048/job/29333550545?pr=2003#step:6:16770 But only on `dyn. llvm-13 DebugOpt / Build ESBMC (ubuntu-latest)`

Race condition. It gives lots of
```
/tmp/esbmc_solidity_temp/temp_sol.c:1:7677: warning: null character ignored [-Wnull-character]
```

Most likely because the temp-path is hardcoded and not generated, here: https://github.com/esbmc/esbmc/blob/80c4e3b48bbd7bdf7ceb7b58d2458e68ddc917f7/src/solidity-frontend/solidity_language.cpp#L49-L50

**Comment by fbrausse** [comment]
> I don't understand https://github.com/esbmc/esbmc/blob/master/regression/esbmc-cpp/vector/vector14/main.cpp and why it is verified successfully instead of failing as it should.

`--symex-trace` shows that the return value of vector::front() now is actually used correctly in the assertion:
```diff
         DECL signed char * return_value$_front$19;
 
         FUNCTION_CALL:  return_value$_front$19=front(&c)
 
         RETURN: &this->buf[0]
 
         END_FUNCTION // front
 
-        ASSERT (signed int)return_value$_front$19 != 97 // assertion c.front() != 'a'
+        ASSERT (signed int)(*return_value$_front$19) != 97 // assertion c.front() != 'a'
 
-        IF !((signed int)return_value$_front$19 != 97) THEN GOTO 2
+        IF !((signed int)(*return_value$_front$19) != 97) THEN GOTO 2
```
Before, the pointer `return_value$_front$19` was cast to `int` and compared to `'a'`. I'd mark it a known bug.

**Comment by intrigus-lgtm** [comment]
> > I don't understand https://github.com/esbmc/esbmc/blob/master/regression/esbmc-cpp/vector/vector14/main.cpp and why it is verified successfully instead of failing as it should.
> 
> `--symex-trace` shows that the return value of vector::front() now is actually used correctly in the assertion:
> 
> ```diff
>          DECL signed char * return_value$_front$19;
>  
>          FUNCTION_CALL:  return_value$_front$19=front(&c)
>  
>          RETURN: &this->buf[0]
>  
>          END_FUNCTION // front
>  
> -        ASSERT (signed int)return_value$_front$19 != 97 // assertion c.front() != 'a'
> +        ASSERT (signed int)(*return_value$_front$19) != 97 // assertion c.front() != 'a'
>  
> -        IF !((signed int)return_value$_front$19 != 97) THEN GOTO 2
> +        IF !((signed int)(*return_value$_front$19) != 97) THEN GOTO 2
> ```
> 
> Before, the pointer `return_value$_front$19` was cast to `int` and compared to `'a'`. I'd mark it a known bug.

Will do.

**Review by XLiZHI — APPROVED** [review]

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @intrigus-lgtm.

**Pull request merged**
