### PR TITLE
[smt] avoid creating zero-width bitvectors

### LINKED ISSUE #719: Aborted with empty union and struct of array
Version: current master (`eff35eb1700838c5af8d619a70b6910ac84d4c0a`)

Command:
``` bash
esbmc main.c --compact-trace
```

Input program:
``` c
#include <assert.h>

typedef union {
  struct {};
} s1;

typedef struct {
  int x[2];
} s2;

s1 v1;
s2 v2;

int main() {
  for (int i = 0; i < 2; i++) {
    v2.x[i] = 0;
  }

  int x = 0;
  for (int i = 0; i < 2; i++) {
    x++;
  }
  assert(x == 0);

  return 0;
}
```

### PR DESCRIPTION
**Pull request by fbrausse**
This PR does two things:
1. Impose a minimum of 1 on the width of bitvectors in smt_conv, specifically `mk_int_bv_sort()`, since BVs of zero width are not supported by (most, if not all) SMT solvers
2. Handle zero-width structs/unions (i.e. empty or only containing zero-width members) when flattening to bitvectors.

Together, both points fix #719 where zero-width unions are used and (for the counter-example) empty structs are bitcasted.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Review by mikhailramalho — APPROVED** [review]
LGTM. It's a shame we can't simply ignore these declarations.

nitpick: I would just choose one style of checking zero and stick with, i.e, either `== 0` or `!width`.

**Comment by fbrausse** [comment]
> LGTM. It's a shame we can't simply ignore these declarations.

I agree. With the renewed C++ support this is only going to be more of an issue.

> nitpick: I would just choose one style of checking zero and stick with, i.e, either == 0 or !width.

Thanks, opted for `== 0`.

**Comment by lucasccordeiro** [comment]
@fbrausse: could you please rebase this branch with the master?

**Comment by fbrausse** [comment]
> @fbrausse: could you please rebase this branch with the master?

done.

**Pull request merged**
