### PR TITLE
[clang-cpp] Support for inheritance and polymorphism

### PR DESCRIPTION
**Pull request by kunjsong01**
Replaces https://github.com/esbmc/esbmc/pull/848. 

**Methodology:** 
We follow the old cpp frontend conversion flow to support inheritance and polymorphism. 
Added vtable and vptr conversions in clang-cpp-frontend. 

**Example:** 
```cpp
     3	class Vehicle
     4	{
     5	public:
     6	  Vehicle() {}
     7	  virtual int number_of_wheels() = 0;
     8	};
```

Symbols added for the above class: 
```
   1 c:@S@Vehicle@F@Vehicle#
   1 c:@S@Vehicle@F@Vehicle#this
   1 c:@S@Vehicle@F@number_of_wheels#
   1 c:@S@Vehicle@F@~Vehicle#
   1 c:@S@Vehicle@F@~Vehicle#this
   1 tag-Vehicle
   1 virtual_table::tag-Vehicle
   1 virtual_table::tag-Vehicle@tag-Vehicle
```

**Major Changes and Dev Notes:**
1. Since conversion of constructors rely on vtable and vptr, we have to use iterate over the declarators in a class in two loops:
   - First loop: we do everything but constructors and set up vtable and vptr in  in `clang_cpp_convertert::do_virtual_table`
   - Second loop: we do constructors
2. Symbol `virtual_table::tag-Vehicle` is added by `clang_c_convertert::get_virtual_method`.
3. Symbol `virtual_table::tag-Vehicle@tag-Vehicle` is added by `clang_cpp_convertert::do_virtual_table`. 

P.S. Revert commit 87f7b210dd5d060618166187df4ede3202abce9e before merging. This is the commit that contains debug lines

### CODE REVIEW

**Comment by mikhailramalho** [comment]
@kunjsong01 please remove the debug code before we can start the review please.

**Comment by kunjsong01** [comment]
### Vtable in GOTO functions:
Now we have the virtual table in `__ESBMC_main`: 
```python
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

__ESBMC_main (__ESBMC_main):
        // 24 file esbmc_intrinsics.h line 19
        __ESBMC_alloc=ARRAY_OF(0);
        // 25 file esbmc_intrinsics.h line 22
        __ESBMC_is_dynamic=ARRAY_OF(0);
        // 26 file esbmc_intrinsics.h line 25
        __ESBMC_alloc_size=ARRAY_OF(0);
        // 27 file esbmc_intrinsics.h line 34
        __ESBMC_rounding_mode=0;
        // 28 file main.cpp line 7
        virtual_table::Vehicle@Vehicle={ .number_of_wheels=0 };
        // 29 file pthread_lib.c line 52
        __ESBMC_num_threads_running=0;
```

### TODO: Set up vptr in ctor to point to the corresponding Vtable
```python
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Vehicle (c:@S@Vehicle@F@Vehicle#):
        // 20 file main.cpp line 6 function Vehicle
        END_FUNCTION // Vehicle
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
should be like: 
```python
Vehicle (Vehicle::Vehicle(this)):
        // 4 no location
        this->Vehicle@vtable_pointer=&virtual_table::Vehicle@Vehicle;
        // 5 no location
        END_FUNCTION
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Solution: 
Vptr is also a class member. Hence, Vptr initialization can be considered member initialization. 
We can add Vptr initialization in `clang_cpp_convertert::get_function_body` after adding the initialization code for class member initializers. Then adjust the node to match whatever side effect we want.

**Comment by kunjsong01** [comment]
> @kunjsong01 please remove the debug code before we can start the review please.

@mikhailramalho Sure, will do. 
All debug code are encapsulated in commit 87f7b210dd5d060618166187df4ede3202abce9e. 
I'll revert it before requesting the final reviewing. 

~~Still need to do vptr initialization in constructos to 100% match symbol table (see [comment above](https://github.com/esbmc/esbmc/pull/854#issuecomment-1277571860)).~~ (Done in commit https://github.com/esbmc/esbmc/commit/87f7b210dd5d060618166187df4ede3202abce9e)

**Comment by kunjsong01** [comment]
With commit 87f7b210dd5d060618166187df4ede3202abce9e, we now have vptr initialization

### Symbol level: 
```cpp
Symbol......: c:@S@Vehicle@F@Vehicle#
Module......: main
Base name...: Vehicle
Mode........: C++ (1)
Type........: void (class Vehicle *)
Value.......:
{
this->Vehicle@vtable_pointer = &virtual_table::Vehicle@Vehicle;

}
Flags.......: lvalue
Location....: file main.cpp line 6
```

### GOTO function level: 
```python
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Vehicle (c:@S@Vehicle@F@Vehicle#):
        // 20 no location
        this->Vehicle@vtable_pointer=&virtual_table::Vehicle@Vehicle;
        // 21 file main.cpp line 6 function Vehicle
        END_FUNCTION // Vehicle
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by kunjsong01** [comment]
### What has been done in commit e22c5ba2f8181192a856e9d0145e6fbf288afa76 ... commit b6c993bcc5f01e7074d8e017d0c71ba7a5637bff: 
We've got basic support for virtual method typechecking. 
The commits that so far have been included in this PR implement conversion flow mimicking `cpp_typecheckt::typecheck_compound_body` from [a class AST to ESBMC's IR](https://github.com/esbmc/esbmc/blob/master/src/cpp/cpp_typecheck_compound_type.cpp#L914 ): 
1. added vtable and vptr for virtual methods
2. controlled order of type checking for class methods, i.e. converting non-ctor/dtor methods before ctors/dtors. Becuase we need to refer to the vptr when converting the ctor body as in `this->Vehicle@vtable_pointer = &virtual_table::Vehicle@Vehicle;`. 
3. added `components` node in a class type, making it easier to copy them from base class to the derived class type something like:
```
struct
  * name: tag-Motorcycle
  * tag: Motorcycle
  * components: 
    0: component
        * type: pointer
          ...
        * name: tag-Motorcycle::@vtable_pointer
        * access: public
        * base_name: @vtable_pointer
        * pretty_name: Motorcycle@vtable_pointer
        * is_vtptr: 1
    1: code
        * type: ...
        * name: c:@S@Motorcycle@F@some_function#
        * access: public
        * #location: ...
    2: code
        * type: ...
        * name: ~Motorcycle()
        * access: public
        * #location: ...
    3: code
        * type: ...
        * name: Motorcycle()
        * access: public
        * #location: ...
    4: code
        * type: ...
        * name: Motorcycle(const Motorcycle&&)
        * access: public
        * #location: ...
```

The derived class symbol does not match, missing components from the base class. 

### Further TODOs to complete this PR: 
1. For derived class, still need to pull the base type in and tweak the access for each base components, e.g. "noaccess" for private members from base class. (refer to https://github.com/esbmc/esbmc/blob/master/src/cpp/cpp_typecheck_bases.cpp)
2. Multiple inheritances (refer to the recursive calls to [cpp_typecheckt::add_base_components](https://github.com/esbmc/esbmc/blob/a04de864b5f7efc5b5fc2e46d4158344e1c65553/src/cpp/cpp_typecheck_bases.cpp#L98))
5. Virtual inheritance (refer to [vbases set](https://github.com/esbmc/esbmc/blob/a04de864b5f7efc5b5fc2e46d4158344e1c65553/src/cpp/cpp_typecheck_bases.cpp#L103).)

Note for clang virtual inheritance: 
Use [`bases()`](https://clang.llvm.org/doxygen/classclang_1_1CXXRecordDecl.html#a3fb55cd089aa79eca55219393d3215f0) to get the base range and [`isVirtuallyDerivedFrom(const CXXRecord*)`](https://clang.llvm.org/doxygen/classclang_1_1CXXRecordDecl.html#ae62e04a26bd8da644d83483b571367ed) to check virtual inheritance.

**Comment by kunjsong01** [comment]
For Further TODOs 1, 2 and 3 listed in https://github.com/esbmc/esbmc/pull/854#issuecomment-1308634979, the following TCs should be used to drive the development: 

| Representative TCs  | Feature to test |
| --- | --- |
| single_inheritance<br />paper_inheritance_example | single inheritance |
| multiple_inheritance | multiple inheritance |
| multiple_inheritance_2 | multiple inheritance, diamond hierarchy with virtual bases |

**Comment by kunjsong01** [comment]
For multiple inheritance and virtual bases: 

### Problem:
Walk through the class inheritance hierarchy and copy the components from base class types into the derived class type. 
For virtual bases, just copy ONCE. 

### Evaluation of Current Design: 
In `get_struct_union_class_fields` and `get_struct_union_class_methods` respectively, we have two loops to pull the bases in. But they are NOT able to *recursively* walk through the class inheritance hierarchy tree with depth > 1.  

### Solution:
As per https://github.com/esbmc/esbmc/pull/854#issuecomment-1308634979, when we reach a (most) derived class, the bases' types are already populated. We need to traverse the inheritance hierarchy tree using DFS:
1. Look up base class symbol in the context. 
2. Copy the components from base class' type into the derived class' type

While traversing, update the two sets {{bases}, {vbases}}. 
For virtual bases, avoid copying twice.

**Comment by kunjsong01** [comment]
### Fixed regression failures in commit a1611e7ba938b9eadc1334ddf13562a5ad6f5ce4: 
```
The following tests FAILED:
	1694 - regression/esbmc-cpp/cpp/cpp_with_pthread_01 (Failed)
	1696 - regression/esbmc-cpp/cpp/cpp_with_pthread_02 (Failed)
	1697 - regression/esbmc-cpp/cpp/cpp_with_pthread_02-no-lib (Failed)
Errors while running CTest
```

**Root cause:** 
The above TCs failed the following assertion: 
```
@@ Done pulling bases in ...
@@ printing ------
CXXRecordDecl 0x55555c630330 </tmp/esbmc.2dc7-17de-c3ac/headers/pthread.h:32:1, col:8> col:8 struct timespec
@@ completeness: 0
@@ done printing ------
esbmc: /home/kunjian/ESBMC_Project/clang11/include/clang/AST/DeclCXX.h:434: clang::CXXRecordDecl::DefinitionData& clang::CXXRecordDecl::data() const: Assertion `DD && "queried property of class with no definition"' failed.
```

This assertion failed due to a CXXRecordDecl's data pointer being nullptr when typechecking `struct timespec`, because timespec's definition is incompelte in `/tmp/esbmc.2dc7-17de-c3ac/headers/pthread.h`: 
```cpp
 23 #include <stddef.h>
 24 #include <stdint.h>
 25
 26 #ifndef _MSVC
 27 #define NULL 0
 28 #endif
 29
 30 /* Forward declaration required because the type is used in pthread function
 31  * parameters below. */
 32 struct timespec;
```

**Solution:** 
commit fac82e5d63115e3caed3b26b82fbd556b93004e8: Skipped incomplete CXXRecordDecl when getting bases

**Comment by mikhailramalho** [comment]
Hey @kunjsong01 is this ready for review? 

If it isn't, I'll remove myself from the reviewer list until it's ready for review, so I don't get emails from this PR.

**Comment by kunjsong01** [comment]
> Hey @kunjsong01 is this ready for review?
> 
> If it isn't, I'll remove myself from the reviewer list until it's ready for review, so I don't get emails from this PR.

Hi @mikhailramalho, apologies for the spams. This PR is not ready for review yet. Apologies for the Please feel free to remove yourself from the reviewer list.

**Pull request closed without merging**
