### PR TITLE
Optional check for over-sized reading of struct fields

### PR DESCRIPTION
**Pull request by shmarovfedor**
This PR makes the over-sized read check for struct fields optional, and allows enabling of such checks via the `--struct-fields-check` flag. This solution is necessary because ESBMC produces a number of false positives where an over-sized read of a struct field does not lead to a safety violation (e.g., #486).

### CODE REVIEW

**Comment by mikhailramalho** [comment]
Is it legal to over-read a field? If so, I would recommend removing that check altogether.

**Comment by shmarovfedor** [comment]
I guess it should be legal as long as it is within the struct's bounds (otherwise `memcpy` would not be allowed for structs with bit-fields). But I think it's useful to have such option as over-sized reads can lead to gaining access to the struct's padding which can lead to unspecified behaviour.

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Review by mikhailramalho — APPROVED** [review]
I have a feeling that we are effectively killing this check, users don't usually care about changing the default parameters...

Anyway, maybe we can bring it back with the UB check that we discussed in the other issue.

**Comment by fbrausse** [comment]
> I have a feeling that we are effectively killing this check, [...]

Indeed. Maybe that's a good thing™?

I believe it boils down to 3 variants of this:
```c
#include <assert.h>
#include <stdint.h>

struct str { _Alignas(32) uint32_t a; };
_Static_assert(sizeof(struct str) >= 32, "clearly, 32 < 32...");

int main()
{
	struct str s, t;
	s.a = 42;
	*((uint64_t *)&s.a + 0);
}
```
1. as it is -> `dereference failure: Over-sized read of struct field` (ESBMC interprets the underlying object not be an array of >= 8 bytes)
2. remove `.a` in the address-of -> `dereference failure: Over-sized read of struct field` (ESBMC treats "pointer to `str`" as "pointer to unsigned" - dubious? maybe we should fix that)
3. change 0 to 1 -> `VERIFICATION SUCCESSFUL` ESBMC does not care despite the comment claiming otherwise: https://github.com/esbmc/esbmc/blob/420e8b08cab652f5cf1cfe33077d615b878a7c5d/src/pointer-analysis/dereference.cpp#L1207-L1209

In these cases the pointed-to objects are different. If ESBMC was to engage in interpreting the ANSI C standard literally, it would have to a) distinguish between all of them (only 4 bytes accessible in 1., all 32 in 2., none in 3.) and b) allow reading storage representation only via `char *` and not `uint64_t *`. However, it does not (yet: #580).

Therefore treating 1. == 2. == 3. would be intuitive, and it should not fail. In particular since a (real-world, e.g., glibc) memcpy of 16 bytes [does](https://sourceware.org/git/?p=glibc.git;a=blob;f=string/memcpy.c;h=9cf64530e7366675895a05c861689ac2831098c9;hb=HEAD#l51) (called word-copy there) 1. followed by 3. and replacing the dereference with `memcpy(&t, &s, 16);` is accepted just fine by ESBMC.

(Coincidentally, replacing it instead by `memcpy(&(uint64_t){0}, &s, 8);` leads to a crash, I'll open another issue about that).

**Review by fbrausse — APPROVED** [review]

**Pull request merged**
