### PR TITLE
Fix output of negative integer constants

### LINKED ISSUE #1366: --smtlib does not output negative integers correctly
When running on the following program

```
extern void abort(void);
extern void __assert_fail(const char *, const char *, unsigned int, const char *) __attribute__ ((__nothrow__ , __leaf__)) __attribute__ ((__noreturn__));
void reach_error() { __assert_fail("0", "vnew2.c", 3, "reach_error"); }
extern void abort(void);
void assume_abort_if_not(int cond) {
  if(!cond) {abort();}
}
void __VERIFIER_assert(int cond) {
  if (!(cond)) {
    ERROR: {reach_error();abort();}
  }
  return;
}
int SIZE = 20000001;
int __VERIFIER_nondet_int();
int main() {
   int n = 0;
   int j = 1;
   int k = __VERIFIER_nondet_int();
  __ESBMC_assume(k == j * -1);
  __VERIFIER_assert(k == (2 - 1) * j * -1);
}
```

with options 

`--smtlib --ir --output out`

The integers -1 are not represented correctedly in the SMTLIB output. They are represented as -1 instead of (- 1).

### PR DESCRIPTION
**Pull request by fbrausse**
Fixes #1366. In SMT-LIB v2 format negative integer literals do not exist, but those numbers have to be expressed as, for instance, `(- 1)`. This PR addresses this for the `--smtlib` output.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @fbrausse.

Can you please add a regression test here, if possible?

**Comment by ibnyusuf** [comment]
Looks good. Thanks!

**Review by ibnyusuf — APPROVED** [review]
Looks good. Thanks!

**Comment by fbrausse** [comment]
> Can you please add a regression test here, if possible?

Done. I've taken the example from the issue and check that an equality with `(- 1)` indeed is generated for it.

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @fbrausse.

**Pull request merged**
