### PR TITLE
Citation.cff

### PR DESCRIPTION
**Pull request by tCm3nc**
An effort to address #869 .

### CODE REVIEW

**Comment by tCm3nc** [comment]
Hopefully I've got the right ORCID links and the right people, please let me know otherwise.
Is the citation as expected?

**Comment by lucasccordeiro** [comment]
Hi guys,

Do you have any suggestions here to acknowledge ESBMC's developers?

Best,
Lucas

**Comment by rafaelsamenezes** [comment]
> Do you have any suggestions here to acknowledge ESBMC's developers?

@lucasccordeiro ESBMC developers are acknowledge through the CREDITS file. 

For the future though, I would suggest changing the reference. A 4 page paper is not enough at all to be considered the work to be cited. Maybe we should consider writing a more in-depth work (journal or book chapter) which could be published/updated on arxiv (is this a valid option?).

**Review by rafaelsamenezes — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
We have a book chapter that we were expecting to publish as part of the SV-COMP effort. I mentioned to @mikhailramalho that we should upload this book chapter to arxiv, given that the publication of the book chapter is taking quite a long time (more than two years).

**Review by kunjsong01 — APPROVED** [review]

**Review by mikhailramalho — APPROVED** [review]
My ORCID is correct

**Review by shmarovfedor — APPROVED** [review]

**Pull request merged**
