### PR TITLE
Restore LTL code

### PR DESCRIPTION
**Pull request by fbrausse**
This PR attempts to restore the LTL checking code removed in 1127828851ffe2b5b86618c005cfcef2e2f6b2cc .

### CODE REVIEW

**Comment by fbrausse** [comment]
I'm observing
```
src/goto-symex/execution_state.cpp:490: void execution_statet::preserve_last_paths(): Assertion `pp.size() == 0 && "Unmerged preserved paths in ex_state"' failed.
```
when running
```
src/esbmc/esbmc --ltl test.c test.ba-2.c --context-bound 2 --no-por
```
with these inputs: [ltl-test.tar.gz](https://github.com/esbmc/esbmc/files/15009888/ltl-test.tar.gz)
They are (slightly modified versions of those) generated from the LTL formula `G({pressed} -> F {charge > min})` for test.c (also contained in the above archive) looking like this:
```c
int pressed, charge, min;

int main()
{
	charge = nondet_int();
	min = nondet_int() % 1024;
	for (int i = 0; i < 5; i++) {
		pressed = nondet_int();
		if (pressed)
			charge = min + 1;
	}
}
```
Lucas pointed to problems involving multi-threading in `__ESBMC_main`, e.g. here: https://github.com/esbmc/esbmc/blob/b3ab4e0e53888bef07f2ee96e3767d00567805d8/src/goto-symex/builtin_functions.cpp#L835-L837

**Comment by fbrausse** [comment]
Small example using `__ESBMC_switch_to_monitor` exhibiting the same assertion violation. Seems to me that this function is broken.
```c
#include <pthread.h>

void __ESBMC_register_monitor(pthread_t);
void __ESBMC_switch_to_monitor(void);

void *monitor_func(void *data)
{
	return data;
}

int main()
{
	pthread_t t;
        pthread_create(&t, NULL, monitor_func, NULL);
        __ESBMC_register_monitor(t);
	__ESBMC_switch_to_monitor();
//	__ESBMC_kill_monitor();
}
```

**Comment by fbrausse** [comment]
Without switch_to_monitor() it's running into a seemingly infinite recursion:
https://github.com/esbmc/esbmc/blob/a8cad4fc82ecf56eb59a073b34f198847bdd5774/src/esbmc/bmc.cpp#L416 https://github.com/esbmc/esbmc/blob/a8cad4fc82ecf56eb59a073b34f198847bdd5774/src/esbmc/bmc.cpp#L673 https://github.com/esbmc/esbmc/blob/a8cad4fc82ecf56eb59a073b34f198847bdd5774/src/esbmc/bmc.cpp#L777 May need to do something similar to the multi-property check instead.

**Comment by lucasccordeiro** [comment]
@fbrausse: Given our project review today, is this PR ready for review? As usual, we can work on incremental ways to add this LTL support back to ESBMC.

**Comment by fbrausse** [comment]
> @fbrausse: Given our project review today, is this PR ready for review? As usual, we can work on incremental ways to add this LTL support back to ESBMC.

Hi Lucas. I believe it is ready, yes. Of course, more regression tests would be always be helpful, but functionality-wise it's done. I can try to come up with some for the `U` and `V` operators. Also there is commented code adding a __ESBMC_switch_to_monitor() intrinsic, but as that's not working, yet, I didn't want to remove it in order to have a reference how it is supposed to work.

**Review by mikhailramalho — APPROVED** [review]
The code looks good, but I can't comment on the functionality as I never spent time working on it.

If no regressions were introduced in the sv-comp benchmarks, LGTM!

**Comment by lucasccordeiro** [comment]
Thanks, @fbrausse. Could you please run this PR over the SV-COMP benchmarks?

**Review by lucasccordeiro — APPROVED** [review]

**Comment by fbrausse** [comment]
> I can't comment on the functionality

OK, I understand. I shall add some documentation, maybe in the Wiki, soon. :)

**Comment by fbrausse** [comment]
Many thanks for re-running the benchmarks, @rafaelsamenezes.
Master:
```
Statistics:          23805 Files
  correct:           15336
    correct true:     8701
    correct false:    6635
  incorrect:            50
    incorrect true:     18
    incorrect false:    32
  unknown:            8419
  Score:             22949 (max: 38482)

https://github.com/esbmc/esbmc/actions/runs/8849874090
```
This PR:
```
Statistics:          23805 Files
  correct:           15338
    correct true:     8702
    correct false:    6636
  incorrect:            50
    incorrect true:     18
    incorrect false:    32
  unknown:            8417
  Score:             22952 (max: 38482)

https://github.com/esbmc/esbmc/actions/runs/8852153102
```

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @fbrausse.

**Pull request merged**
