### PR TITLE
Changing message output interface issue part 1

### PR DESCRIPTION
**Pull request by Mohannad-Aldughaim**
Hello everyone,

I have made some changes to the following:
Cmake file: added `fmt` library to the build and linked it
ui_message.cpp : used `fmt::printf` and `fprintf` instead of `cout` and `cerr`
bmc_parseoptions.cpp : replaced all `cout` and `cerr` usages with `status()` and `error()`

This pull request is a sample to make sure I am doing things the right way. Please let me know if you have any comments or if i should continue this way. 

I am facing some issues though:
1- in some places the message handler needs to be initialised or to become static to use it.  
2- in ui_message.cpp, there is an `xml` object that I am not sure if it should be printed using `fmt`.
3- There are some functions that take `std::cout` as a parameter. I am not sure how to approach them yet but if you have any insight about them it would help. they are: 
```
c_preprocess(filename, std::cout, false, *get_message_handler())
goto_functions.output(ns, std::cout);
language.show_parse(std::cout);
```

Regards,
-Mohannad

Signed-off-by: Mohannad-Aldughaim <m.aldughaim@gmail.com>

### CODE REVIEW

**Review by mikhailramalho — CHANGES_REQUESTED** [review]
Alright, we are on the right path here:
1. Can you use the header-only version of fmt so we don't have to link it against esbmc? 
2. Fix CI errors
3. Remove commented code and update comment in the format `// TODO: how xml should be handled?`

**Comment by Mohannad-Aldughaim** [comment]
Thank you @mikhailramalho 
I will make the changes. 
So for header-only, should i include the files in esbmc or assume they are installed on the machine?
also by CI errors you mean Travis CI?

**Comment by mikhailramalho** [comment]
> Thank you @mikhailramalho
> I will make the changes.
> So for header-only, should i include the files in esbmc or assume they are installed on the machine?

You are still going to include them, you just won't link esbmc against fmt::fmt.

> also by CI errors you mean Travis CI?

Yes.

**Comment by rafaelsamenezes** [comment]
> bmc_parseoptions.cpp : replaced all `cout` and `cerr` usages with `status()` and `error()`

Where are those functions being defined? If possible create an abstract class for them with a specialization that uses `fmt::print` this will be very helpful in improving ESBMC outputs. BTW, it would be great if the class contains methods such as debug, verbose, warning, and trace.

> 3- There are some functions that take std::cout as a parameter. I am not sure how to approach them yet but if you have any insight about them it would help. they are:

Since you are using the functions `status` and `error` I think that it would be best to remove the parameter and just reimplement everywhere in the function that uses the `ostream`

**Comment by Mohannad-Aldughaim** [comment]
Hi everyone,

So i have been trying to include the fmt library in esbmc but i ran into some issues and it works with the following options:
1- Have fmt installed on the machine:  
main advantage is : it can use header only version and no modification to cmake files.
disadvantage: must download fmt and make install it as a prerequisite to build esbmc 

2- Have fmt source added to esbmc : this way it needs to linked using cmake files.
advantage: no new prerequisite to esbmc
disadvantage: needs to be linked against esbmc

I been trying to add fmt files without linking it against esbmc to have the best of both options but did not find a solution yet.
So may i ask you, If you have anything in mind that could help with this issue i would appreciate it.

**Comment by mikhailramalho** [comment]
Option 1 is fine: like any other esbmc dependency (e.g. Boost) , the user
must install it in order to compile esbmc.

Also, fmt is available via apt, I think the package is called libfmt-dev.

**Comment by rafaelsamenezes** [comment]
What is the current status of this PR?

**Comment by lucasccordeiro** [comment]
@Mohannad-Aldughaim: I will close this PR since it is entirely obsolete. @rafaelsamenezes has volunteered to change the message output interface (cf. https://github.com/esbmc/esbmc/pull/456).

**Pull request closed without merging**
