### PR TITLE
[python-frontend] fixed int type-casting

### PR DESCRIPTION
**Pull request by haru-02**
@brcfarias here is a new PR that includes the changes suggested in #1987 I had to close the old PR due to merge conflicts. Thank you for the review.

### CODE REVIEW

**Review by brcfarias — APPROVED** [review]

**Comment by brcfarias** [comment]
Could you please fix the indentation in `python_converter.cpp` using clang-format-11?

**Comment by lucasccordeiro** [comment]
@haru-02: does this implementation work for arithmetic operations? For example int(1.222)*a?

**Comment by brcfarias** [comment]
> @haru-02: does this implementation work for arithmetic operations? For example int(1.222)*a?

After applying this PR locally:

image

**Comment by lucasccordeiro** [comment]
Excellent!

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
@haru-02: could you please fix the code style issue?

**Comment by haru-02** [comment]
@lucasccordeiro yes, i will change the code indentation and post a fix soon.

**Comment by haru-02** [comment]
Thank you for the review once again. @brcfarias @lucasccordeiro

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @haru-02.

**Pull request merged**
