### PR TITLE
Fix undefined function

### PR DESCRIPTION
**Pull request by mikhailramalho**
Fix bug introduced by PR #285, where a function was deleted because it was only used inside an assert, and because our regressions are built in RelWithDebInfo mode, the issue was not triggered during compilation.

So add back the function and enable Debug mode during regression tests.

### CODE REVIEW

**Comment by rafaelsamenezes** [comment]
> Fix bug introduced by PR #285, where a function was deleted because it was only used inside an assert, and because our regressions are built in RelWithDebInfo mode, the issue was not triggered during compilation.

I didn't understand. Our tests are organized as:

- Unit tests: With the libFuzzer and Boost.Test targets which are compiled
- System tests: With the regression targets which aren't compiled.

> So add back the function and enable Debug mode during regression tests.

Travis already runs the tests in Debug when generating the Coverage and we shouldn't make system tests dependent of a build type. If this is an essential behavior, I suggest moving those tests into another suite and adding them by checking the build type in CMake.

**Comment by mikhailramalho** [comment]
> 
> Travis already runs the tests in Debug when generating the Coverage and we shouldn't make system tests dependent of a build type. If this is an essential behavior, I suggest moving those tests into another suite and adding them by checking the build type in CMake.

Are you sure that Travis is building ESBMC in Debug mode? It shouldn't be even remotely possible after commit 087534d088f.

As you can see in this PR, the function `array_indexes_are_same` is being used inside two assertions in the `array_conv.cpp` file.

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Comment by rafaelsamenezes** [comment]
> Are you sure that Travis is building ESBMC in Debug mode? It shouldn't be even remotely possible after commit [087534d](https://github.com/esbmc/esbmc/commit/087534d088f0ff39cdda35ec02df493f4e6d004d).

You are correct. I didn't know that our default build type was RelWithDebInfo. Still, the debug flag should be added [here](https://github.com/esbmc/esbmc/blob/master/.travis.sh#L107)

**Pull request merged**
