### PR TITLE
Print alive messages during Decision Procedure

### PR DESCRIPTION
**Pull request by ChrisCheng816**
Print “alive” messages during the decision procedure to address https://github.com/esbmc/esbmc/issues/706.

### CODE REVIEW

**Review by mikhailramalho — APPROVED** [review]
It looks fine I guess, just make sure to explain to the user of this feature that esbmc is printing that, not the solver.

If the solver is stuck or deadlocked, the message we print doesn't matter.

**Review by rafaelsamenezes — APPROVED** [review]

**Comment by rafaelsamenezes** [comment]
Apparently Ubuntu 22.04 is complaining

```
home/runner/work/esbmc/esbmc/src/esbmc/bmc.h:50:29: error: field ‘keep_alive_running’ has incomplete type ‘std::atomic<bool>’
   50 |   mutable std::atomic<bool> keep_alive_running;
      |                             ^~~~~~~~~~~~~~~~~~
```

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @Chriszai.

Can I also ask you to update our user documentation at https://ssvlab.github.io/esbmc/documentation.html?

**Comment by ChrisCheng816** [comment]
> Thanks for submitting this PR, @Chriszai.
> 
> Can I also ask you to update our user documentation at https://ssvlab.github.io/esbmc/documentation.html?

Oh, yes, sure.

**Pull request merged**
