### PR TITLE
Revert "[C++ verification] adjust lambda operator"

### PR DESCRIPTION
**Pull request by intrigus-lgtm**
Reverts esbmc/esbmc#2165

Reason: The code doesn't actually work and could be simplified.
Rather than trying to improve the (now) existing code, it would be best to state afresh IMHO.

I'm creating a new PR that adds the reverted TCs and new ones.

For example, this TC is broken (which it was already before your new PR, **but the approach to fix that would also fix the problems that your PR fixed in a cleaner way**):
```
#include <cassert>
 
int main()
{
    int aaa = 22;
    int result = [aaa, bbb = 256]() { return aaa + bbb; }();
    assert(result == 2762);
    return 0;
}
```

The pretty well hidden method you were probably looking for is [getCaptureFields](https://clang.llvm.org/doxygen/classclang_1_1CXXRecordDecl.html#a5f9bae915113a518675d1f2445bed2f8) and can be used like so:
```
llvm::DenseMap<const ValueDecl*, FieldDecl*> captures{};
FieldDecl* thisCapture{};
cxxRecordDecl.getCaptureFields(captures, thisCapture);
```

It gives a mapping from a capture to the associated field in the closure.

### CODE REVIEW

**Comment by XLiZHI** [comment]
Good. This looks like a useful API, it's hidden so well that I didn't find it, I'll take a look at the method.(This is why I added the discussion tag to my last PR)

As for the previous code, I'll remove them in the new PR, no need to revert it.

**Comment by intrigus-lgtm** [comment]
> Good. This looks like a useful API, it's hidden so well that I didn't find it, I'll take a look at the method.(This is why I added the discussion tag to my last PR)

Well, I did plan to review your PR, but I'm in the final phase of my Master's thesis right now and ~1 day is currently not enough time to properly review a PR. So I would have preferred a bit more time before a PR is merged if I'm requested for review.
> 
> As for the previous code, I'll remove them in the new PR, no need to revert it.

I'd _really_ prefer to start afresh, you can of course copy paste stuff, but it makes it easier to review for me from the previous state.

As for why the [existing tests](https://github.com/esbmc/esbmc/blob/master/regression/esbmc-cpp11/lambda/lambda_01/main.cpp) "work":

```
operator() (c:test2.cpp@102@F@main#@Sa@F@operator()#1):
        // 38 file /tmp/test2.cpp line 10 column 9 function operator()
        ASSERT x == 42 // assertion x == 42
        // 39 file /tmp/test2.cpp line 11 column 9 function operator()
        ASSERT y == 1 // assertion y == 1
        // 40 file /tmp/test2.cpp line 12 column 5 function operator()
        END_FUNCTION // operator()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

this is the code generated for
```
#include <cassert>

int main()
{
    int x = 42; // ## 1
    int y = 1;

    auto lambda_with_capture_1 = [=]()
    {
        assert(x == 42); // ## 2
        assert(y == 1);
    };
```

The reason it "works" is that the `x` inside the lambda (`#1`) is the **same* `x` as the one outside (`#1`).
Due to the way esbmc works, this `x` is still visible inside the lambda, while we should use `__x` inside the lambda instead of `x`.
(`class __anon_class_at_/tmp/test2_cpp_main_8_34 lambda_with_capture_1={ .__x=x, .__y=y };`)

**Comment by XLiZHI** [comment]
> the reason it "works" is that the x inside the lambda (#1) is the *same x as the one outside (#1).
> Due to the way esbmc works, this x is still visible inside the lambda, while we should use __x inside the lambda instead of x.
> (class __anon_class_at_/tmp/test2_cpp_main_8_34 lambda_with_capture_1={ .__x=x, .__y=y };)

Indeed, when I was exploring this method, I realized the reason and I think my method is not robust and would like to discuss it further.

I agree with revert if you insist. Do you want to take over the job or should I do it?

**Comment by intrigus-lgtm** [comment]
> > the reason it "works" is that the x inside the lambda (#1) is the *same x as the one outside (#1).
> > Due to the way esbmc works, this x is still visible inside the lambda, while we should use __x inside the lambda instead of x.
> > (class __anon_class_at_/tmp/test2_cpp_main_8_34 lambda_with_capture_1={ .__x=x, .__y=y };)
> 
> Indeed, when I was exploring this method, I realized the reason and I think my method is not robust and would like to discuss it further.
> 
> I agree with revert if you insist. Do you want to take over the job or should I do it?

Revert would still be best I think.
Yeah, I can take over this, if that's fine with you.

**Review by XLiZHI — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
@intrigus-lgtm: Can I ask you to submit a PR that properly fixes this lamba operator? You can remove @XLiZHI's solution from your upcoming PR.

**Comment by intrigus-lgtm** [comment]
Superseded by https://github.com/esbmc/esbmc/pull/2171
Sorry for the noise.

**Pull request closed without merging**
