### PR TITLE
Automatic weekly release

### LINKED ISSUE #1191: Add automated nightly releases
We should do something similar to [orbit](https://github.com/google/orbit/blob/main/.github/workflows/release.yml) and make automated weekly releases of ESBMC.

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
This PR:

1. Converts build.yml into pull_request.yml.
2. Adds a new build.yml which is now a reusable workflow to build ESBMC.
3. Sets a cron job to do a weekly pre-release of ESBMC.

Closes #1191

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Review by fbrausse — COMMENTED** [review]
There are new free-form input strings for `operating-system` and `build-flags`. Could you give a list of known-working values for those so we have a kind-of reference? Maybe as a comment in the .yml? *Edit:* or as a description of the field.

**Review by fbrausse — APPROVED** [review]
This looks very nice! If you continue simplifying it, soon I will understand our github actions code ;)

One question: Why do you pass "-e Off" (i.e. no -Werror) for release builds? Shouldn't release builds be Werror-clean? I'm not a big fan of -Werror myself, but clearly there is demand for it, #1130.

**Comment by fbrausse** [comment]
OK, I just read your comment in #1130. Maybe mark it as TODO?

**Comment by rafaelsamenezes** [comment]
> One question: Why do you pass "-e Off" (i.e. no -Werror) for release builds? Shouldn't release builds be Werror-clean? I'm not a big fan of -Werror myself, but clearly there is demand for it, https://github.com/esbmc/esbmc/issues/1130.

Hm, IMO the release should never be prevented (as long as it can build). The commit checks (push/pull_request) should be the ones to verify *all* build types (which is currently on hold because of #1130).

**Comment by fbrausse** [comment]
> Hm, IMO the release should never be prevented (as long as it can build).

No build should ever be prevented as long as it can build. That's why I don't like -Werror. For nightly/weekly releases I don't mind, but for official releases we should better make sure that we understand all warnings.

**Comment by fbrausse** [comment]
Let's table this discussion here, I've already approved this PR and I am very happy that you're cleaning up the CI actions!

**Comment by lucasccordeiro** [comment]
This is really good, @rafaelsamenezes! Thanks for submitting this PR!

**Pull request merged**
