### PR TITLE
Pos svcomp fixes

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
Reopening PR

### CODE REVIEW

**Comment by rafaelsamenezes** [comment]
Started benchexec with 500s timeout. After finished I will put the results here.

**Comment by rafaelsamenezes** [comment]
Results from Benchexec

[merge-results.table.html.zip](https://github.com/esbmc/esbmc/files/4050024/merge-results.table.html.zip)

**Comment by mikhailramalho** [comment]
Any regression compared to master?

**Comment by rafaelsamenezes** [comment]
> Any regression compared to master?

It didn't add any incorrect results.

- Fixed 1 incorrect true Concurrency
- Fixed 6 incorrect false in AWS
- Fixed 1 incorrect true in Termination-Other

**Comment by mikhailramalho** [comment]
Excellent, let's merge it then.

**Pull request merged**
