### PR TITLE
[Solidity] Support Multiple Contract Verification

### PR DESCRIPTION
**Pull request by ChenfengWei0**
Previously we could only verify one contract at a time, by specifying the target contract name by `--contract`.  This PR adds support for multiple contract verification so that the user only needs to input the file with no further options set.

e.g.
```solidity
contract Base {
    uint8 data = 1;

    constructor(uint8 x) {
        assert(data + 2 == x);
    }
}

contract Derive {
    function test() public {
        assert(1 == 0);
    }
}
```
- ` esbmc --sol example.sol example.solast --incremental-bmc --multi-property`

```sh
[Counterexample]


State 1 file example.sol line 8 function Base thread 0
----------------------------------------------------
Violated property:
  file example.sol line 8 function Base
  assertion
  (signed int)data + 2 == (signed int)x

[Counterexample]


State 1 file example.sol line 17 function test thread 0
----------------------------------------------------
Violated property:
  file example.sol line 17 function test
  assertion
  1 == 0


VERIFICATION FAILED
```

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
Nice. LGTM.

BTW, is the solidity regression suite enabled in our CI?

**Comment by ChenfengWei0** [comment]
> Nice. LGTM.
> 
> BTW, is the solidity regression suite enabled in our CI?

I believe so.

```sh
          Start 1151: regression/esbmc-solidity/mul_cnt_ver_1
1148/4016 Test #1151: regression/esbmc-solidity/mul_cnt_ver_1 ..............................................   Passed    0.26 sec
          Start 1152: regression/esbmc-solidity/mul_cnt_ver_2
1149/4016 Test #1152: regression/esbmc-solidity/mul_cnt_ver_2 ..............................................   Passed    0.27 sec
```

**Comment by lucasccordeiro** [comment]
Thank you.

**Review by fbrausse — COMMENTED** [review]
The code changes look fine to me, but I wonder why this PR adds `--k-induction` to 7 of the Solidity test cases. Is it necessary due to the code changes?

**Comment by ChenfengWei0** [comment]
> The code changes look fine to me, but I wonder why this PR adds `--k-induction` to 7 of the Solidity test cases. Is it necessary due to the code changes?

Yes. During my test, these regression tests will keep unwinding unstoppable without k-induction. This might be due to the bug fix for the constructor in this PR.  Previously, we forgot to handle the parameters in the constructor.

**Comment by fbrausse** [comment]
> During my test, these regression tests will keep unwinding unstoppable without k-induction. This might be due to the bug fix for the constructor in this PR. Previously, we forgot to handle the parameters in the constructor.

Which function is being unwound there?

**Comment by ChenfengWei0** [comment]
> > During my test, these regression tests will keep unwinding unstoppable without k-induction. This might be due to the bug fix for the constructor in this PR. Previously, we forgot to handle the parameters in the constructor.
> 
> Which function is being unwound there?

e.g. `constructor_3`
```sol
pragma solidity >=0.4.0;

contract Base {
    uint8 data = 1;

    constructor(uint8 x) {
        assert(data + 2 == x);
    }
}

contract Derive {
    constructor() {
        Base x = new Base(2);
    }
}
```
- `./esbmc --sol contract.sol contract.solast --function Derive --contract Derive`
```sh
ESBMC version 7.4.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing example.solast
Converting
Done conversion of intrinsics...
Generating GOTO Program
GOTO program creation time: 0.424s
GOTO program processing time: 0.000s
Starting Bounded Model Checking
Unwinding loop 2 iteration 1
Unwinding loop 2 iteration 2
Unwinding loop 2 iteration 3
Unwinding loop 2 iteration 4
Unwinding loop 2 iteration 5
Unwinding loop 2 iteration 6
Unwinding loop 2 iteration 7
Unwinding loop 2 iteration 8
Unwinding loop 2 iteration 9
Unwinding loop 2 iteration 10
Unwinding loop 2 iteration 11
Unwinding loop 2 iteration 12
Unwinding loop 2 iteration 13
Unwinding loop 2 iteration 14
Unwinding loop 2 iteration 15
...
```

The target function is the `Derive`, which is the constructor of the contract `Derive` and whose name is omitted.

With `k-induction`
- `./esbmc --sol contract.sol contract.solast --function Derive --contract Derive --k-induction`
```sh
[Counterexample]


State 1 file contract.sol line 8 function Base thread 0
----------------------------------------------------
Violated property:
  file contract.sol line 8 function Base
  assertion
  (signed int)data + 2 == (signed int)x


VERIFICATION FAILED

Bug found (k = 1)
```

**Comment by fbrausse** [comment]
So for contract_3 the GOTO functions change from
```
Derive (sol:@C@Derive@F@Derive#):
        // 24 no location
        Base x;
        // 25 
        FUNCTION_CALL:  Base(&x, 2)
        // 26 file contract.sol line 17 function Derive
        dead x;
        // 27 file contract.sol line 17 function Derive
        END_FUNCTION // Derive
```
being called by __ESBMC_main() to
```
Derive (sol:@C@Derive@F@Derive#):
        // 24 no location
        Base x;
        // 25 
        FUNCTION_CALL:  Base(&x, 2)
        // 26 file contract.sol line 17 function Derive
        dead x;
        // 27 file contract.sol line 17 function Derive
        END_FUNCTION // Derive
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

sol_main_Derive (sol:@C@Derive@F@sol_main_Derive):
        // 28 no location
        FUNCTION_CALL:  Derive()
        // 29 no location
     1: _Bool return_value$_nondet_bool$1;
        // 30 
        return_value$_nondet_bool$1=NONDET(_Bool);
        // 31 no location
        IF !return_value$_nondet_bool$1 THEN GOTO 2
        // 32 no location
        GOTO 1
        // 33 no location
     2: dead return_value$_nondet_bool$1;
        // 34 no location
        END_FUNCTION
```
where `sol_main_Derive` now has this loop checking a nondet boolean. What's the purpose of this loop?

**Comment by ChenfengWei0** [comment]
> So for contract_3 the GOTO functions change from
> 
> ```
> Derive (sol:@C@Derive@F@Derive#):
>         // 24 no location
>         Base x;
>         // 25 
>         FUNCTION_CALL:  Base(&x, 2)
>         // 26 file contract.sol line 17 function Derive
>         dead x;
>         // 27 file contract.sol line 17 function Derive
>         END_FUNCTION // Derive
> ```
> 
> being called by __ESBMC_main() to
> 
> ```
> Derive (sol:@C@Derive@F@Derive#):
>         // 24 no location
>         Base x;
>         // 25 
>         FUNCTION_CALL:  Base(&x, 2)
>         // 26 file contract.sol line 17 function Derive
>         dead x;
>         // 27 file contract.sol line 17 function Derive
>         END_FUNCTION // Derive
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> sol_main_Derive (sol:@C@Derive@F@sol_main_Derive):
>         // 28 no location
>         FUNCTION_CALL:  Derive()
>         // 29 no location
>      1: _Bool return_value$_nondet_bool$1;
>         // 30 
>         return_value$_nondet_bool$1=NONDET(_Bool);
>         // 31 no location
>         IF !return_value$_nondet_bool$1 THEN GOTO 2
>         // 32 no location
>         GOTO 1
>         // 33 no location
>      2: dead return_value$_nondet_bool$1;
>         // 34 no location
>         END_FUNCTION
> ```
> 
> where `sol_main_Derive` now has this loop checking a nondet boolean. What's the purpose of this loop?

The nondet bool is to simulate arbitrary function calls in smart contract transactions. This `sol_main_Derive` is manually constructed in the frontend and serves as the entry function for the state transition system. 

However, when using `--function` option, the construction of this entry function is unexpected. In this case, the entry function should be `Derieve()` instead. I have just submitted a new commit to fix this issue. The newly added `--k-induciton`s are removed.

**Review by fbrausse — APPROVED** [review]
Great, many thanks for addressing this concern as well. LGTM.

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @ChenfengWei0.

@fbrausse: Thanks for spotting this issue in this PR.

**Pull request merged**
