### PR TITLE
setjmp/longjmp workaround

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
This makes that esbmc fails if reaching either `setjmp` and `longjmp`.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
Nice :-)

**Comment by rafaelsamenezes** [comment]
Results (30s):

```
Statistics:             66 Files
  correct:              29
    correct true:       15
    correct false:      14
  incorrect:             6
    incorrect true:      2
    incorrect false:     4
  unknown:              31
  Score:               -84 (max: 103)
```

Some of the benchmarks are still giving results. ~~@fbrausse shall we replace the implementation of the intrinsic with a crash?~~

Apparently the preprocessed files generate `_setjmp` due to macro expansion

**Comment by fbrausse** [comment]
> shall we replace the implementation of the intrinsic with a crash?

should be fine to do that, but let's run the benchmarks via CI again to be sure.

**Comment by rafaelsamenezes** [comment]
New results (30s):

```
Statistics:             66 Files
  correct:              19
    correct true:       15
    correct false:       4
  incorrect:             2
    incorrect true:      2
    incorrect false:     0
  unknown:              45
  Score:               -30 (max: 103)
```

All unknown are the jmp instructions. The 2 incorrect are from memory-model.

**Review by fbrausse — APPROVED** [review]
Nice, thanks!

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @rafaelsamenezes.

**Pull request merged**
