### PR TITLE
[C verification] add thread-local storage type check (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by XLiZHI**
We don't support thread-local storage, we disable it to get a better score on SV-COMP.

### CODE REVIEW

**Comment by XLiZHI** [comment]
This PR:
```
Statistics:          30300 Files
  correct:           16322
    correct true:    10950
    correct false:    5372
  incorrect:            23
    incorrect true:     18
    incorrect false:     5
  unknown:           13955
  Score:             26616 (max: 51772)

https://github.com/esbmc/esbmc/actions/runs/11955897572
```
Master:
```
Statistics:          30300 Files
  correct:           16443
    correct true:    11002
    correct false:    5441
  incorrect:            26
    incorrect true:     18
    incorrect false:     8
  unknown:           13831
  Score:             26741 (max: 51772)

GitHub actions: https://github.com/esbmc/esbmc/actions/runs/11850816430
```

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
@XLiZHI: There is a substantial reduction in the number of correct results. Is it because of the thread-local storage?

**Review by rafaelsamenezes — APPROVED** [review]

**Comment by XLiZHI** [comment]
I think we'd rather not merge it, this PR reduces the number of corrrects by a lot.  I'll re-evaluate it.

**Comment by lucasccordeiro** [comment]
> I think we'd rather not merge it, this PR reduces the number of corrrects by a lot. I'll re-evaluate it.

Yes, please do check.

**Pull request closed without merging**
