### PR TITLE
Fix overflow- encoding

### LINKED ISSUE #1559: Wrong results when checking sub unsigned underflow
esbmc reports a wrong bug when verifying this program with `--unsigned-overflow-check`  and any solver other than boolector:
```
int main()
{
  unsigned int x = 0;
  unsigned int y = 2;
  unsigned int z = y - x;
}
```

### PR DESCRIPTION
**Pull request by mikhailramalho**
The overflow checks for a - b is now (a - b) <= a

Fixed #1559

### CODE REVIEW

**Comment by mikhailramalho** [comment]
Also, `overflow_25_unsigned/main.c` already checks for a failure results, so no need to add another test case for that.

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @mikhailramalho.

Shall we run it over the SV-COMP benchmarks?

**Comment by mikhailramalho** [comment]
I don't think it's necessary, there were no wrong results on the overflow
category when I last run the rework-built-in.

I've found this issue by accident when writing one of the regressions

**Comment by lucasccordeiro** [comment]
Thanks, @mikhailramalho.

**Comment by lucasccordeiro** [comment]
@mikhailramalho: Can I ask you whether you have run this PR over the SV-COMP benchmarks?

**Pull request merged**
