### PR TITLE
Fixes involving casts

### PR DESCRIPTION
**Pull request by lucasccordeiro**
Signed-off-by: Mikhail R. Gadelha <mikhail.ramalho@gmail.com>

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
This PR fails on the test case: `regression/llvm/pointers`. The error message is: `Unexpected index type in computer_pointer_offset`.

**Comment by lucasccordeiro** [comment]
In particular, this patch does not like this code fragment:

```
int main() {
  int d[5][5];
 (*(&d[0] + 1 + 0))[0]=1;
    *(d+1)[2] = 1;
    *(d+2)[2] = *(d+1)[2];
  return 0;
}
```

```
$ esbmc test.c 
ESBMC version 6.4.0 64-bit x86_64 macos
file test.c: Parsing
Converting
Generating GOTO Program
GOTO program creation time: 0.369s
GOTO program processing time: 0.000s
Starting Bounded Model Checking
Unexpected index type in computer_pointer_offset
Abort trap: 6
```

**Comment by lucasccordeiro** [comment]
@mikhailramalho: We have some tests cases failing due to this assertion:

```
../src/pointer-analysis/value_set.cpp:518: void value_sett::get_value_set_rec(const expr2tc&, value_sett::object_mapt&, const string&, const type2tc&) const: Assertion `!(is_pointer_type(op0) && is_pointer_type(op1)) && "Cannot have pointer arithmetic with two pointers as operands"' failed.
```

**Comment by mikhailramalho** [comment]
I changed this PR a bit: it turns out we don't actually need the typecheck_arithmetic yet.

This PR is now focused on casts:
* Enabling debug during regression, which triggered several cast errors, e.g., issue #283.
* Adding the missing casts for compound assignments' operands
* Removing an old cast move from the lhs to rhs during goto construction
* Fix the wrong cast related to the stack size code
* Fix the wrong cast when building a cex with arrays of bools 

The only regression now is issue #283, which is not related to this PR; it is only triggered because this PR enables casts checks.

**Comment by lucasccordeiro** [comment]
@mikhailramalho: I think we have now other test cases failing, e.g., `Float-no-simp8`.

**Comment by mikhailramalho** [comment]
> @mikhailramalho: I think we have now other test cases failing, e.g., `Float-no-simp8`.

These issues are not triggered by this patch. They are only being reported here because I enabled Debug mode in our regressions, see PR #286.

**Comment by mikhailramalho** [comment]
@rafaelsamenezes, could you compare the results of this PR against our current master? Using incr strategy.

**Comment by rafaelsamenezes** [comment]
Summary from SV-Comp'21 with incremental (5min and 5GB):

This PR:
Statistics:          15455 Files
  correct:            5276
    correct true:     3108
    correct false:    2168
  incorrect:           250
    incorrect true:    142
    incorrect false:   108
  unknown:            9929
  Score:              2112 (max: 25033)

Current Master:

Statistics:          15455 Files
  correct:            5130
    correct true:     2961
    correct false:    2169
  incorrect:           114
    incorrect true:      6
    incorrect false:   108
  unknown:           10211
  Score:              6171 (max: 25033)

@mikhailramalho 
Is this branch already rebased?

**Comment by mikhailramalho** [comment]
@rafaelsamenezes, can you run it again? And upload the results somewhere I can download them?

**Comment by rafaelsamenezes** [comment]
Summary from SV-Comp'21 with incremental (5min and 5GB):

This PR:
Statistics:          15455 Files
  correct:            5136
    correct true:     2965
    correct false:    2171
  incorrect:           114
    incorrect true:      6
    incorrect false:   108
  unknown:           10205
  Score:              6181 (max: 25033)

Current Master:

Statistics: 15455 Files
correct: 5130
correct true: 2961
correct false: 2169
incorrect: 114
incorrect true: 6
incorrect false: 108
unknown: 10211
Score: 6171 (max: 25033)

**Pull request merged**
