### PR TITLE
Added bit-vector sign extension to inequalities in SMT conversion

### PR DESCRIPTION
**Pull request by lucasccordeiro**
This PR adds bit-vector sign extension to inequalities in SMT conversion (see https://github.com/esbmc/esbmc/issues/148).

### CODE REVIEW

**Comment by mikhailramalho** [comment]
The actual problem here seems to be that the frontend is not type-promoting the operands correctly; this should be fixed on the frontend.

Furthermore, this will likely generate the wrong formula if the operands are unsigned, as zero-extension should be used instead of sign-extension.

**Comment by lucasccordeiro** [comment]
@mikhailramalho and I have investigated this issue.

The problem seems to lie in the `dereference` module, where we fail to handle this statement properly:

```
!((signed int)(4 * (unsigned long int)((signed long int)queue.tail)) >= 96
```

Our clang frontend seems to correctly build the resulting typecast expression via `clang_c_adjust::adjust_expr_rel`. 

However, when we dereference the pointer for a 64-bit architecture, the size of the `lhs` becomes 64-bit while the size of the `rhs` remains 32-bit, which breaks our SMT backend.

**Comment by lucasccordeiro** [comment]
This big `if-then-else` case, which contains the ill-formed expression, is originally constructed at:

https://github.com/esbmc/esbmc/blob/master/src/pointer-analysis/dereference.cpp#L474

```
(64) invalid_object1&2#1 == (!((signed int)(4 * (unsigned long int)((signed long int)c:@queue&2#14.tail)) >= 96 && (signed int)(4 * (unsigned long int)((signed long int)c:@queue&2#14.tail)) < 104) && !((signed int)(4 * (unsigned long int)((signed long int)c:@queue&2#14.tail)) >= 88 && (signed int)(4 * (unsigned long int)((signed long int)c:@queue&2#14.tail)) < 96) && !((signed int)(4 * (unsigned long int)((signed long int)c:@queue&2#14.tail)) >= 80 && (signed int)(4 * (unsigned long int)((signed long int)c:@queue&2#14.tail)) < 88) && (signed int)(4 * (unsigned long int)((signed long int)c:@queue&2#14.tail)) >= 0 && (signed int)(4 * (unsigned long int)((signed long int)c:@queue&2#14.tail)) < 80 && !(((signed int)(4 * (unsigned long int)((signed long int)c:@queue&2#14.tail))) % 4 == 0) ? c:qq.c@457@F@enqueue@x?1!1&2#1 : invalid_object1&0#0)
```

**Review by rafaelsamenezes — APPROVED** [review]

**Comment by mikhailramalho** [comment]
As I said, 9c5770b4807 (and also 066646553) are the wrong way to fix the issue. These commits should be removed.

**Comment by mikhailramalho** [comment]
I'll remove them and force push.

**Pull request merged**
