### PR TITLE
Rewrite how bitfields are handled

### PR DESCRIPTION
**Pull request by mikhailramalho**
Several changes:
* We now add pads, like it is done by GCC (MSVC does it differently and it is not supported in this PR).
* Remove the alignment round-up when calculating the sizeof of an expression.
* Rewrite the alignment checks to allow byte reads/writes to any object
* Implement bitcasts from structs/arrays/fps to and from bvs in the SMT backend (they can be used to implement new simplifications in the future).
* Some small optimizations/fixes here and there.

This PR should fix several cases from SV-COMP, however, it introduces a regression: when trying to read, say, a uint32 from an array of uint16s, because we are only allowing byte reads/writes for now. 

This can be fixed by increasing the precision (and by removing alignment checks altogether) to allow bit reads/writes but the cost will be bigger formulae and/or longer solving time.

### CODE REVIEW

**Comment by mikhailramalho** [comment]
@lucasccordeiro, could you run this PR over sv-comp? 

There are still a few issues to solve (assignments to bit-fields), but I think it should reduce our incorrect results.

**Comment by lucasccordeiro** [comment]
The results of this PR:

```
Statistics:          15455 Files
  correct:            6820
    correct true:     3214
    correct false:    3606
  incorrect:           145
    incorrect true:      7
    incorrect false:   138
  unknown:            8490
  Score:              7602 (max: 25033)
```

The results of the master branch:
```
Statistics:          15455 Files
  correct:            6723
    correct true:     3114
    correct false:    3609
  incorrect:           242
    incorrect true:      6
    incorrect false:   236
  unknown:            8490
  Score:              5869 (max: 25033)
```

**Comment by lucasccordeiro** [comment]
```
<benchmark tool="esbmc" timelimit="5 min" memlimit="6 GB" cpuCores="1">
<option name="-s">incr</option>
````

```
Binary Version: https://github.com/esbmc/esbmc/actions/runs/598174054
````

```
Statistics:          15455 Files
  correct:            6115
    correct true:     3197
    correct false:    2918
  incorrect:           147
    incorrect true:     12
    incorrect false:   135
  unknown:            9193
  Score:              6768 (max: 25033)
```

**Comment by lucasccordeiro** [comment]
@mikhailramalho: Here are the new results.

```
Statistics:          15455 Files
  correct:            6216
    correct true:     3298
    correct false:    2918
  incorrect:            57
    incorrect true:     12
    incorrect false:    45
  unknown:            9182
  Score:              8410 (max: 25033)
```

March 10th, 2021:

```
Statistics:          15455 Files
  correct:            6191
    correct true:     3301
    correct false:    2890
  incorrect:            45
    incorrect true:     12
    incorrect false:    33
  unknown:            9219
  Score:              8580 (max: 25033)
```

**Comment by mikhailramalho** [comment]
@lucasccordeiro, could you run another run of experiments? I believe it is good enough now to be merged.

**Comment by lucasccordeiro** [comment]
```
Statistics:          15455 Files
  correct:            6191
    correct true:     3301
    correct false:    2890
  incorrect:            45
    incorrect true:     12
    incorrect false:    33
  unknown:            9219
  Score:              8580 (max: 25033)
```

**Pull request merged**
