### PR TITLE
Output huge (un)signedbv constants in a "validator-friendly" way, whatever that means

### PR DESCRIPTION
**Pull request by fbrausse**
The constant expression -9223372036854775808 is actually not supported by contemporary C, because the unary - and the rest are not handled together. That means that the literal 9223372036854775808 will be interpreted as an unsigned long long int and the (implicit) cast to signed long long int will be undefined (because it will touch the sign bit).

The second change done here is to output any constant > LLONG_MAX in hex format. Both of these changes are to please CPAchecker, a tool on a mission to banish large numbers...

### CODE REVIEW

**Comment by fbrausse** [comment]
Just for fun:
```
Invalid configuration
Exception in thread "main" org.sosy_lab.cpachecker.cpa.automaton.AutomatonGraphmlParser$WitnessParseException: Cannot parse witness: The witness automaton provided is invalid! Reason: Cannot parse <x = 18446744073709551615;>
[...]
Caused by: org.sosy_lab.cpachecker.cfa.parser.eclipse.c.CFAGenerationRuntimeException: Integer value is too large to be represented by the highest possible type (unsigned long long int): 18446744073709551615.
	at org.sosy_lab.cpachecker.cfa.parser.eclipse.c.ASTLiteralConverter.getLeastRepresentedTypeForValue(ASTLiteralConverter.java:434)
	at org.sosy_lab.cpachecker.cfa.parser.eclipse.c.ASTLiteralConverter.parseIntegerLiteral(ASTLiteralConverter.java:143)
[...]
```

**Review by mikhailramalho — APPROVED** [review]
Ouch

Do we need all these cases? Do it work if we always print the hex value?

**Review by brcfarias — APPROVED** [review]
I understand that the first case is necessary to handle LLONG_MIN, but could we unify the handling of positive values with hex?

**Comment by fbrausse** [comment]
> could we unify the handling of positive values with hex?

Are you asking whether we should print all positive numbers in hex? If yes, then I would say no, because this change applies generally (not just for svcomp), and most of our users are humans.

Or did I misunderstand?

**Comment by fbrausse** [comment]
> Ouch
> 
> Do we need all these cases? Do it work if we always print the hex value?

It wouldn't reduce the number of cases unfortunately as we'd have to convert it to absolute value for comparison and figure out its sign in order to print `"-"` (or not). The BigInt API isn't really helpful here. But maybe I missed something?

**Comment by fbrausse** [comment]
@brcfarias Could you please check whether this change fixes the errors you did see with CPAchecker? Especially this one I'm not sure about:
```
Error: Invalid configuration (Cannot parse witness: The witness automaton provided is invalid! Reason: Cannot parse <iter->element = { .key=(void *)9223934986799808512, .value=(void *)11259136776077632 };>) (AutomatonGraphmlParser.getAssumptions, SEVERE)
```

**Comment by brcfarias** [comment]
> @brcfarias Could you please check whether this change fixes the errors you did see with CPAchecker? 

I can run the command below with the esbmc binary referenced in svcomp repository (This test case is related to the LLONG_MIN error)

`./esbmc --no-div-by-zero-check --force-malloc-success --state-hashing --add-symex-value-sets --no-align-check --k-step 2 --floatbv --unlimited-k-steps -D'__builtin_unreachable()' --no-vla-size-check ../../sv-benchmarks/c/Juliet_Test/CWE190_Integer_Overflow__int64_t_fscanf_square_21_bad_abs.i --64 --witness-output CWE190_Integer_Overflow__int64_t_fscanf_square_21_bad_abs.i.graphml --no-pointer-check --no-bounds-check --overflow-check --no-assertions --k-induction --max-inductive-step 3`

but when running it with a locally compiled debug version, it crashes with:

```
esbmc/src/util/string_constant.cpp:24: void string_constantt::set_value(const irep_idt&): Assertion `bv_width(type().subtype()) == config.ansi_c.char_width' failed.
[1]    129708 IOT instruction (core dumped)  ./esbmc --no-div-by-zero-check --force-malloc-success --state-hashing
```

Do you know which compilation flags are used for svcomp?

**Comment by fbrausse** [comment]
Yes, try -DCMAKE_BUILD_TYPE=Release.

This error is quite unfortunate, it's https://github.com/esbmc/esbmc/issues/1165 I think. Long standing and we haven't fixed it, yet. But for most benchmarks it's not relevant.

**Comment by brcfarias** [comment]
Using a release version, the error did not occur anymore; however, the tool printed the following warning:

`Expression <operand1=[data], operand2=[operand1=[-9223372036854775807L], operand2=[1], operator=[MINUS]], operator=[EQUALS]> contains unknown variables: [data] (AutomatonGraphmlParser.getAssumptions, WARNING)
`

And it logged the following result:
`Verification result: TRUE. No property violation found by the chosen configuration.`
for this test, where the expected result is false.

**Comment by fbrausse** [comment]
> Using a release version, the error did not occur anymore;

Nice, thanks.

> however, the tool printed the following warning:
> 
> `Expression <operand1=[data], operand2=[operand1=[-9223372036854775807L], operand2=[1], operator=[MINUS]], operator=[EQUALS]> contains unknown variables: [data] (AutomatonGraphmlParser.getAssumptions, WARNING) `
> 
> And it logged the following result: `Verification result: TRUE. No property violation found by the chosen configuration.` for this test, where the expected result is false.

Yeah, there are other bugs. When you look at line 1589 where ESBMC says the assignment to `data` should be, there is no `data` on that line. It's one after `fscanf (stdin, "%" "l" "d", &data);`.

**Comment by fbrausse** [comment]
> > 
> 
> Yeah, there are other bugs. When you look at line 1589 where ESBMC says the assignment to `data` should be, there is no `data` on that line. It's one after `fscanf (stdin, "%" "l" "d", &data);`.

Reason is that we increment the PC before interpreting the intrinsic: https://github.com/esbmc/esbmc/blob/9283607139a397129d6415a3fbbe7b090aa02115/src/goto-symex/symex_main.cpp#L271-L272 Not sure why we do that, but the code rightly so calls it "misery": https://github.com/esbmc/esbmc/blob/9283607139a397129d6415a3fbbe7b090aa02115/src/goto-symex/builtin_functions.cpp#L1288-L1291

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @fbrausse.

**Pull request merged**
