### PR TITLE
Python frontend: Support for pass statement and var declarations without initialization

### PR DESCRIPTION
**Pull request by brcfarias**
https://docs.python.org/3/tutorial/controlflow.html:

_The [pass](https://docs.python.org/3/reference/simple_stmts.html#pass) statement does nothing. It can be used when a statement is required syntactically but the program requires no action. For example:_

```
while True:
    pass  # Busy-wait for keyboard interrupt (Ctrl+C)
```

_This is commonly used for creating minimal classes:_
```
class MyEmptyClass:
    pass
```

### CODE REVIEW

**Review by rafaelsamenezes — COMMENTED** [review]
Does this support functions that return values? I would think that it should return some form of nondet value if it is the case.

**Comment by brcfarias** [comment]
> Does this support functions that return values? I would think that it should return some form of nondet value if it is the case.

Hi @rafaelsamenezes. Yes, the verification is successfull for this program:

```
def foo() -> float:
    pass

foo()
```

**Comment by brcfarias** [comment]
The output for:

```
def foo() -> float:
    pass

print(foo())
```

is `None`

**Comment by brcfarias** [comment]
However we are crashing for the following valid program:

```
def foo() -> float:
    pass

assert (foo() == None)
```

> I would think that it should return some form of nondet value if it is the case.

From the tests, this wouldn't be the case, since nondet() would return a value of the same type as the function's return type instead of None.

This is a case that I can handle on the next PR.

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @brcfarias.

**Review by rafaelsamenezes — APPROVED** [review]

**Pull request merged**
