### PR TITLE
Tentative fix for issue 879

### PR DESCRIPTION
**Pull request by mikhailramalho**

### CODE REVIEW

**Comment by mikhailramalho** [comment]
@rafaelsamenezes, can you run this branch on sv-comp?

**Comment by rafaelsamenezes** [comment]
> @rafaelsamenezes, can you run this branch on sv-comp?

1. Go to https://github.com/esbmc/esbmc/actions/workflows/benchexec.yml
2. Click on "Run workflow"

**Comment by mikhailramalho** [comment]
> > @rafaelsamenezes, can you run this branch on sv-comp?
> 
> 1. Go to https://github.com/esbmc/esbmc/actions/workflows/benchexec.yml
> 2. Click on "Run workflow"

do we have the baseline results somewhere?

**Comment by rafaelsamenezes** [comment]
> > > @rafaelsamenezes, can you run this branch on sv-comp?
> > 
> > 
> > 
> > 1. Go to https://github.com/esbmc/esbmc/actions/workflows/benchexec.yml
> > 2. Click on "Run workflow"
> 
> do we have the baseline results somewhere?

We do not, we can add a master run in the queue though.

**Comment by lucasccordeiro** [comment]
@mikhailramalho: can I ask you to rebase this PR with the master branch?

Our SV-COMP CI is working; we can now run your PR over the SV-COMP benchmarks.

**Comment by mikhailramalho** [comment]
Done

**Comment by lucasccordeiro** [comment]
Thanks, @mikhailramalho.

I will run this PR over the SV-COMP benchmarks as soon as CI gets green.

**Comment by lucasccordeiro** [comment]
This PR is now in the queue to run over SV-COMP.

**Comment by lucasccordeiro** [comment]
Master:

```
Statistics:          26459 Files
  correct:           13792
    correct true:     8275
    correct false:    5517
  incorrect:           916
    incorrect true:    761
    incorrect false:   155
  unknown:           11751
  Score:             -4765 (max: 43043)
```
This PR:

```
Statistics:          26459 Files
correct:           13791
correct true:     8273
correct false:    5518
incorrect:           916
incorrect true:    761
incorrect false:   155
unknown:           11752
Score:             -4768 (max: 43043)
```

**Comment by lucasccordeiro** [comment]
I'll rerun this PR over the SV-COMP after rebasing it with the master branch.

**Comment by lucasccordeiro** [comment]
Master:

```
Statistics:          26459 Files
correct:           14473
correct true:     8259
correct false:    6214
incorrect:            92
incorrect true:     39
incorrect false:    53
unknown:           11894
Score:             20636 (max: 43043)
```

This PR:

```
 Statistics:          26459 Files
  correct:           14476
 correct true:     8256
 correct false:    6220
incorrect:            92
incorrect true:     39
incorrect false:    53
unknown:           11891
Score:             20636 (max: 43043)
```

**Pull request merged**
