### PR TITLE
if2t's type can differ from either side's

### PR DESCRIPTION
**Pull request by fbrausse**
This addresses discrepancies in the translated SMT solver's types between that of the if2t and those of either of its side's. In regression/k-induction-parallel/invert_string for instance, the Z3 and CVC4 backends aborted due to such a construct where the if2t's array size is a small constant but either side's one is a symbol of a larger type.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

Thanks for submitting this PR, @fbrausse  ;-)

**Comment by fbrausse** [comment]
Thanks @lucasccordeiro! I would suggest to run this over SV-COMP before merging, the added type-casts for if2t expressions will probably affect some things. For instance, in the regression test mentioned initially, a new equality is being asserted and for Boolector and other users of `array_convt` the terms generated for "cond ? array1 : array2" also changed.

**Comment by rafaelsamenezes** [comment]
> I would suggest to run this over SV-COMP before merging

I will start a run Monday

**Comment by fbrausse** [comment]
> > I would suggest to run this over SV-COMP before merging
> 
> I will start a run Monday

Thanks @rafaelsamenezes! If you could let me know how it's done with the current setup, I can also do it myself (need to run #905 over it as well).

**Comment by lucasccordeiro** [comment]
Thanks, @fbrausse: are you still able to run PRs over the SV-COMP benchmarks?

**Comment by rafaelsamenezes** [comment]
> Thanks @rafaelsamenezes! If you could let me know how it's done with the current setup

The current setup is quite limited and cannot be used remotely.

**Comment by fbrausse** [comment]
> Thanks, @fbrausse: are you still able to run PRs over the SV-COMP benchmarks?

I think so. Will keep you updated.

**Comment by mikhailramalho** [comment]
This should be fixed where the if is being created, not at the backend.

**Comment by fbrausse** [comment]
@mikhailramalho I know at least one place where it's created, it's described in <https://github.com/esbmc/esbmc/issues/1085>. But unfortunately I don't know enough about the renaming code to fix it there. Seeing that the other solver backends (via array_conv) sidestep this problem basically by ignoring the type information in the `if2t` and instead only relying on that of the `true_value` branch, I thought this would be a better way to handle it. But this one is not important for my other work, so I'm fine with solving this issue another way.

**Comment by fbrausse** [comment]
For the record, this didn't change SV-COMP stats.

Still closing this PR, since it's a workaround that was better solved with #1123. Thanks for reviewing.

**Pull request closed without merging**
