### PR TITLE
Link shared against clang + support external clang headers

### LINKED ISSUE #496: Use CMake to get the clang headers for the current distribution
Currently, we are shipping all the `libclang`  headers [inside our repository](https://github.com/esbmc/esbmc/tree/master/src/clang-c-frontend/headers). 

This makes that for each clang release (official or custom), we must manually replace the headers with the newest. 

 Instead of this, we could use CMake to detect all the files directly from the LLVM configuration. The steps needed to achieve this are:

1. Remove the `clang-c-frontend/headers` directory. Move the CMake file elsewhere
2. Make CMake find the correct path for the headers. For reference, the headers for Clang 11.0.0 are in: `<path-to-clang-11>/lib/clang/11.0.0/include/*.h`
3. Generate the list of all headers inside this path and make it as the `input` [for the mangling](https://github.com/esbmc/esbmc/blob/master/src/clang-c-frontend/headers/CMakeLists.txt#L1)

### LINKED ISSUE #535: Non-static build against system clang
A number of Linux distributions don't ship the individual clang components `libclangTooling.a`, `libclangAST.a` and `libclangIndex.a` anymore ([Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1787375), [openSUSE](https://bugreports.qt.io/browse/QTCREATORBUG-23172?focusedCommentId=524992&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-524992), [Arch](https://bugs.archlinux.org/task/66283), [Gentoo](https://bugs.gentoo.org/710306), maybe others) since clang-10. As these are hardcoded in the `CMakeLists.txt`, it leads to build failures when configuring with the system's `LLVM_DIR` and `-DBUILD_STATIC=Off`:
```
FAILED: src/c2goto/c2goto 
: && /usr/bin/c++ -O2 -g -DNDEBUG  src/c2goto/CMakeFiles/c2goto.dir/c2goto.cpp.o src/c2goto/CMakeFiles/c2goto.dir/cprover_blank_library.cpp.o -o src/c2goto/c2goto  src/goto-programs/libgotoprograms.a  src/langapi/liblangapi.a  src/util/libutil_esbmc.a  src/util/message/libdefault_message.a  src/clang-c-frontend/libclangcfrontend_stuff.a  src/goto-programs/libgotoprograms.a  src/pointer-analysis/libpointeranalysis.a  src/util/libutil_esbmc.a  src/util/message/libdefault_message.a  src/util/message/libmessage.a  src/util/libfilesystem.a  src/util/message/libfmt_message_handler.a  src/util/message/libmessage_handler.a  /usr/lib64/libboost_filesystem.so.1.76.0  /usr/lib64/libboost_system.so.1.76.0  /usr/lib64/libboost_date_time.so.1.76.0  /usr/lib64/libboost_program_options.so.1.76.0  _deps/fmt-build/libfmt.a  src/big-int/libbigint.a  src/clang-c-frontend/AST/libclangcfrontendast.a  -lclangTooling  -lclangAST  -lclangIndex  src/clang-c-frontend/headers/libcheaders.a && :
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lclangTooling
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lclangAST
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lclangIndex
collect2: error: ld returned 1 exit status
```
Is it possible to enable linking against `libclang-cpp.so` in the non-static case? I do not know how Windows or OS X builds are handled, but the patch at https://github.com/fbrausse/esbmc/commit/3115dd0f1b113a8d882c84ceb8877e6ebc91a866 works for me (Gentoo, x86_64).

### PR DESCRIPTION
**Pull request by fbrausse**
This PR fixes #496.

The following changes are made:
- link against libclang-cpp when building in non-static mode
- add cmake options `CLANG_HEADERS_BUNDLED=detect|esbmc|On|Off` (default: `detect`) and `OVERRIDE_CLANG_HEADER_DIR` (default empty) controlling the bundling of clang's headers
- the list of header files is no longer hard-coded in clang-c-frontend/clang-headers.cpp, but generated as `src/clang-c-frontend/headers/cheaders.h` by cmake
- Clang's resource-dir is detected by cmake by extracting the appropriate #define from its sources.

I've tested this for non-static builds. For static builds nothing should change *except* for the last point above: if that fails, the configure stage fails as well. Depending on whether existing setups trigger that, this could be enabled only for non-static builds.

#535 requires this + the goto-libs. #516 could benefit from `OVERRIDE_CLANG_HEADER_DIR` as well.

### CODE REVIEW

**Comment by mikhailramalho** [comment]
Does this mean that we can get rid of the clang headers in our repo?

**Comment by fbrausse** [comment]
Ideally, yes. However I would first test shared builds on different platforms and distributions. The non-bundled headers (defaulted to by shared builds) depend on detection of the CLANG_RESOURCE_DIR #define from the clang installation. In one Ubuntu on an aarch64 platform I have this is empty and automatic detection should probably fall back to invoke "clang -print-resource-dir". This is not implemented, yet and might interfere with cross-compiling.

**Review by rafaelsamenezes — APPROVED** [review]

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Comment by lucasccordeiro** [comment]
@fbrausse: could you please rebase this branch?

**Comment by fbrausse** [comment]
> [..] automatic detection should probably fall back to invoke "clang -print-resource-dir". This is not implemented, yet and might interfere with cross-compiling.

Turns out there is no need for that, I've implemented [the logic](https://clang.llvm.org/doxygen/Driver_8cpp_source.html#l00108) from clang for an empty CLANG_RESOURCE_DIR.

The CI builds now all use the header files from the given clang installation instead of those in `clang-c-frontend/headers`, so  we can indeed remove them along with the option `CLANG_HEADERS_BUNDLED=esbmc`. I'll do that and rebase to master later today.

**Comment by lucasccordeiro** [comment]
Excellent! Many thanks, @fbrausse.

**Comment by lucasccordeiro** [comment]
BTW, could you also update our building instructions, @fbrausse?

**Comment by fbrausse** [comment]
There was a lot of merging going on, I've rebased those out of the history. Should merge cleanly now.

**Pull request merged**
