### PR TITLE
Fix function call starting with nondet 

### PR DESCRIPTION
**Pull request by lucasccordeiro**
This PR should fix function call starting with `nondet`. In particular, it checks whether the `lhs` is not nil before making the side-effect.

### CODE REVIEW

**Review by rafaelsamenezes — APPROVED** [review]
LGTM

**Comment by mikhailramalho** [comment]
Checking the lhs is not enough, ESBMC still doesn't verify the following program correctly:
```
#include <stdio.h>
#include <string.h>

char global_arr[10];


int nondet_init_arr(char *arr)
{
  unsigned int i = 0;
  for(; i < 9; i++)
    arr[i] = nondet_char();
  return 1;
}

void global_fun()
{
  int foo = nondet_init_arr(global_arr); // forcing a lhs 
  unsigned int len = strlen(global_arr);
  assert(len == 0);
}

int main()
{
  global_fun();
  return 0;
}
```

I think part of the correct solution is to change the guard in `builtin_function.cpp:642` from:
```
    if(lhs.is_nil())
      return;
```
to: 
```
    if(lhs.is_nil() && symbol->value.is_nil())
      return;
```
i.e. if the user defines the body of a function, we should call it (maybe this should even be extended to all functions, e.g., assert!).

However, just adding this guard doesn't fix the issue, when the expr reaches symex, it is converted to a nondet symbol. Maybe migrate is broken.

**Comment by lucasccordeiro** [comment]
@mikhailramalho: do you have a test case that shows that when the expr reaches symex, it is converted to a nondet symbol?

I have added some test cases here, but I was unable to expose this problem you mention.

**Comment by mikhailramalho** [comment]
The following patch seems to fix the issue:

[0001-Honour-user-definition-when-builtin-functions-a-rede.patch.txt](https://github.com/esbmc/esbmc/files/5978116/0001-Honour-user-definition-when-builtin-functions-a-rede.patch.txt)

It also fixes programs like:
```
void assert(_Bool a) {}

int main()
{
  assert(0);
  return 0;
}
```
where ESBMC shouldn't fail.

**Pull request merged**
