### PR TITLE
Speed up c2goto

### PR DESCRIPTION
**Pull request by fbrausse**
Before on a debug build: 2m58s, after: 0m6s

### CODE REVIEW

**Review by rafaelsamenezes — APPROVED** [review]
Thanks, the c2goto building was starting to get quite annoying. 

Nice catch though! May I ask how you identified that the serialization was the issue?

**Review by lucasccordeiro — APPROVED** [review]
Nice PR ;-)

**Comment by fbrausse** [comment]
> Thanks, the c2goto building was starting to get quite annoying.
> 
> Nice catch though! May I ask how you identified that the serialization was the issue?

Thanks! I've run the c2goto command performed during build under `perf record -g` and it said that 1. `reference_convert` and in there 2. `full_eq` were the main bottlenecks. There are only a few places `full_eq` is being used. Looking at the original implementation it's clear this would be horrendously slow.

**Comment by fbrausse** [comment]
Here's `perf report -g none` showing lots CPU time for irep serialization (in particular for reference_convert()):
```
# Children      Self  Command  Shared Object                       Symbol                                                          >
# ........  ........  .......  ..................................  ................................................................>
#
    98.96%     0.00%  c2goto   c2goto                              [.] main
    98.96%     0.00%  c2goto   libc.so.6                           [.] __libc_start_call_main
    98.95%     0.00%  c2goto   c2goto                              [.] c2goto_parseopt::doit
    98.95%     0.00%  c2goto   c2goto                              [.] parseoptions_baset::main
    97.57%     2.57%  c2goto   c2goto                              [.] irep_serializationt::reference_convert
    97.51%     0.00%  c2goto   c2goto                              [.] symbol_serializationt::convert
    97.50%     0.00%  c2goto   c2goto                              [.] write_goto_binary(std::ostream&, contextt const&, goto_funct>
    97.50%     0.00%  c2goto   c2goto                              [.] std::__invoke_impl<void, write_goto_binary(std::ostream&, co>
    97.50%     0.00%  c2goto   c2goto                              [.] std::__invoke<write_goto_binary(std::ostream&, contextt cons>
    97.49%     0.00%  c2goto   c2goto                              [.] std::reference_wrapper<write_goto_binary(std::ostream&, cont>
    97.49%     0.00%  c2goto   c2goto                              [.] std::__invoke_impl<void, std::reference_wrapper<write_goto_b>
    97.48%     0.00%  c2goto   c2goto                              [.] std::__invoke_r<void, std::reference_wrapper<write_goto_bina>
    97.48%     0.00%  c2goto   c2goto                              [.] std::_Function_handler<void (symbolt const&), std::reference>
    97.47%     0.00%  c2goto   c2goto                              [.] std::function<void (symbolt const&)>::operator()
    97.47%     0.00%  c2goto   c2goto                              [.] contextt::foreach_operand_impl_const
    97.46%     0.00%  c2goto   c2goto                              [.] write_goto_binary
    97.46%     0.00%  c2goto   c2goto                              [.] contextt::foreach_operand<write_goto_binary(std::ostream&, c>
    93.33%     0.01%  c2goto   c2goto                              [.] irep_serializationt::write_irep
    91.82%     7.62%  c2goto   c2goto                              [.] full_eq
    64.68%    64.64%  c2goto   c2goto                              [.] dstring::operator!=
     7.70%     7.70%  c2goto   c2goto                              [.] std::vector<irept, std::allocator<irept> >::size
     5.90%     5.90%  c2goto   c2goto                              [.] irept::read
     4.58%     1.51%  c2goto   c2goto                              [.] irept::id
```
Without `-g none`, it would show the entire call graph (very big), but that's how `full_eq` "in there" was identified.

**Comment by rafaelsamenezes** [comment]
> > Thanks, the c2goto building was starting to get quite annoying.
> > Nice catch though! May I ask how you identified that the serialization was the issue?
> 
> Thanks! I've run the c2goto command performed during build under `perf record -g` and it said that 1. `reference_convert` and in there 2. `full_eq` were the main bottlenecks. There are only a few places `full_eq` is being used. Looking at the original implementation it's clear this would be horrendously slow.

Guess we could add a Wiki page about profiling.

**Comment by fbrausse** [comment]
Looking for some nice writeup about profiling, I found https://stackoverflow.com/a/60265409

**Pull request merged**
