### PR TITLE
Fixing a memory leak check issue

### LINKED ISSUE #941: [memory-leak] ESBMC provides incorrect verification result
$$ esbmc simple.c --memory-leak-check

````C
#include <stdlib.h>

int main(){

  int *a = (int *) malloc(sizeof(int));

  if(a == NULL)
    return 0;

  free(a);

  return 0;
}
````

````
Counterexample:

State 1 file pthread_simple.c line 5 function main thread 0
----------------------------------------------------
  a = (signed int *)0

State 2 file pthread_simple.c line 13 function main thread 0
----------------------------------------------------
Violated property:
  file pthread_simple.c line 13 function main
  dereference failure: forgotten memory: dynamic_1_value


VERIFICATION FAILED
````

### PR DESCRIPTION
**Pull request by shmarovfedor**
This PR fixes #941.

Problem: all dynamic allocations in ESBMC result in adding a new symbol `dynamic_<num>_value`, while the allocation status is marked via a separate `allocation guard`. In the previous version of the algorithm, ESBMC was iterating over all such dynamic objects requiring all of them to be deallocated (without checking whether the corresponding allocation was successful in the first place).

Solution: adding a condition that forces the above check only for successfully (as specified by the `allocation guard`) allocated dynamic objects, while ignoring all unsuccessful allocations.

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
Many thanks, @shmarovfedor.

Can I ask you to run this PR over the SV-COMP benchmarks? 

You'll have to create a local branch to use the GitHub actions. 

You would also need to update our SV-COMP script to consider the output of the memory leak check.

**Comment by lucasccordeiro** [comment]
Something like this:

````
      if memory_leak in the_output:
        return Result.fail_memtrack
````

**Review by mikhailramalho — COMMENTED** [review]
LGTM.

I suggest testing it first on sv-comp tho

**Comment by shmarovfedor** [comment]
I've just received the results for a benchexec run over SV-COMP with 30s timeout for this patch and with the memory leaks enabled as per @lucasccordeiro instructions:

```
2023-04-04T23:58:36.8615194Z 
2023-04-04T23:58:36.8616985Z Statistics:          26459 Files
2023-04-04T23:58:36.8622436Z   correct:           14812
2023-04-04T23:58:36.8623339Z     correct true:     8257
2023-04-04T23:58:36.8624244Z     correct false:    6555
2023-04-04T23:58:36.8632231Z   incorrect:           220
2023-04-04T23:58:36.8677712Z     incorrect true:     39
2023-04-04T23:58:36.8678435Z     incorrect false:   181
2023-04-04T23:58:36.8678963Z   unknown:           11427
2023-04-04T23:58:36.8679513Z   Score:             18925 (max: 43043)
2023-04-04T23:58:36.8679876Z 
```

**Comment by lucasccordeiro** [comment]
These results are from the master with the modification in the sv-comp script to consider the memory leak results:

```2023-03-23T04:32:23.9616488Z Statistics:          26459 Files
2023-03-23T04:32:23.9617208Z   correct:           14816
2023-03-23T04:32:23.9618714Z     correct true:     8258
2023-03-23T04:32:23.9619262Z     correct false:    6558
2023-03-23T04:32:23.9619720Z   incorrect:           220
2023-03-23T04:32:23.9637011Z     incorrect true:     39
2023-03-23T04:32:23.9637824Z     incorrect false:   181
2023-03-23T04:32:23.9638633Z   unknown:           11423
2023-03-23T04:32:23.9639322Z   Score:             18930 (max: 43043)
```

**Review by lucasccordeiro — APPROVED** [review]

**Pull request merged**
