### PR TITLE
[BUILDING] updated Yices version

### PR DESCRIPTION
**Pull request by XLiZHI**
I encountered an error when trying to build `Yice -2.6.1` and resolved it after trying a new version `2.6.4`. I think we should change to the new version.

ENV: Ubuntu 22.04.3 LTS

### CODE REVIEW

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
@XLiZHI: can you also update the table in the building instructions?

**Review by lucasccordeiro — APPROVED** [review]

**Review by fbrausse — APPROVED** [review]
LGTM. Out of curiosity: what error did you encounter?

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @XLiZHI.

**Comment by XLiZHI** [comment]
> LGTM. Out of curiosity: what error did you encounter?

There is a _multiple definition_ error in the build, which I encountered when I first tried to use ESBMC.

<details>

```
   -o ../build/x86_64-pc-linux-gnu-release/bin/yices_smtcomp ../build/x86_64-pc-linux-gnu-release/obj/frontend/yices_smtcomp.o ../build/x86_64-pc-linux-gnu-release/lib/libyices.a -lgmp
/usr/bin/ld: ../build/x86_64-pc-linux-gnu-release/lib/libyices.a(smt2_commands.o):(.bss+0x280): multiple definition of `smt2_opcodes_t'; ../build/x86_64-pc-linux-gnu-release/obj/frontend/yices_smt2.o:(.bss+0x0): first defined here
/usr/bin/ld: ../build/x86_64-pc-linux-gnu-release/lib/libyices.a(smt2_parser.o):(.bss+0x0): multiple definition of `smt2_opcodes_t'; ../build/x86_64-pc-linux-gnu-release/obj/frontend/yices_smt2.o:(.bss+0x0): first defined here
/usr/bin/ld: ../build/x86_64-pc-linux-gnu-release/lib/libyices.a(smt2_term_stack.o):(.bss+0x0): multiple definition of `smt2_opcodes_t'; ../build/x86_64-pc-linux-gnu-release/obj/frontend/yices_smt2.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:957: ../build/x86_64-pc-linux-gnu-release/bin/yices_smt2] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/lxzy/ESBMC_Project/yices2/src'
make[1]: *** [Makefile.build:370: dist] Error 2
make[1]: Leaving directory '/home/lxzy/ESBMC_Project/yices2'
make: *** [Makefile:278: dist] Error 2
```

**Pull request merged**
