### PR TITLE
Fix wrong usage of equality instead of assignment

### PR DESCRIPTION
**Pull request by fbrausse**
The detailed analysis by @ChenfengWei0 in #1655 correctly identified the problem. An equality on floats is not the same as an assignment of floats. This code hasn't been touched by semantic changes since 72c3d83db91 in 2014. I believe it was a remnant of an earlier version of the smt_conv's interface.

This PR also removes the function set_to() as it has a quite misleading name and is now unused.

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
Many thanks, @fbrausse.

It would be great if you could start an SV-COMP run for this PR.

**Comment by fbrausse** [comment]
I'm running both, [this PR](https://github.com/esbmc/esbmc/actions/runs/7958121416) and [master](https://github.com/esbmc/esbmc/actions/runs/7958127390), since the last master seems to have been 10 days ago.

**Review by ChenfengWei0 — APPROVED** [review]

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @fbrausse.

**Comment by fbrausse** [comment]
> Thanks for submitting this PR, @fbrausse.

Many thanks to @ChenfengWei0 for identifying the cause.

**Comment by lucasccordeiro** [comment]
> Many thanks to @ChenfengWei0 for identifying the cause.

Indeed! Thanks for spotting the root cause of this error, @ChenfengWei0.

**Comment by fbrausse** [comment]
Master:
```
Statistics:          23805 Files
  correct:           13826
    correct true:     7608
    correct false:    6218
  incorrect:            25
    incorrect true:     13
    incorrect false:    12
  unknown:            9954
  Score:             20826 (max: 38482)

https://github.com/esbmc/esbmc/actions/runs/7958127390
```
This PR:
```
Statistics:          23805 Files
  correct:           13792
    correct true:     7580
    correct false:    6212
  incorrect:            24
    incorrect true:     13
    incorrect false:    11
  unknown:            9989
  Score:             20780 (max: 38482)

https://github.com/esbmc/esbmc/actions/runs/7958121416
```
- no-data-race: 1x incorrect false -> timeout
- no-overflow: 1x timeout -> unknown, checking... *Edit:* also timeout noise, master behaves the same (segfault)
- unreach-call: 1x timeout -> unknown and 1x in reverse direction; both (probably #584): `ERROR: GOTO instruction type 0 not handled in goto_symext::symex_step`

The rest is timeout noise.

**Comment by lucasccordeiro** [comment]
Many thanks, @fbrausse.

I'll merge this PR into the master.

**Pull request merged**
