### PR TITLE
Fix repeated assign in cex when printing concats

### PR DESCRIPTION
**Pull request by mikhailramalho**
from #292:
```
Due to how we encode assignments in our memory model, these 4 assignments represent 1 assignment in the original program (as you can see in the value of the startline tag). This happens because we update each byte separately, and since this is an array of bytes, it becomes 4 assignments.
```

This patch fixes the issue and tries to print a single assignment instead of the 4 generated by the `concat`s. It works by:
1. Passing the original rhs (i.e., before being split using 'byte_extract`s) to the SSA. Only in the concat assignment case.
2. Uses the original rhs to build the cex, if it is available.
3. Prevents the generation of 4 assignments by caching both the lhs and rhs's crc.

I'm a bit itchy about 3, can you check if you have any impact on your tests, @kaled-alshmrany?

The generated cex/witness for the program in #292 are quite lengthy now and includes the correct assignments:
```
Counterexample:

State 1 file skippedu.c line 7 thread 0
----------------------------------------------------
  SIZE = 0 (00000000 00000000 00000000 00000000)

State 2 file skippedu.c line 9 thread 0
----------------------------------------------------
  MAX = 100000 (00000000 00000001 10000110 10100000)

State 3 file skippedu.c line 13 function main thread 0
----------------------------------------------------
  SIZE = 2 (00000000 00000000 00000000 00000010)

State 4 file skippedu.c line 17 function main thread 0
----------------------------------------------------
  a = (signed int *)(&dynamic_5_array[0])

State 5 file skippedu.c line 19 function main thread 0
----------------------------------------------------
  i = 0 (00000000 00000000 00000000 00000000)

State 6 file skippedu.c line 21 function main thread 0
----------------------------------------------------
  *(a + i) = 1 (00000000 00000000 00000000 00000001)

State 10 file skippedu.c line 19 function main thread 0
----------------------------------------------------
  i = 1 (00000000 00000000 00000000 00000001)

State 11 file skippedu.c line 21 function main thread 0
----------------------------------------------------
  *(a + i) = 2151677953 (10000000 01000000 00000000 00000001)

State 15 file skippedu.c line 19 function main thread 0
----------------------------------------------------
  i = 2 (00000000 00000000 00000000 00000010)

State 20 file skippedu.c line 3 function __VERIFIER_assert thread 0
----------------------------------------------------
Violated property:
  file skippedu.c line 3 function __VERIFIER_assert
  assertion
  0

VERIFICATION FAILED

Bug found (k = 6)
```
```
    <node id="N1"/>
    <edge id="E0" source="N0" target="N1">
      <data key="enterFunction">main</data>
      <data key="createThread">0</data>
    </edge>
    <node id="N2"/>
    <edge id="E1" source="N1" target="N2">
      <data key="startline">7</data>
      <data key="assumption">SIZE = 0;</data>
      <data key="threadId">0</data>
    </edge>
    <node id="N3"/>
    <edge id="E2" source="N2" target="N3">
      <data key="startline">9</data>
      <data key="assumption">MAX = 100000;</data>
      <data key="threadId">0</data>
    </edge>
    <node id="N4"/>
    <edge id="E3" source="N3" target="N4">
      <data key="startline">13</data>
      <data key="assumption">SIZE = 2;</data>
      <data key="threadId">0</data>
    </edge>
    <node id="N5"/>
    <edge id="E4" source="N4" target="N5">
      <data key="startline">17</data>
      <data key="threadId">0</data>
    </edge>
    <node id="N6"/>
    <edge id="E5" source="N5" target="N6">
      <data key="startline">19</data>
      <data key="assumption">i = 0;</data>
      <data key="threadId">0</data>
    </edge>
    <node id="N7"/>
    <edge id="E6" source="N6" target="N7">
      <data key="startline">21</data>
      <data key="assumption">*(a + i) = 1;</data>
      <data key="threadId">0</data>
    </edge>
    <node id="N8"/>
    <edge id="E7" source="N7" target="N8">
      <data key="startline">19</data>
      <data key="assumption">i = 1;</data>
      <data key="threadId">0</data>
    </edge>
    <node id="N9"/>
    <edge id="E8" source="N8" target="N9">
      <data key="startline">21</data>
      <data key="assumption">*(a + i) = 2151677953;</data>
      <data key="threadId">0</data>
    </edge>
    <node id="N10"/>
    <edge id="E9" source="N9" target="N10">
      <data key="startline">19</data>
      <data key="assumption">i = 2;</data>
      <data key="threadId">0</data>
    </edge>
    <node id="N11">
      <data key="violation">true</data>
    </node>
    <edge id="E10" source="N10" target="N11">
      <data key="startline">3</data>
      <data key="threadId">0</data>
    </edge>
```

esbmc --no-div-by-zero-check --force-malloc-success --state-hashing --no-align-check --k-step 5 --floatbv --unlimited-k-steps --context-bound 2 skippedu.c --32 --witness-output skippedu.c.graphml --falsification --no-pointer-check --no-bounds-check --interval-analysis --no-slice

### CODE REVIEW

**Comment by kaled-alshmrany** [comment]
Many thanks @mikhailramalho 

I will test it tomorrow and provide you the results.

BTW, @rafaelsamenezes  already sent me a (fixed version of ESBMC) and it worked well for the example "skipeduu.c". 

Is it difference from what  @rafaelsamenezes sent to me?

However, I need to test this version on other benchmarks to see in case it has issues or not compared with v6.0.

**Review by lucasccordeiro — APPROVED** [review]
@mikhailramalho: Is there some way to add regression tests here?

**Comment by rafaelsamenezes** [comment]
> Is it difference from what @rafaelsamenezes sent to me?

This should also fix the issue with having extra inputs in the testcase

**Review by rafaelsamenezes — APPROVED** [review]

**Comment by mikhailramalho** [comment]
Just to be clear: I still don't think this is the right fix, it's a workaround.

That's why I asked @kaled-alshmrany to test it, if it improves our scores in test-comp, we send a version with this patch, but even so I don't think this should be merged to master.

**Comment by mikhailramalho** [comment]
Merged as part of the updates for sv-comp.

**Pull request closed without merging**
