### PR TITLE
Display dereferenced pointer-arithmetic as `p[idx]`

### PR DESCRIPTION
**Pull request by fbrausse**
Addresses #725 which aimed at removing the frontend's translation of `p[i]` to `*(p+i)`.

During the discussion it has become clear that repurposing the `index2t` type for that breaks in a few places since currently it operates only on array- and string-typed source expressions. Thus, this PR keeps the translation in the frontend, and instead adjusts the counter-example presentation to recognize pointer-arithmetic under dereferences and display those in the index notation.

It does so recursively, e.g. `*((0+p)-(1-(1+3))` gets displayed as `p[0 - (1 - (1 + 3))]` and thus should address https://github.com/esbmc/esbmc/issues/725#issuecomment-1152436623 as well.

### CODE REVIEW

**Review by mikhailramalho — APPROVED** [review]
LGTM, thanks @fbrausse!

**Review by lucasccordeiro — APPROVED** [review]

**Comment by fbrausse** [comment]
Thanks for your reviews!

@mikhailramalho the `cmt_lvalue` changes in your patch in #725, are they independent and could be applied in addition with those in this PR? What is the meaning of `cmt_lvalue`?

**Comment by mikhailramalho** [comment]
It was probably for typechecking in the old frontend, but it seems we don't use it anymore

**Comment by rafaelsamenezes** [comment]
@fbrausse do you think that we could create some stable test cases for this in the CE?

**Comment by lucasccordeiro** [comment]
@fbrausse: could you please rebase this PR with the master branch?

**Comment by fbrausse** [comment]
@rafaelsamenezes Not sure, I could of course encode the status-quo output (and maybe the previous one) into a regex for some particular cases, but if at some point we decide to reorder/simplify operands the test case would fail. Is that what you had in mind?

@lucasccordeiro done

**Comment by rafaelsamenezes** [comment]
> @rafaelsamenezes Not sure, I could of course encode the status-quo output (and maybe the previous one) into a regex for some particular cases, but if at some point we decide to reorder/simplify operands the test case would fail. Is that what you had in mind?

Yes, and you are correct. It would be hard to make it stable.

**Pull request merged**
