### PR TITLE
Update release-notes.txt for ESBMC v7.7

### PR DESCRIPTION
**Pull request by lucasccordeiro**

### CODE REVIEW

**Comment by ChenfengWei0** [comment]
Shall we mention the update of condition coverage?

**Comment by lucasccordeiro** [comment]
> Shall we mention the update of condition coverage?

Yes. What is the PR?

**Comment by ChenfengWei0** [comment]
> Yes. What is the PR?

https://github.com/esbmc/esbmc/pull/1999

**Comment by lucasccordeiro** [comment]
> https://github.com/esbmc/esbmc/pull/1999

Done.

**Review by XLiZHI — APPROVED** [review]

**Comment by brcfarias** [comment]
Could we include #1957 ?

**Review by ChenfengWei0 — APPROVED** [review]

**Comment by ChenfengWei0** [comment]
> > #1999
> 
> Done.

Many thanks

**Comment by lucasccordeiro** [comment]
> Could we include https://github.com/esbmc/esbmc/pull/1957 ?

Done.

**Review by Anthonysdu — APPROVED** [review]

**Review by rafaelsamenezes — APPROVED** [review]

**Review by brcfarias — APPROVED** [review]

**Pull request merged**
