### PR TITLE
Fix issue #375

### PR DESCRIPTION
**Pull request by mikhailramalho**
The constants depend on the running arch (32 or 64 bits), so try to generate an ulong to calculate offset.

@rafaelsamenezes, can you run it on SV-Comp benchmarks?

### CODE REVIEW

**Comment by mikhailramalho** [comment]
The actual fix is in `src/pointer-analysis/value_set.cpp` the other stuff is code style.

**Comment by lucasccordeiro** [comment]
@mikhailramalho: This PR is running in `fm11.cs.manchester.ac.uk` over the entire SV-COMP suite. The results should be ready in two days.

**Comment by lucasccordeiro** [comment]
Here are the results:

PR (`fm11.cs.manchester.ac.uk`):
```
Statistics:          15455 Files
  correct:            6723
    correct true:     3114
    correct false:    3609
  incorrect:           242
    incorrect true:      6
    incorrect false:   236
  unknown:            8490
  Score:              5869 (max: 25033)
```

Master (`fm10.cs.manchester.ac.uk`):
```
Statistics:          15455 Files
  correct:            6716
    correct true:     3116
    correct false:    3600
  incorrect:           242
    incorrect true:      6
    incorrect false:   236
  unknown:            8497
  Score:              5864 (max: 25033)
```

**Comment by mikhailramalho** [comment]
I just checked the results and the diff is mostly timeouts. Running all the cases without timeout resulted in the same verdict.

I suggest merging this branch.

**Comment by lucasccordeiro** [comment]
I agree.

**Pull request merged**
