### PR TITLE
[SMT backend] Update API to Use Bitwuzla 0.5.0

### PR DESCRIPTION
**Pull request by lucasccordeiro**
We are updating our API and documentation to integrate Bitwuzla v0.5.0, the latest release of the Bitwuzla SMT solver. For more details on the new release, visit [Bitwuzla Releases](https://github.com/bitwuzla/bitwuzla/releases).

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
I have just started two runs to evaluate the integration of bitwuzla 0.5.0 over the SV-COMP benchmarks:

Master: https://github.com/esbmc/esbmc/actions/runs/9636043814 (bitwuzla 0.3.1)

This PR: https://github.com/esbmc/esbmc/actions/runs/9636039645 (bitwuzla 0.5.0)

**Comment by lucasccordeiro** [comment]
Master (https://github.com/esbmc/esbmc/actions/runs/9636043814):

````
2024-06-24T00:12:58.9654779Z Statistics:          23805 Files
2024-06-24T00:12:58.9656020Z   correct:           13073
2024-06-24T00:12:58.9657112Z     correct true:     7709
2024-06-24T00:12:58.9676251Z     correct false:    5364
2024-06-24T00:12:58.9677607Z   incorrect:            40
2024-06-24T00:12:58.9678510Z     incorrect true:     13
2024-06-24T00:12:58.9679448Z     incorrect false:    27
2024-06-24T00:12:58.9681014Z   unknown:           10692
2024-06-24T00:12:58.9682257Z   Score:             19934 (max: 38482)
````

This PR (https://github.com/esbmc/esbmc/actions/runs/9636039645):

````
2024-06-23T23:55:52.9006931Z Statistics:          23805 Files
2024-06-23T23:55:52.9008239Z   correct:           13332
2024-06-23T23:55:52.9009133Z     correct true:     7907
2024-06-23T23:55:52.9009966Z     correct false:    5425
2024-06-23T23:55:52.9010832Z   incorrect:            42
2024-06-23T23:55:52.9011848Z     incorrect true:     14
2024-06-23T23:55:52.9013252Z     incorrect false:    28
2024-06-23T23:55:52.9014218Z   unknown:           10431
2024-06-23T23:55:52.9015084Z   Score:             20343 (max: 38482)
````

Master with Boolector (https://github.com/esbmc/esbmc/actions/runs/9616078574):

````
Statistics:          23805 Files
  correct:           14160
    correct true:     7778
    correct false:    6382
  incorrect:            42
    incorrect true:     13
    incorrect false:    29
  unknown:            9603
  Score:             21058 (max: 38482)
````

**Comment by lucasccordeiro** [comment]
Bitwuzla 0.50 can solve more correct true results than Boolector 3.2.2.

Boolector 3.2.2 can solve more correct false results than Bitwuzla 0.50.

We might use Bitwuzla for the forward condition, inductive step checks, and Boolector for the base case check.

**Review by brcfarias — APPROVED** [review]
Just a nitpick: bitw_TermManager could be renamed to snake_case (replacing uppercases) to match the other attributes.

**Comment by lucasccordeiro** [comment]
> Just a nitpick: bitw_TermManager could be renamed to snake_case (replacing uppercases) to match the other attributes.

Many thanks, @brcfarias. Implemented as suggested.

**Comment by rafaelsamenezes** [comment]
> Bitwuzla 0.50 can solve more correct true results than Boolector 3.2.2.
> 
> Boolector 3.2.2 can solve more correct false results than Bitwuzla 0.50.
> 
> We might use Bitwuzla for the forward condition, inductive step checks, and Boolector for the base case check.

We should extract some formulas and ask the devs about this regression.

**Pull request merged**
