### PR TITLE
Fix issues #331 #367

### PR DESCRIPTION
**Pull request by mikhailramalho**
This is currently breaking our regression because it removes all alignment calculations (used by the --align-check flag).

@rafaelsamenezes, can you run this patch on the memory category from SV-Comp?

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
@mikhailramalho: Shall we update every occurrence of `constant_int2tc` by `gen_ulong` as you did in `https://github.com/esbmc/esbmc/pull/377/files#diff-eeb9a7e481687c19d1d71dbe65464649a740323aea4ba1f0822f26b4ecce9366R123`?

**Comment by lucasccordeiro** [comment]
This test case should fail https://github.com/esbmc/esbmc/pull/378/files#diff-83fc7e53d8bc250aa818f3f983073cd64390e3686a3484524ebde002bcb88bbcR1, but this PR provides `VERIFICATION SUCCESSUL`.

**Comment by lucasccordeiro** [comment]
@mikhailramalho: While we don't fix the compilation problem in the CI, I won't be to run this PR in our servers. I need to obtain from the `actions` tab the Linux binary, which is not being generated because of the compilation problem in the CI.

**Comment by mikhailramalho** [comment]
For now, I don't think so.

There are several places where we create constants in that file, but it is
relatively stable right now.

**Pull request closed without merging**
