### PR TITLE
rename_type() should also recurse into operands

### LINKED ISSUE #60: terminate called after throwing an instance of 'array_type2t::dyn_sized_array_excp*'
ESBMC fails for this particular program when we call it as:

esbmc main.c --unwind 10
```
# include <stdio.h>
# include <stdlib.h>
# include <assert.h>

typedef int __nodetype;

typedef struct node {
    __nodetype key;
    struct node *next;
} NODE;

static unsigned int vertices;

int get_graph_size(char *argv[]) {
  unsigned int size=0;
  int a, b;
  FILE *fp;
  fp = fopen(argv[1],"r");
  if (!fp) {
    printf("Failed to open the file %s.\n",argv[1]);
    return -1;
  }
  while (!feof(fp)) {
    fscanf(fp,"%d%d", &a, &b);
    size = a > size ? a : size;
    size = b > size ? b : size;
  }

  ++size;
  printf("graph size: %d\n", size);

  return size;
}

void insert_node(NODE* list[], int a, int b){
    NODE* l = (NODE*)malloc(sizeof(NODE));
    if (list[a] == NULL) {
        l->key = b;
        l->next = NULL;
    } else {
        l->key = b;
        l->next = list[a];
    }
    list[a] = l;
}

void print_adjacent_list(NODE *list[]){
  int i;
  NODE *tmp;
  printf("\nPrinting adjacent list...\n\n");
  for(i=0; i<vertices; i++) {
    if (list[i]!=NULL) {
      printf("(%d) ==> %d ", i, list[i]->key) ;
      tmp = list[i]->next;
      while (tmp != NULL) {
        printf("==> %d  ", tmp->key);
        tmp = tmp->next;
      }
    }
    printf("\n");
  }
}

void print_adjacent_matrix(__nodetype matrix[vertices][vertices]) {
  int i, j;
  printf("\nPrinting adjacent matrix...\n\n");
  for(i=0; i<vertices; i++) {
    for(j=0; j<vertices; j++) {
      printf("%d ", matrix[i][j]);
    }
    printf("\n");
  }
}

int create_adjacent_list(char *argv[], NODE *list[]) {
  int i, a, b, prev_a, prev_b;
  FILE *fp;
  fp = fopen(argv[1],"r");

  for(i=0; i<vertices; i++)
    list[i]=NULL;

  if (!fp) {
    printf("Failed to open the file %s.\n",argv[1]);
    return -1;
  }

  while (!feof(fp)) {
    fscanf(fp,"%d%d", &a, &b);
    if (prev_a != a || prev_b != b) {
          printf("a: %d, b: %d\n", a, b);
      insert_node(list, a, b);
    }
    prev_a = a;
    prev_b = b;
  }
  return 0;
}

int create_adjacent_matrix(char *argv[], __nodetype matrix[vertices][vertices]) {
  int i, j, a, b, prev_a, prev_b;
  FILE *fp;
  fp = fopen(argv[1],"r");

  for(i=0; i<vertices; i++)
    for(j=0; j<vertices; j++)
      matrix[i][j] = 0;

  if (!fp) {
    printf("Failed to open the file %s.\n",argv[1]);
    return -1;
  }

  while (!feof(fp)) {
    fscanf(fp,"%d%d", &a, &b);
    if (prev_a != a || prev_b != b) {
          printf("a: %d, b: %d\n", a, b);
      matrix[a][b]=1;
    }
    prev_a = a;
    prev_b = b;
  }
  return 0;
}

int main(int argc, char *argv[]){

  vertices = get_graph_size(argv);

  NODE *adjacent_list[vertices];
  __nodetype adjacent_matrix[vertices][vertices];

  create_adjacent_list(argv, adjacent_list);
  print_adjacent_list(adjacent_list);

  create_adjacent_matrix(argv, adjacent_matrix);
  print_adjacent_matrix(adjacent_matrix);

  return 0;
}
```

### LINKED ISSUE #1085: Level2 renaming of VLA array size creates invalid if2t expressions
Investigating the error mentioned in https://github.com/esbmc/esbmc/pull/1083#issuecomment-1590955655 for Z3 turned out to be due to an invalid if2t expression being translated to SMT:
```
if
* cond : symbol
    * name : goto_symex::guard
    * renamelev : Level 2
    * level1_num : 0
    * level2_num : 12
    * thread_num : 0
    * node_num : 0
    * type : bool
* true_value : symbol
    * name : c:gh-1070.c@421@F@main@url
    * renamelev : Level 2
    * level1_num : 1
    * level2_num : 2
    * thread_num : 0
    * node_num : 0
    * type : array
      * subtype : signedbv
          * width : 8
      * array_size : symbol
          * name : c:@F@main::$tmp::return_value$_strlen$1
          * renamelev : Level 0
          * level1_num : 0
          * level2_num : 0
          * thread_num : 0
          * node_num : 0
          * type : unsignedbv
            * width : 64
      * size_is_infinite : false
* false_value : symbol
    * name : c:gh-1070.c@421@F@main@url
    * renamelev : Level 2
    * level1_num : 1
    * level2_num : 3
    * thread_num : 0
    * node_num : 0
    * type : array
      * subtype : signedbv
          * width : 8
      * array_size : symbol
          * name : c:@F@main::$tmp::return_value$_strlen$1
          * renamelev : Level 0
          * level1_num : 0
          * level2_num : 0
          * thread_num : 0
          * node_num : 0
          * type : unsignedbv
            * width : 64
      * size_is_infinite : false
* type : array
  * subtype : signedbv
      * width : 8
  * array_size : constant_int
      * value : 0
      * type : unsignedbv
        * width : 64
  * size_is_infinite : false
```
The type of the if2t-expression has been mangled and does no longer correspond to those of either branches. The if2t expression itself is constructed with properly aligned types, however, this mangling happens in https://github.com/esbmc/esbmc/blob/ee286d92a125aa7fc3a966fc4ca85dfcd057ef9b/src/goto-symex/renaming.cpp#L149 since `it->second.constant` is the non-nil
```
constant_int
* value : 0
* type : unsignedbv
  * width : 64
```

### PR DESCRIPTION
**Pull request by fbrausse**
Another take on fixing the failing cases from #1070 as suggested in https://github.com/esbmc/esbmc/pull/1121#issuecomment-1605586220, and this time also a fix for #1085 and #60 (though --unwind 10 takes too long, I've reduced it to 3).

`goto_symex_statet::rename_type()` did only consider the expression's type and
its subtypes and not sub-expressions as well. This causes the sub-expressions
for instance in the if2t `cond ? array1 : array2`, to not be considered,
triggering issues with the Z3 and CVC4 backends due to mismatching bv-widths
for array sizes. Something that's supposedly fixed up by the internal
fixup_renamed_type() for other kinds of expressions, but for some reason that's
only invoked for symbols, not ifs, and for renaming exprs, not types.
So the the recursion is put into the public `rename_type()` interface instead.

The other backends using array_conv have not been affected because they simply
ignore the if2t's type annotation and go with that of the true_value sub-expr.
As now they act on arrays of different sizes, I would again suggest to test this on SV-COMP.

**Edit:** Turns out the other backends have been affected to some degree by the missing type renaming in sub-exprs.

### CODE REVIEW

**Review by mikhailramalho — COMMENTED** [review]
Yeah, that makes more sense!

I wonder if we could get rid of the the rename_type call and force it whenever we call rename. There might be some performance penalty tho

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @fbrausse.

@rafaelsamenezes: can you run this PR over the SV-COMP benchmarks too?

**Comment by fbrausse** [comment]
Master (ac9ec4d1362f86b5505095b90e1549e2992c9d96):
```
Statistics:          26459 Files
  correct:           14370
    correct true:     8158
    correct false:    6212
  incorrect:            60
    incorrect true:     30
    incorrect false:    30
  unknown:           12029
  Score:             21088 (max: 43043)
```
This PR (591b023de1264f758d8651ac9e793ce54e4348af):
```
Statistics:          26459 Files
  correct:           14374
    correct true:     8161
    correct false:    6213
  incorrect:            60
    incorrect true:     30
    incorrect false:    30
  unknown:           12025
  Score:             21095 (max: 43043)
```
**Edit:** This is for 30s (on the fm08 VM).

**Comment by lucasccordeiro** [comment]
Great! Thanks for submitting this PR, @fbrausse.

**Pull request merged**
