### PR TITLE
[symex] make alloca handling more robust

### PR DESCRIPTION
**Pull request by intrigus-lgtm**
Don't free pointers returned from `alloca`te functions. Pointers from functions called `alloca$` will still be incorrectly freed, but this is for a future PR.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Review by XLiZHI — APPROVED** [review]

**Review by rafaelsamenezes — APPROVED** [review]

**Comment by rafaelsamenezes** [comment]
Maybe we could replace it with a regex? Something like "alloca$\d+".

**Comment by lucasccordeiro** [comment]
> Maybe we could replace it with a regex? Something like "alloca$\d+".

@intrigus: could you please try this approach?

**Comment by intrigus-lgtm** [comment]
> > Maybe we could replace it with a regex? Something like "alloca$\d+".
> 
> @intrigus: could you please try this approach?

I will not try this approach as it's also not complete, i.e. a function called `alloca$111` would still fail.
I don't have the time for a complete solution and the alloca handling in esbmc looks pretty broken anyway.

The main motivation for this PR is to unblock my c++ code that uses std::allocator<T>.

**Comment by rafaelsamenezes** [comment]
> > > Maybe we could replace it with a regex? Something like "alloca$\d+".
> > 
> > 
> > @intrigus: could you please try this approach?
> 
> I will not try this approach as it's also not complete, i.e. a function called `alloca$111` would still fail. I don't have the time for a complete solution and the alloca handling in esbmc looks pretty broken anyway.

That would generate "alloca$111$<digits>", no?

**Comment by lucasccordeiro** [comment]
> The main motivation for this PR is to unblock my c++ code that uses std::allocator.

Thanks, @intrigus.

I have asked Rafael to submit another PR with his proposal.

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @intrigus-lgtm.

**Comment by intrigus-lgtm** [comment]
> > The main motivation for this PR is to unblock my c++ code that uses std::allocator.
> 
> Thanks, @intrigus.
> 
> I have asked Rafael to submit another PR with his proposal.

Sorry, for not being more helpful, just pretty busy and keeping my thesis' deadline in mind.

**Pull request merged**
