### PR TITLE
[WiP] [Benchexec] CSmith Fuzzing Regression Tests

### PR DESCRIPTION
**Pull request by ericksonalves**

### CODE REVIEW

**Comment by ericksonalves** [comment]
@lucasccordeiro this is the initial PR for the csmith fuzzing tests.

**Review by lucasccordeiro — DISMISSED** [review]
You need to create the test.desc file for each test case.

**Comment by lucasccordeiro** [comment]
Here is one example of test.desc

```
KNOWNBUG
main.c
--unwind 10 --show-symex-value-sets --symex-trace --ssa-smt-trace --show-goto-value-sets --symex-ssa-trace --ssa-trace
^VERIFICATION FAILED$
```

Here is an example to run a given regression suite (e.g., csmith):

```
$python3 testing_tool.py --regression csmith --tool /Users/lucasccordeiro/esbmc/build/src/esbmc/esbmc --mode CORE
```

- regression indicates the suite we want to verify (e.g., csmith).
- tool indicates the location of the binary we want to use.
- mode indicates which test cases will be executed; possible values are: CORE, KNOWNBUG, FUTURE, and THOROUGH

**Comment by ericksonalves** [comment]
A new one has been added to avoid conflicts with `master` branch.

**Pull request closed without merging**
