### PR TITLE
show not unwinding loop info

### PR DESCRIPTION
**Pull request by Anthonysdu**
This PR is to follow the conversation : #1291

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Review by mikhailramalho — CHANGES_REQUESTED** [review]
There is a bit of duplicated code there, please remove it

**Review by lucasccordeiro — APPROVED** [review]
Well spotted, @mikhailramalho.

Thanks for improving this code fragment, @Anthonysdu.

**Review by mikhailramalho — APPROVED** [review]
lgtm

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @Anthonysdu.

**Pull request merged**
