### PR TITLE
[regression] added CHERI-C++ test suite

### PR DESCRIPTION
**Pull request by kunjsong01**
Added CHERI-C++ test cases. 
This is done by modifying existing test cases of `regression/cheri-c` to include some preliminary C++ language features.

### CODE REVIEW

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
@kunjsong01: shall we rename the file extension to .cpp?

**Comment by fbrausse** [comment]
> @kunjsong01: shall we rename the file extension to .cpp?

I think we need to do that. ESBMC decides the language based on the extension - as everybody does.

**Comment by lucasccordeiro** [comment]
@kunjsong01: could you please address our comments?

**Comment by lucasccordeiro** [comment]
@kunjsong01?

**Review by XLiZHI — APPROVED** [review]
LGTM

**Review by fbrausse — APPROVED** [review]

**Comment by fbrausse** [comment]
@XLiZHI Usually people involved in writing PRs do not approve of their own PRs. It dilutes the "rule of 2 (except if Lucas wants it)" that we have about PRs. ;)

**Comment by lucasccordeiro** [comment]
@fbrausse is correct.

**Review by lucasccordeiro — APPROVED** [review]

**Pull request merged**
