### PR TITLE
Take cur_state->guard into account for creating a new thread

### PR DESCRIPTION
**Pull request by fbrausse**
Fixes SV-COMP memsafety
- c/goblint-regression/04-mutex_46-escape_nr.yml
- c/ldv-races/race-2_1-container_of.yml
- c/ldv-races/race-2_2-container_of.yml
- c/ldv-races/race-2_3-container_of.yml
- c/ldv-races/race-2_4-container_of.yml
- c/ldv-races/race-2_5-container_of.yml
- c/ldv-races/race-3_1-container_of-global.yml
- c/ldv-races/race-3_2-container_of-global.yml

I'm running sv-comp on this.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR,@franz.

Can I ask you please to add some regression tests?

**Comment by fbrausse** [comment]
Thanks @lucasccordeiro. Will do once the sv-comp results are in. I'm in new terrain here with the threading; still not entirely clear on how all the different guards interact. Just some.

**Comment by fbrausse** [comment]
For SV-COMP's `main` branch (not svcomp23, which the stats-30s.txt tracks) the results are in:
PR #1455 (base of this PR):
```
Statistics:          30471 Files
  correct:           17965
    correct true:    11130
    correct false:    6835
  incorrect:            52
    incorrect true:     20
    incorrect false:    32
  unknown:           12454
  Score:             27943 (max: 51065)

https://github.com/esbmc/esbmc/actions/runs/6815270285
```
This PR:
```
Statistics:          30471 Files
  correct:           17976
    correct true:    11146
    correct false:    6830
  incorrect:            42
    incorrect true:     19
    incorrect false:    23
  unknown:           12453
  Score:             28146 (max: 51065)

https://github.com/esbmc/esbmc/actions/runs/6815261437
```
Unexpectedly also solves previously incorrect unreach-call
- c/aws-c-common/aws_array_eq_harness-1.i

Lots of timeout fluctuation, but I guess it's safe to assume that svcomp23 results would be similar. I'll remove merging #1455 into this and add some regression tests.

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @fbrausse.

**Pull request merged**
