### PR TITLE
Update Bitwuzla to v0.3.0

### PR DESCRIPTION
**Pull request by fbrausse**

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
@fbrausse: could you please run this PR over the SV-COMP benchmarks using bitwuzla? We should compare the performance of Bitwuzla 0.2 (master) and 0.3 (this PR).

**Comment by fbrausse** [comment]
> could you please run this PR over the SV-COMP benchmarks using bitwuzla? We should compare the performance of Bitwuzla 0.2 (master) and 0.3 (this PR).

Indeed. I've started a [master](https://github.com/esbmc/esbmc/actions/runs/7386041469) and [v0.3.0](https://github.com/esbmc/esbmc/actions/runs/7386044091) run.

**Comment by fbrausse** [comment]
Well, with the new sped up benchexec we have quite some fluctuation.
Master:
```
Statistics:          23805 Files
  correct:           12765
    correct true:     7548
    correct false:    5217
  incorrect:            30
    incorrect true:     14
    incorrect false:    16
  unknown:           11010
  Score:             19609 (max: 38482)

https://github.com/esbmc/esbmc/actions/runs/7386041469
```
This PR first run:
```
Statistics:          23805 Files
  correct:           12707
    correct true:     7505
    correct false:    5202
  incorrect:            28
    incorrect true:     14
    incorrect false:    14
  unknown:           11070
  Score:             19540 (max: 38482)

https://github.com/esbmc/esbmc/actions/runs/7386044091
```
This PR second run (everything unchanged):
```
Statistics:          23805 Files
  correct:           12767
    correct true:     7554
    correct false:    5213
  incorrect:            27
    incorrect true:     13
    incorrect false:    14
  unknown:           11011
  Score:             19681 (max: 38482)

https://github.com/esbmc/esbmc/actions/runs/7389331111
```
All in all I would still say it's fine to recommend the latest version of Bitwuzla.

@rafaelsamenezes Are there news about the hopefully more stable 15-thread benchexec runs?

**Comment by lucasccordeiro** [comment]
Many thanks, @fbrausse.

**Pull request merged**
