### PR TITLE
Feature/add solidity overflow check

### PR DESCRIPTION
**Pull request by correcthorsebatterystaple**
PR implements changes suggested in issue https://github.com/esbmc/esbmc/issues/776

Changes:
- Add language string to `configt`
- Add overflow checks for unsigned types for solidity only
- Add regression tests for automated overflow checks on both signed and unsigned types

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
@correcthorsebatterystaple: Could you please check these regression tests?

```
he following tests FAILED:
	789 - regression/esbmc-solidity/int_overflow_check (Failed)
	793 - regression/esbmc-solidity/uint_overflow_check (Failed)
```

**Review by fbrausse — COMMENTED** [review]
Personally, I'm not a big fan of storing computed information in strings. An enum would be much nicer as it is easier to compare/`switch` on, avoids dynamic allocation, can be used as an index into arrays, has all possible values explicitely and centrally defined, etc.

Doing that properly would probably require cleaning up the `mode_table` handling, though, so I'm fine with this way now. We can change it later.

Could you add a comment to the new `configt::language` member explaining what it is?

For the failing tests you might want to enable the `--overflow-check`. ;)

**Comment by correcthorsebatterystaple** [comment]
> Personally, I'm not a big fan of storing computed information in strings. An enum would be much nicer as it is easier to compare/`switch` on, avoids dynamic allocation, can be used as an index into arrays, has all possible values explicitely and centrally defined, etc.
> 
> 
> 
> Doing that properly would probably require cleaning up the `mode_table` handling, though, so I'm fine with this way now. We can change it later.

I must agree I too am not a big fan of magic strings. However, as you said would require a larger refactor to have that be consistent with the mode table implementation. 

> 
> 
> 
> Could you add a comment to the new `configt::language` member explaining what it is?

Will add

> For the failing tests you might want to enable the `--overflow-check`. ;)

Oops

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Review by fbrausse — APPROVED** [review]

**Pull request merged**
