### PR TITLE
Intrigus/improve shift types checks

### PR DESCRIPTION
**Pull request by intrigus-lgtm**
Use the correct type for generating the width constant.
Remove unused code in smt_overflow that would lead to
problems downstream, because the ops of the lessthan2tc could
have different signedness causing trouble in smt_conv.
Re-enable TCs.

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
@intrigus-lgtm: The current master can successfully verify the test cases you have added to this PR. Can you please add the test case that triggers the issue described in this PR?

You also mention "Re-enable TCs". Which TCs are you referring to?

**Comment by intrigus-lgtm** [comment]
> @intrigus-lgtm: The current master can successfully verify the test cases you have added to this PR. Can you please add the test case that triggers the issue described in this PR?

Yeah, because it just slices and simplifies everything way.
Forgot to add this as a parameter.
If I add this, it doesn't work on master anymore.
 
> You also mention "Re-enable TCs". Which TCs are you referring to?

Re-enable in the sense that I switch from KNOWBUG to CORE.

**Comment by lucasccordeiro** [comment]
> Forgot to add this as a parameter.

Do you mean `--no-simplify`? Yes, I can now reproduce the issue. Please add this parameter to the test.desc.

> Re-enable in the sense that I switch from KNOWBUG to CORE.

I can't see on your PR which test cases changed from KNOWBUG to CORE.

**Comment by intrigus-lgtm** [comment]
> > Re-enable in the sense that I switch from KNOWBUG to CORE.
> 
> I can't see on your PR which test cases changed from KNOWBUG to CORE.

I added the testcases in the first commit of the PR as KNOWNBUG and now switched them to CORE in the last commit of this PR.

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @intrigus-lgtm.

**Comment by lucasccordeiro** [comment]
@intrigus-lgtm: could you please check why our CI is failing?

**Comment by intrigus-lgtm** [comment]
> @intrigus-lgtm: could you please check why our CI is failing?

I guess it's related to different data width sizes on windows...

**Review by brcfarias — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
>I guess it's related to different data width sizes on windows...

@intrigus-lgtm : could you please check this issue so we can merge your PR?

**Review by mikhailramalho — APPROVED** [review]
LGTM

**Comment by lucasccordeiro** [comment]
@intrigus-lgtm: Can I ask you whether you had a chance to fix the failing regression tests?

**Comment by intrigus-lgtm** [comment]
> @intrigus-lgtm: Can I ask you whether you had a chance to fix the failing regression tests?

The test failure was caused by fixing typos and spelling everywhere, because I did not yet have those commits on my branch, so I was expecting the wrong text in the test output :laughing: 

Should work now.

**Comment by lucasccordeiro** [comment]
@intrigus-lgtm: There is still one test case failing here :-)

````
The following tests FAILED:
	747 - regression/esbmc/ub_08_shift_left_mixed_op_types_fail (Failed) esbmc regression
Errors while running CTest
````

**Comment by intrigus-lgtm** [comment]
> @intrigus-lgtm: There is still one test case failing here :-)
> 
> ```
> The following tests FAILED:
> 	747 - regression/esbmc/ub_08_shift_left_mixed_op_types_fail (Failed) esbmc regression
> Errors while running CTest
> ```



> @intrigus-lgtm: There is still one test case failing here :-)
> 
> ```
> The following tests FAILED:
> 	747 - regression/esbmc/ub_08_shift_left_mixed_op_types_fail (Failed) esbmc regression
> Errors while running CTest
> ```

Hmm, I added an extra line so that should have caused changes in the test output I guess?
But then why only on Windows...

Pushed a tentative fix.

**Comment by lucasccordeiro** [comment]
> Pushed a tentative fix.

Can you simplify the output?

**Comment by lucasccordeiro** [comment]
@intrigus-lgtm: is there some chance to get this PR completed? :-) I would suggest simplifying the output of your test case.

**Comment by intrigus-lgtm** [comment]
> @intrigus-lgtm: is there some chance to get this PR completed? :-) I would suggest simplifying the output of your test case.

I'll try tomorrow or later today.

**Comment by lucasccordeiro** [comment]
@intrigus-lgtm: I hope you're okay with my simplified output of your test case. Your PR solves an important issue in our SMT backend.

**Comment by intrigus-lgtm** [comment]
> @intrigus-lgtm: I hope you're okay with my simplified output of your test case. Your PR solves an important issue in our SMT backend.

:+1:

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @intrigus-lgtm.

**Pull request merged**
