### PR TITLE
[cpp-frontend] Fix segfault on virtual methods 

### LINKED ISSUE #924: [C++ Verification] Segfault verifying program containing `new`
I'm getting a segmentation fault when running ESBMC on
```c++
#include <memory>

int main()
{
	int *p = new int;
}
```

### PR DESCRIPTION
**Pull request by brcfarias**
Fixes #924

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
The following tests FAILED:
	2136 - regression/esbmc-cpp/polymorphism_bringup/polymorphism_common_error_3 (Failed)
Errors while running CTest
Error: Process completed with exit code 8.

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
@brcfarias : could you please check the regression test that is failing?

**Comment by kunjsong01** [comment]
`2137 - regression/esbmc-cpp/polymorphism_bringup/polymorphism_common_error_3 (Failed)`

This test case tries to instantiate a base class that contains a virtual method without definition. The linker reports an error in this case.

I reckon we can probably disable the failed test case in CI, as it doesn't do much in a sense that who would verify a program that doesn't link?

**Comment by kunjsong01** [comment]
Bruno and I discussed offline. That was an old TC from the regression suite. 
just disable that TC then we can push this patch. @lucasccordeiro what do you think?

**Comment by lucasccordeiro** [comment]
Fine by me ;-)

**Review by lucasccordeiro — APPROVED** [review]

**Review by kunjsong01 — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Many thanks, @brcfarias.

**Pull request merged**
