### PR TITLE
[libm] Rough Float Operational Models

### PR DESCRIPTION
**Pull request by emanino**
This PR:
- introduces a few extra operational models in src/c2goto/library/libm/
- focuses on (very) rough approximations of mathematical functions
- either piece-wise linear or first-order Pade' approximants
- with the goal of solving some of the new neural net benchmarks

### CODE REVIEW

**Comment by fbrausse** [comment]
I've merged the current version (https://github.com/esbmc/esbmc/pull/1499/commits/c69c65874a49bf6faf5148743805e99e50b91fbd) into #1455; if there are any important changes here, please let me know.

**Comment by fbrausse** [comment]
As the SV-COMP'24 version of ESBMC is final, it's unlikely this PR will ever get merged into the svcomp24 branch. :) Shall we close this? We can continue experiments with the NNs outside of this PR, I guess.

**Comment by emanino** [comment]
> As the SV-COMP'24 version of ESBMC is final, it's unlikely this PR will ever get merged into the svcomp24 branch. :) Shall we close this? We can continue experiments with the NNs outside of this PR, I guess.

Agreed :-)

**Comment by lucasccordeiro** [comment]
I am fine with this suggestion.

**Pull request closed without merging**
