### PR TITLE
[dereference] more union-related fixes

### PR DESCRIPTION
**Pull request by fbrausse**
This PR addresses #639 (using @rafaelsamenezes' solution) and #716. I'll start an SV-COMP benchmarks run as soon as the CI finished.

### CODE REVIEW

**Review by rafaelsamenezes — APPROVED** [review]

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
@fbrausse: Can I ask you to add regression tests that produce "VERIFICATION FAILED"?

**Review by mikhailramalho — APPROVED** [review]
LGTM, we can merge it if there aren't new regressions on SV-COMP.

**Comment by fbrausse** [comment]
stats diff: https://github.com/esbmc/esbmc/pull/717/commits/3fd87fc263136277ae7f302af8e2900c5e8420ef
detailed diff:
- [unreach-call](https://fbrausse.github.io/esbmc/svcomp/diff-old-new/unreach-call/results.2022-06-01_14-09-28.diff.html)

In particular, one `unknown` got solved correctly now but 2 fast-ish correct ones now time out. I'm looking into the reasons.

**Comment by fbrausse** [comment]
The 2 fast-ish ones are `pthread-deagle/circular_buffer_{bad,good}`. In a Debug build they both fail with `master` and this PR  at the same place https://github.com/esbmc/esbmc/blob/eff35eb1700838c5af8d619a70b6910ac84d4c0a/src/irep2/irep2_type.cpp#L266-L272 where `comp` is `"__lock"` and `name` is `"pthread_mutex_t"`. Thus the error did exist before, it just happened to work because our c2goto lib's struct layout has `__lock` as the first member of `pthread_mutex_t` - same as in the memory layout of the preprocessed SV-COMP .i file. However, in the .i it looks like
```c
struct __pthread_mutex_s
{
  int __lock;
  unsigned int __count;
  int __owner;
  unsigned int __nusers;
  int __kind;
  short __spins;
  short __elision;
  __pthread_list_t __list;
};
[...]
typedef union
{
  struct __pthread_mutex_s __data;
  char __size[40];
  long int __align;
} pthread_mutex_t;
```
and there it is not member of largest size (that would be `__data`). That's why this change showed the different behaviour.

Again, this is not a new error, it is just showing now. The cause lies in the preprocessing SV-COMP does. A merge request explaining this problem and giving a solution has been opened but not been acted upon: https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/merge_requests/1359

**Comment by fbrausse** [comment]
PS: SV-COMP's `.c` sources corresponding to the `.i` work fine in both Debug and Release, as well as `master` and this PR.

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Pull request merged**
