### PR TITLE
[WiP] Changed smt_cache_entryt parameters

### PR DESCRIPTION
**Pull request by vanderson-rocha**
I created this PR just to raise a question: On line 244, wouldn't the correct be **smt_cache_entryt e = {expr, side2, ctx_level};**?

### CODE REVIEW

**Comment by mikhailramalho** [comment]
You might have a point here, but I think we need to insert three entries to the cache:
```
smt_astt smt_convt::convert_assign(const expr2tc &expr)
{
  const equality2t &eq = to_equality2t(expr);
  smt_astt side1 = convert_ast(eq.side_1);
  smt_astt side2 = convert_ast(eq.side_2);
  smt_astt equality = mk_eq(side1, side2);

  // Put that into the smt cache, thus preserving the assigned symbols value.
  // IMPORTANT: the cache is now a fundemental part of how some flatteners work,
  // in that one can chose to create a set of expressions and their ASTs, then
  // store them in the cache, rather than have a more sophisticated conversion.
  smt_cache.insert({eq.side_1, side1, ctx_level});
  smt_cache.insert({eq.side_2, side2, ctx_level});
  smt_cache.insert({expr, eq, ctx_level});

  assert_ast(equality);
  return side2;
}
```

Could you test this?

**Comment by vanderson-rocha** [comment]
Hi. @mikhailramalho 

The execution of **smt_cache.insert({eq.side_1, side1, ctx_level});** and **smt_cache.insert({eq.side_2, side2, ctx_level});** already occurs in https://github.com/esbmc/esbmc/blob/master/src/solvers/smt/smt_conv.cpp#L1094, when it call **convert_ast(eq.side_1);** and **convert_ast(eq.side_2);** respectively.

The execution of **smt_astt equality = mk_eq(side1, side2);** and **assert_ast(equality);** is the same as side2->assign(this, side1); in https://github.com/esbmc/esbmc/blob/master/src/solvers/smt/smt_conv.cpp#L238 and can be verified at https://github.com/esbmc/esbmc/blob/master/src/solvers/smt/smt_conv.cpp#L2473. However, instead of being side_1 == side_2, it returns side_2 == side_1

**Comment by mikhailramalho** [comment]
Hi Vanderson, sorry the delay.

You're right about the sides, we don't need to change that, however, I think the right change should be:
```
-  smt_cache_entryt e = {eq.side_1, side1, ctx_level};
+  smt_cache_entryt e = {eq.side_1, side2, ctx_level};
```
So it works like a constant propagation: we are encoding that side1 == side2, so whenever we see side1 from this point it can be replaced by side2.

**Comment by lucasccordeiro** [comment]
@vanderson-rocha: could you please try to run this change as suggested by @mikhailramalho?

**Comment by vanderson-rocha** [comment]
@mikhailramalho, the code **side2->assign(this, side1)** does not change value of side2 variable. So, I believe, it is necessary to do something like this:

smt_astt equality = mk_eq(side2, side1);
smt_cache_entryt e = {eq.side_1, equality, ctx_level};

You understood me?

**Comment by mikhailramalho** [comment]
The problem with this:
```
smt_astt equality = mk_eq(side2, side1);
smt_cache_entryt e = {eq.side_1, equality, ctx_level};
```
is that whenever we get `eq.side_1`, it will be replaced with the equality. Consider the following program:
```
int x = 3;
int y = 3;
assert(x == y);
int z = x;
```
the line`smt_cache_entryt e = {eq.side_1, equality, ctx_level};` will replace `x` by `x == y` in your example, so the program will become:
```
int x = 3;
int y = 3;
assert(x == y);
int z = (x == y);
```

**Comment by vanderson-rocha** [comment]
@mikhailramalho, you are right. @lucasccordeiro, I tested the solution presented by @mikhailramalho , and it works for me.

**Comment by lucasccordeiro** [comment]
@vanderson-rocha: Could you please push this change suggested by @mikhailramalho? Then we can review and merge your PR.

**Comment by vanderson-rocha** [comment]
People. I did something wrong when merged this branch with master. Can we close this PR and open another one for this correction?

**Comment by lucasccordeiro** [comment]
Yes! Can you create this new PR?

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/254.

**Pull request closed without merging**
