### PR TITLE
Fix wrong line number in counterexamples

### LINKED ISSUE #381: Print wrong line number in the counterexample due to pre-processing (frontend issue?)
ESBMC prints the incorrect line number in the counterexample. In particular, it shows `arithmetic overflow` on line 2 (the define statement) instead of line 7 (uint16_t b = a << 16;).

```
#ifndef uint16_t
#define uint16_t unsigned short
#endif
int main() {
  uint16_t a = 0xFFFF;
  uint16_t b = a << 16;
  return 0; 
}
```

```
Counterexample:

State 1 file test_basic_checks.c line 2 function main thread 0
----------------------------------------------------
Violated property:
  file test_basic_checks.c line 2 function main
  arithmetic overflow on shl
  !overflow("shl", (signed int)a, 16)

VERIFICATION FAILED
```

### PR DESCRIPTION
**Pull request by ericksonalves**
This should close #381

### CODE REVIEW

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
This is a good fix for ESBMC! We might get some additional witnesses validated in SV-COMP :-)

Can I ask you to add the regression test from https://github.com/esbmc/esbmc/issues/381?

You can add a test desc as:
```
CORE
main.c

^file main.c line 7 function main$
```

**Comment by ericksonalves** [comment]
> This is a good fix for ESBMC! We might get some additional witnesses validated in SV-COMP :-)
> 
> Can I ask you to add the regression test from #381?
> 
> You can add a test desc as:
> 
> ```
> CORE
> main.c
> 
> ^file main.c line 7 function main$
> ```

Done.

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Review by rafaelsamenezes — APPROVED** [review]
LGTM

**Comment by mikhailramalho** [comment]
We just have to make sure it works with pre processed files + those
location pragmas. Did you test it?

**Comment by ericksonalves** [comment]
I am sharing the results of a test I performed with a pre-processed file.

Pre-processing:
```console
gcc -E 381.c > pre-381.i
esbmc --overflow-check pre-381.i
```

Output:
```
Counterexample:

State 1 file 381.c line 6 function main thread 0
----------------------------------------------------
Violated property:
  file 381.c line 6 function main
  arithmetic overflow on shl
  !overflow("shl", (signed int)a, 16)


VERIFICATION FAILED
```

Only parse tree:
```
`-FunctionDecl 0x538e250 <381.c:4:1, line:8:1> line:4:5 main 'int ()'
  `-CompoundStmt 0x538e530 <col:12, line:8:1>
    |-DeclStmt 0x538e3a8 <line:5:3, col:28>
    | `-VarDecl 0x538e308 <col:3, col:22> col:18 used a 'unsigned short' cinit
    |   `-ImplicitCastExpr 0x538e390 <col:22> 'unsigned short' <IntegralCast>
    |     `-IntegerLiteral 0x538e370 <col:22> 'int' 65535
    |-DeclStmt 0x538e4e8 <line:6:3, col:29>
    | `-VarDecl 0x538e3d8 <col:3, col:27> col:18 b 'unsigned short' cinit
    |   `-ImplicitCastExpr 0x538e4d0 <col:22, col:27> 'unsigned short' <IntegralCast>
    |     `-BinaryOperator 0x538e4b0 <col:22, col:27> 'int' '<<'
    |       |-ImplicitCastExpr 0x538e498 <col:22> 'int' <IntegralCast>
    |       | `-ImplicitCastExpr 0x538e480 <col:22> 'unsigned short' <LValueToRValue>
    |       |   `-DeclRefExpr 0x538e440 <col:22> 'unsigned short' lvalue Var 0x538e308 'a' 'unsigned short'
    |       `-IntegerLiteral 0x538e460 <col:27> 'int' 16
    `-ReturnStmt 0x538e520 <line:7:3, col:10>
      `-IntegerLiteral 0x538e500 <col:10> 'int' 0
```

**Comment by lucasccordeiro** [comment]
Can you please add this test case to the PR too? i.e, the original and pre-processed program.

**Comment by mikhailramalho** [comment]
That's not what I'm talking about... I'll send an example tomorrow.

**Comment by mikhailramalho** [comment]
Here's the example:
```
#include <assert.h>

# 1 "foo.c" 1
int fail()
{
  int x = __VERIFIER_nondet_int();
  assert(x);
}

# 1 "main.c" 1

int main(int argc, char **argv) {
  fail();
}
```

Currently, esbmc returns:
```
$ esbmc main.c
ESBMC version 6.8.0 64-bit x86_64 linux
file main.c: Parsing
In file included from main.c:3:
foo.c:5:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
Converting
Generating GOTO Program
GOTO program creation time: 0.242s
GOTO program processing time: 0.001s
Starting Bounded Model Checking
Symex completed in: 0.002s (21 assignments)
Slicing time: 0.000s (removed 16 assignments)
Generated 1 VCC(s), 1 remaining after simplification (5 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.2
Encoding to solver time: 0.000s
Runtime decision procedure: 0.001s
Building error trace

Counterexample:

State 3 file foo.c line 3 function fail thread 0
----------------------------------------------------
  x = 0 (00000000 00000000 00000000 00000000)

State 4 file assert.h line 112 function fail thread 0
----------------------------------------------------
Violated property:
  file assert.h line 112 function fail
  assertion x
  (_Bool)x
```

Note the **foo.c** in the cex.

This is the expected behaviour when compiling the code (replace `__VERIFIER_nondet_int()` with `0`):
```
$ gcc main.c -g; ./a.out
a.out: foo.c:4: fail: Assertion `x' failed.
Aborted (core dumped)
```
Note the assertion failure is in foo.c, line 4.

**Comment by rafaelsamenezes** [comment]
@mikhailramalho shall we open a new issue for this corner case then?

**Comment by mikhailramalho** [comment]
This example is working today on esbmc.

My question was whether esbmc keeps the same behaviour after Erickson's
patch.

**Comment by ericksonalves** [comment]
@mikhailramalho

This is the output for my patch:
```
ESBMC version 6.8.0 64-bit x86_64 linux
file /home/ericksonalves/workspace/main.c: Parsing
In file included from /home/ericksonalves/workspace/main.c:3:
foo.c:5:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
Converting
Generating GOTO Program
GOTO program creation time: 0.133s
GOTO program processing time: 0.001s
Starting Bounded Model Checking
Symex completed in: 0.000s (18 assignments)
Slicing time: 0.000s (removed 13 assignments)
Generated 1 VCC(s), 1 remaining after simplification (5 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.1
Encoding to solver time: 0.000s
Runtime decision procedure: 0.001s
Building error trace

Counterexample:

State 3 file foo.c line 3 function fail thread 0
----------------------------------------------------
  x = 0 (00000000 00000000 00000000 00000000)

State 4 file foo.c line 4 function fail thread 0
----------------------------------------------------
Violated property:
  file foo.c line 4 function fail
  assertion x
  (_Bool)x


VERIFICATION FAILED
```

We can check the differences if compared to esbmc's current implementation:

*Current*:
```
State 4 file assert.h line 112 function fail thread 0
----------------------------------------------------
Violated property:
  file assert.h line 112 function fail
  assertion x
  (_Bool)x
```

*Patched*:
```
State 4 file foo.c line 4 function fail thread 0
----------------------------------------------------
Violated property:
  file foo.c line 4 function fail
  assertion x
  (_Bool)x
```

Basically, the violation in the cex changed from `assert.h` to `foo.c`, and its respective line number. Is that reasonable?

**Comment by lucasccordeiro** [comment]
This is an excellent patch, @ericksonalves!

**Comment by mikhailramalho** [comment]
Excellent!

**Pull request merged**
