### PR TITLE
Fix Z3 build with the Ubuntu APT packages

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
The String that comes from Z3_VERSION on apt is different from the pre-built packages.

This also sets the arm debug build to use the version from the system.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
LGTM. We could merge it once the CI is ready.

**Review by mikhailramalho — APPROVED** [review]
LGTM

**Comment by fbrausse** [comment]
It's not just Ubuntu, but depending on which build systems is/was used, see https://github.com/Z3Prover/z3/issues/2184 and https://reviews.llvm.org/D54978. I use [the same fix](https://github.com/fbrausse/esbmc/commit/a062995d75906342625304c38cfa68cf9290614c) for the Gentoo package as well as builds directly from source.

**Comment by fbrausse** [comment]
It would help me considerably if we could merge at least the first commit of this series to master. This compile issue is not apt-specific.

**Comment by rafaelsamenezes** [comment]
> It would help me considerably if we could merge at least the first commit of this series to master. This compile issue is not apt-specific.

@fbrausse I just pushed into master

**Comment by fbrausse** [comment]
Many thanks!

**Comment by rafaelsamenezes** [comment]
This is no longer needed

**Pull request closed without merging**
