### PR TITLE
[c++ verification] fixed assertion failed in string OM

### LINKED ISSUE #1664: [C++ frontend] source->type->type_id == type2t::struct_id || source->type->type_id == type2t::union_id' failed.
$esbmc main.cpp

````CPP
#include <iostream>

using std::cout;

#include <string>

using std::string;

#include <ctime>

#include <cstdlib>

void writeCookie();

int main()
{
   // write the cookie
   writeCookie();

   // output header
   cout << "Content-type: text/html\n\n";

   // output XML declaration and DOCTYPE
   cout << "<?xml version = \"1.0\"?>"
        << "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 "
        << "Transitional//EN\"";

   // output html element and its contents
   cout << "<html xmlns = \"http://www.w3.org/1999/xhtml\">"
        << "<head><title>Logged Out</title></head>"
        << "<body>"
        << "<center><p>You are now logged out<br>"
        << "You will be billed accordingly<br>"
        << "To login again, "
        << "<a href=\"/cgi-bin/login.cgi\">click here</a>"
        << "</body></html>\n";

   return 0;

} // end main

// function to write cookie
void writeCookie()
{
   // string containing expiration date
   string expires = "Friday, 14-MAY-10 16:00:00 GMT";

   // set cookie
   cout << "set-cookie: CART=; expires=" << expires
        << "; path=\n";

} // end writeCookie
````

### PR DESCRIPTION
**Pull request by XLiZHI**

### CODE REVIEW

**Comment by XLiZHI** [comment]
> Error: Process completed with exit code 143.

~~It seems runner stopped working, but no failure occurs in regression. Maybe it takes up too many resources.~~

The issue is in [esbmc-cpp/list/list_sort](https://github.com/esbmc/esbmc/blob/master/regression/esbmc-cpp/list/list_sort/main.cpp) and [esbmc-cpp/list/list_sort_bug](https://github.com/esbmc/esbmc/blob/master/regression/esbmc-cpp/list/list_sort_bug/main.cpp)  (previously marked as `KNOWBUG` because string OM assertion failed)

It looks like the problem occurs in an infinite Unwinding loop, I temporarily modify flag to pass CI.

**Comment by lucasccordeiro** [comment]
Well done, @XLiZHI.

This PR fixes 218 regression tests! I believe this is the PR that enables the largest number of test cases in ESBMC history :-)

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
@rafaelsamenezes: do you have some suggestions on how to improve our CI to support the verification of the C++ regression suite?

**Comment by lucasccordeiro** [comment]
> [esbmc-cpp/list/list_sort](https://github.com/esbmc/esbmc/blob/master/regression/esbmc-cpp/list/list_sort/main.cpp) and [esbmc-cpp/list/list_sort_bug](https://github.com/esbmc/esbmc/blob/master/regression/esbmc-cpp/list/list_sort_bug/main.cpp) (previously marked as KNOWBUG because string OM assertion failed)

> It looks like the problem occurs in an infinite Unwinding loop, I temporarily modify flag to pass CI.

Nice. Let's wait for CI now ;-)

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @XLiZHI.

**Pull request merged**
