### PR TITLE
[WIP] Camada support

### PR DESCRIPTION
**Pull request by mikhailramalho**
Work-in-progress support for camada (https://github.com/mikhailramalho/camada).

Should massively simplify ESBMC's backend.

### CODE REVIEW

**Comment by rafaelsamenezes** [comment]
Is there a way to make static builds of camada and release them? This would simplify a lot of the build process of ESBMC.

**Comment by mikhailramalho** [comment]
> Is there a way to make static builds of camada and release them? This would simplify a lot of the build process of ESBMC.

Do you mean a static library that contains symbols and code from all the other libraries? Currently, while you can build camada statically, you'll still need all the other dependencies when linking against camada.

The problem is that there is no native support in CMake to repack the libraries. I actually found a few scripts that claim that can do that but I didn't manage to get it to work... Here's an in-depth explanation of the problem and a script to bundle the libs:

https://cristianadam.eu/20190501/bundling-together-static-libraries-with-cmake/
https://gist.github.com/cristianadam/ef920342939a89fae3e8a85ca9459b49

But when I tried, I remember not being able to install the lib (CMake complained about IMPORTED libs?). Maybe I'm just not that well-versed in CMake...

Patches are welcome!

**Comment by rafaelsamenezes** [comment]
> Do you mean a static library that contains symbols and code from all the other libraries? Currently, while you can build camada statically, you'll still need all the other dependencies when linking against camada.

I mean remove the dependencies of external solvers from ESBMC and only use camada. If we don't use any specific function from a solver it should be fine, right?

**Comment by mikhailramalho** [comment]
>
>
> I mean remove the dependencies of external solvers from ESBMC and only use
> camada. If we don't use any specific function from a solver it should be
> fine, right?
>
>
>
Not really, because you'll need the solver libraries for linking.


-- 

Mikhail Ramalho.

**Pull request closed without merging**
