### PR TITLE
[dereference] fix #704

### LINKED ISSUE #704: Seg fault with union, array, struct, and loop
Segmentation fault with the below example

``` c
typedef union uni_s {
  int data;
} uni_t;

typedef struct arr_s {
  int data[2];
} arr_t;

typedef struct top_s {
  uni_t u; 
  arr_t a;
} top_s;

int main() {
  top_s t;
  arr_t* a = &t.a;

  for (int i = 0; i < 2 ; i++) {
    a->data[i] = i;
  }

  return 0;
}
``` 

Version: ESBMC version 6.9.0 64-bit x86_64 linux
(Current master `d206ccc8dfdb026d3ff115abb2f30fe11e156111` )

### PR DESCRIPTION
**Pull request by fbrausse**

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
@fbrausse: it seems that there is one test case that fails with this PR:

```
The following tests FAILED:
	290 - regression/esbmc-unix2/14_popl20-figure1 (Failed)
Errors while running CTest
```

**Comment by fbrausse** [comment]
@lucasccordeiro This seems to have been a segfault caused maybe by spurious memory shortage.

**Comment by mikhailramalho** [comment]
Can you run it on SV-Comp before merging?

**Review by lucasccordeiro — APPROVED** [review]
Overall, this PR looks okay to me.

Shall we run this PR over the SV-COMP benchmarks before we merge it?

**Comment by lucasccordeiro** [comment]
> @lucasccordeiro This seems to have been a segfault caused maybe by spurious memory shortage.

Thanks, @fbrausse.

**Comment by fbrausse** [comment]
[This branch](https://github.com/esbmc/esbmc/actions/runs/2331786965):
```
Statistics:          15648 Files
  correct:            8448
    correct true:     5130
    correct false:    3318
  incorrect:            53
    incorrect true:     24
    incorrect false:    29
  unknown:            7147
  Score:             12346 (max: 25567)
```

**Comment by lucasccordeiro** [comment]
Thanks, @fbrausse.

Can I ask you to rebase this branch?

Rafael has run the master branch over the SV-COMP benchmarks but without using the new concurrency flag (i.e., `--no-goto-merge`, see https://github.com/esbmc/esbmc/pull/696):

Master branch:
```
Statistics:          15648 Files
  correct:            8155
    correct true:     5078
    correct false:    3077
  incorrect:            62
    incorrect true:     24
    incorrect false:    38
  unknown:            7431
  Score:             11857 (max: 25567)
```

The results of this PR look much better than the master. In any case, I would still recommend running ESBMC over the master using the same wrapper script.

**Comment by fbrausse** [comment]
I've started [another run](https://github.com/esbmc/esbmc/actions/runs/2339312424) on current master, with the same wrapper script. Also we now record the latest known SV-COMP statistics for 300s timeout in `scripts/competitions/svcomp/stats-300s.txt`.

**Comment by lucasccordeiro** [comment]
> I've started [another run](https://github.com/esbmc/esbmc/actions/runs/2339312424) on current master, with the same wrapper script. Also we now record the latest known SV-COMP statistics for 300s timeout in scripts/competitions/svcomp/stats-300s.txt.

This is an excellent idea/initiative!

**Comment by fbrausse** [comment]
[master](https://github.com/esbmc/esbmc/actions/runs/2339312424):
```
Statistics:          15648 Files
  correct:            8438
    correct true:     5124
    correct false:    3314
  incorrect:            53
    incorrect true:     24
    incorrect false:    29
  unknown:            7157
  Score:             12330 (max: 25567)
```
[This PR](https://github.com/esbmc/esbmc/actions/runs/2331786965):
```
Statistics:          15648 Files
  correct:            8448
    correct true:     5130
    correct false:    3318
  incorrect:            53
    incorrect true:     24
    incorrect false:    29
  unknown:            7147
  Score:             12346 (max: 25567)
```

**Comment by lucasccordeiro** [comment]
Many thanks, @fbrausse.

**Comment by lucasccordeiro** [comment]
BTW, Excellent PR!

**Pull request merged**
