### PR TITLE
[NFC] Improvement to messages

### PR DESCRIPTION
**Pull request by mikhailramalho**
This PR is part of a series of PRs derived from https://github.com/esbmc/esbmc/pull/876: although that PR was accepted, it's been a nightmare to rebase, so I decided to split it.

This PR improves some messages printed by esbmc: 
* Removed places where we were printing "error: " twice in the error message
* Fixed inconsistencies when printing warnings, now we always prepend the message with "Warning:"
* Don't scream when printing k-induction stuff

I didn't fix anything in the old frontends for obvious reasons.

### CODE REVIEW

**Comment by mikhailramalho** [comment]
@ChenfengWei1 you seem to have worked on the ambiguous main function in the solidity frontend, which is now broken with this PR. Care to share some light on the issue?

**Comment by ChenfengWei0** [comment]
Sorry for my late reply.

Previously, when meeting an ambiguous symbol, we report it and continue running. In this PR, ESBMC will report and then terminate.

For example:
- `--sol main.sol main.solast --function empty`
```solidity
contract A {
    function empty() public {}
}

contract B {
    function empty() public {}
}
```

- Before this PR
```
...
ERROR: warning: main symbol `empty' is ambiguous
Generating GOTO Program
GOTO program creation time: 0.252s
GOTO program processing time: 0.000s
Starting Bounded Model Checking
Symex completed in: 0.001s (11 assignments)
Slicing time: 0.000s (removed 11 assignments)
Generated 0 VCC(s), 0 remaining after simplification (0 assignments)
BMC program time: 0.001s

VERIFICATION SUCCESSFUL
```

In this case, ESBMC will only verify the first `empty()`, the one inside contract A. If we put a false assert in `A:empty()`:

```
ERROR: warning: main symbol `empty' is ambiguous
...

[Counterexample]


State 1 file ex20.sol line 5 function empty thread 0
----------------------------------------------------
Violated property:
  file ex20.sol line 5 function empty
  assertion
  0 == 1
```

I think some solidity regression tests are relying on this feature.

- This PR
```
ERROR: main symbol `empty' is ambiguous
ERROR: CONVERSION ERROR
```

@mikhailramalho May I ask if you could change the failed regression tests to `THOROUGH` and leave them to me to fix? Or you could change the expected result to `ERROR: CONVERSION ERROR`.

**Comment by mikhailramalho** [comment]
In your example, only one of the empty functions will be verified...

Is the program you showed valid:
```
contract A {
    function empty() public {}
}

contract B {
    function empty() public {}
}
```
I'm not sure how we can force esbmc to verify both functions if we don't pass its full scoped name (e.g., A::empty or B::empty).

I'll change the program to THOROUGH as suggested.

**Comment by ChenfengWei0** [comment]
I have changed the failed Solidity regression tests via #1446.

**Comment by fbrausse** [comment]
"Files changed: 0". LGTM. ;)

**Comment by fbrausse** [comment]
> "Files changed: 0". LGTM. ;)

Is there anything going to happen with this now-empty PR or can we close it?

**Comment by mikhailramalho** [comment]
I didn't realize this was merged, closing it now.

**Pull request closed without merging**
