### PR TITLE
Fix recursive structs. Fixes #1776

### LINKED ISSUE #1776: [C++ Frontend] Recursive, extending structs via pointers: `Assertion 'type.id() == typet::t_struct || type.id() == typet::t_union || type.id() == typet::t_class' failed.`
`a` refers to `b` via a pointer.
So when we try to parse the `a`, we will notice the field `c` with the type `b`.
Then we will try to get the type for `b`.
However, now `b` will try to get the type for its base class: `a`.
And now we will call `to_struct_type(class_a)` which will fail, because `a` is not yet a complete type.

I tried a bit to fix this, but wasn't very successful so far.

I think @fbrausse was working on recursive structs last time, so maybe he has an idea.

```cpp
class a;
class b;
class a {
  b *c;
};
class b : a {};
```

```shell
esbmc: esbmc/src/util/std_types.h:251: struct_typet& to_struct_type(typet&): Assertion `type.id() == typet::t_struct || type.id() == typet::t_union || type.id() == typet::t_class' failed.
```

### PR DESCRIPTION
**Pull request by intrigus-lgtm**
Previously, esbmc would try to parse fields of forward declarations.
Consider this code:
```cpp
class a; // https://github.com/esbmc/esbmc/pull/1
class b; // https://github.com/esbmc/esbmc/issues/2
class a { // https://github.com/esbmc/esbmc/issues/3
  b *c;
};
class b : a {}; // https://github.com/esbmc/esbmc/issues/4
```
When parsing https://github.com/esbmc/esbmc/pull/1, clang would resolve the actual definition for us.
This means that we would skip ahead to https://github.com/esbmc/esbmc/issues/3 and try to parse the fields
of `a`. When doing this, we will encounter `b` and try to get a type
for it. This will ultimately fail, because we are still defining `a`,
but `b` extends `a` and so `a` must be a _complete_ type which it is
not at that point.

We can avoid this problem by _not_ continuing to parse fields if the
declaration is not a complete one.
When now parsing https://github.com/esbmc/esbmc/pull/1, we would not skip ahead to https://github.com/esbmc/esbmc/issues/3 anymore.
Similarly, when parsing https://github.com/esbmc/esbmc/issues/2, we would not skip ahead to https://github.com/esbmc/esbmc/issues/4 anymore.
There is still a slight problem:
when parsing https://github.com/esbmc/esbmc/issues/3 we would however still have a problem.
We would try to get a type for `b` again, which would then fail
again, because `a` is not yet complete.

This problem is easily solved, by not recording structs in the
context if we already have a symbol there for it.

### CODE REVIEW

**Review by fbrausse — APPROVED** [review]
Thanks, LGTM. I also looked into it today and came to the same conclusion: follow the declaration/definition style of the Clang AST / the source code. I just didn't want to make the call in get_type() dependent on whether we already had the symbol and was looking for a Clang API that would let me tell the difference. Unsuccessfully. So I guess I'm fine with it, thanks again.

**Comment by fbrausse** [comment]
Actually, maybe it makes sense to add a comment to this case in get_type():

-----------------------
This only happens when the definition of the record type is part of a declaration of a field / variable, as for the anonymous union in, e.g., /usr/include/bits/types/__mbstate_t.h
```c
typedef struct
{
  int __count;
  union
  {
    __WINT_TYPE__ __wch;
    char __wchb[4];
  } __value;		/* Value so far.  */
} __mbstate_t;
```
or in c2goto/library/libm/musl/libm.h
```c
#define asuint(f) ((union{float _f; uint32_t _i;}){f})._i
```
-----------------------

I still think there is a reason why this irregularity happens, which may have to do with the implementation of get_var(), but I can't pinpoint it, yet.

**Comment by intrigus-lgtm** [comment]
Unfortunately this is still not a complete fix :(

```cpp
template <typename> struct a;
struct b;
template <typename> struct a { b *c; };
struct b : a<int> {};
```
(Basically the original testcase but this time with templates)

Fails again with 
```
Assertion `type.id() == typet::t_struct || type.id() == typet::t_union || type.id() == typet::t_class' failed.
```

**Comment by fbrausse** [comment]
> (Basically the original testcase but this time with templates)

I think it's worth trying to remove the get_struct_union_class() calls in the C++ frontend, specifically, in get_base_map(). There are two of them and - if we follow the decl/def style of the AST correctly - none should be necessary: you can't derive from an incomplete base class.

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @intrigus-lgtm.

**Comment by lucasccordeiro** [comment]
@intrigus-lgtm: you can consider submitting another PR once you handle the new issue mentioned here.

**Pull request merged**
