### PR TITLE
[build] fix compilation with Clang 19

### PR DESCRIPTION
**Pull request by ligurio**
```
  185 |       comp.set_is_unnamed_bitfield(fd.isUnnamedBitfield());
      |                                       ^~~~~~~~~~~~~~~~~
      |                                       isUnnamedBitField
```

### CODE REVIEW

**Comment by mikhailramalho** [comment]
What version of clang are you using?

**Comment by ligurio** [comment]
> What version of clang are you using?

Clang 19

**Comment by XLiZHI** [comment]
We currently support up to Clang 16. As far as I know this API change was in the release of Clang 17. If you want to use a higher version, Maybe this will work:
```
#if LLVM_VERSION_MAJOR > 16
#  define isUnnamedBitField(fd) fd->isUnnamedBitField()
#else
#  define isUnnamedBitField(fd) fd->isUnnamedBitfield()
#endif
....

#undef isUnnamedBitField(fd)
```

**Comment by mikhailramalho** [comment]
or better still do:
```
#if LLVM_VERSION_MAJOR > 16
      comp.set_is_unnamed_bitfield(fd.isUnnamedBitField());
#else
      comp.set_is_unnamed_bitfield(fd.isUnnamedBitfield());
#endif
```

**Comment by ligurio** [comment]
The patch updated and force-pushed.

Also, I would a check for the latest support Clang version to `CMakeLists.txt` and show a warning if a version is not in the range of supported versions. What do you think?

**Comment by lucasccordeiro** [comment]
Your suggestion to print a warning message looks good, @ligurio.

**Comment by ligurio** [comment]
> Your suggestion to print a warning message looks good, @ligurio.

@lucasccordeiro, added

**Comment by lucasccordeiro** [comment]
Many thanks, @ligurio.

**Review by lucasccordeiro — APPROVED** [review]

**Review by XLiZHI — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @ligurio.

**Comment by mikhailramalho** [comment]
The cmake part should be the other way around, the minimum version is 16, and we should abort cmake config when it's lower than that

**Comment by lucasccordeiro** [comment]
> The cmake part should be the other way around, the minimum version is 16, and we should abort cmake config when it's lower than that

I'm unsure here. As far as I'm aware, we have tested until v16. We didn't test the recent versions (e.g., v19). Please correct me if I'm wrong here.

**Comment by XLiZHI** [comment]
> I'm unsure here. As far as I'm aware, we have tested until v16. We didn't test the recent versions (e.g., v19). Please correct me if I'm wrong here.

Our minimum LLVM version should be 13, which is the latest version of Clang-CHERI. But since our windows version is still using clang 11 (we need to build the windows version manually), we can't remove it yet.

**Comment by mikhailramalho** [comment]
> > The cmake part should be the other way around, the minimum version is 16, and we should abort cmake config when it's lower than that
> 
> I'm unsure here. As far as I'm aware, we have tested until v16. We didn't test the recent versions (e.g., v19). Please correct me if I'm wrong here.

I've been using clang 18 for a while now, and this patch breaks the compilation. This change was introduced for clang 19, not 18.

I find it weird that we now decided to support up to a maximum version rather than a minimum. It was never like that before. We should incentivize people to use newer versions of the lib since (more often than not) they improve performance, add new features, and include fixes.

**Comment by lucasccordeiro** [comment]
Dear @mikhailramalho,

> I've been using clang 18 for a while now, and this patch breaks the compilation. This change was introduced for clang 19, not 18.

That's why @ligurio added a warning message to indicate if a version is not in the range of supported versions.

> We should incentivize people to use newer versions of the lib since (more often than not) they improve performance, add new features, and include fixes.

I fully agree that we should motivate the users to use the latest lib versions. However, we should also check for regression to avoid what happened in your environment, i.e., the proposed patch broke your compilation.

**Comment by rafaelsamenezes** [comment]
> > > The cmake part should be the other way around, the minimum version is 16, and we should abort cmake config when it's lower than that
> > 
> > 
> > I'm unsure here. As far as I'm aware, we have tested until v16. We didn't test the recent versions (e.g., v19). Please correct me if I'm wrong here.
> 
> I've been using clang 18 for a while now, and this patch breaks the compilation. This change was introduced for clang 19, not 18.
> 
> I find it weird that we now decided to support up to a maximum version rather than a minimum. It was never like that before. We should incentivize people to use newer versions of the lib since (more often than not) they improve performance, add new features, and include fixes.

Are you reffering to this line: ``#if LLVM_VERSION_MAJOR > 16`

Which should be 18?

**Pull request merged**
