### PR TITLE
Interval analysis now inverts boolean correctly

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
Solves #1565

The original issue was that the `invert_bool` function expected an interval to be a singleton i.e., [0,0] or [1,1]. If the interval was not that, it would assume that it was (-inf,+inf). This resulted in invert bool for [1,+inf) return [1, +inf) which is wrong.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Review by fbrausse — APPROVED** [review]
Yes. This looks right to me.

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @rafaelsamenezes.

**Comment by rafaelsamenezes** [comment]
Master (120s):

```
Statistics:          23805 Files
  correct:           15105
    correct true:     8545
    correct false:    6560
  incorrect:            45
    incorrect true:     17
    incorrect false:    28
  unknown:            8655
  Score:             22658 (max: 38482
```

This PR (120s):

```
Statistics:          23805 Files
  correct:           15107
    correct true:     8542
    correct false:    6565
  incorrect:            45
    incorrect true:     17
    incorrect false:    28
  unknown:            8653
  Score:             22657 (max: 38482)
```

**Pull request merged**
