### PR TITLE
[Concurrency] negative number of assignments fix

### PR DESCRIPTION
**Pull request by Anthonysdu**
This PR is to fix the issue #1387

### CODE REVIEW

**Comment by Anthonysdu** [comment]
Trace now:

```
Thread interleavings 4494
Symex completed in: 0.001s (126 assignments)
Slicing time: 0.000s (removed 123 assignments)
Generated 29 VCC(s), 1 remaining after simplification (3 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.1
Runtime decision procedure: 0.000s
BMC program time: 0.001s
Thread interleavings 4495
Symex completed in: 0.000s (126 assignments)
Slicing time: 0.000s (removed 123 assignments)
Generated 29 VCC(s), 1 remaining after simplification (3 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.1
Runtime decision procedure: 0.000s
BMC program time: 0.001s
Thread interleavings 4496
Symex completed in: 0.000s (126 assignments)
Slicing time: 0.000s (removed 123 assignments)
Generated 29 VCC(s), 1 remaining after simplification (3 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.000s
Solving with solver Boolector 3.2.1
Runtime decision procedure: 0.000s
```

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @Anthonysdu.

**Comment by fbrausse** [comment]
Let's do this for `simple_slice::run()` and `claim_slicer::run()` as well.

**Review by fbrausse — APPROVED** [review]
LGTM.

**Pull request merged**
