### PR TITLE
Adhere to C semantics for pointer-arithmetic

### LINKED ISSUE #1401: A false positive result?
Different result for this program
```
#include <assert.h>
int main() {
    int granules[10] = {10, 20, 30, 40, 50, 60, 70, 80, 90, 100};
    unsigned long int offset = (&granules[0] + 6) - &granules[0];
    assert(offset < 8);
    return 0;
}
```

esbmc master: 
```
State 1 file main.c line 4 column 5 function main thread 0
----------------------------------------------------
  offset = (unsigned long int)((&granules[0] + 6) - &granules[0])

State 2 file main.c line 5 column 5 function main thread 0
----------------------------------------------------
Violated property:
  file main.c line 5 column 5 function main
  assertion offset < 8
  offset < 8


VERIFICATION FAILED
```
cbmc:
```
** Results:
main.c function main
[main.assertion.1] line 5 assertion offset < 8: SUCCESS
```

### PR DESCRIPTION
**Pull request by fbrausse**
Fixes #1401.

### CODE REVIEW

**Comment by Anthonysdu** [comment]
thanks @fbrausse 
but it doesn't work for structs though:

```
#include <assert.h>

struct Granule {
    int value;
};

int main() {
    struct Granule granules[10] = {
        {10}, {20}, {30}, {40}, {50}, {60}, {70}, {80}, {90}, {100}
    };

    unsigned long int offset = (&granules[0] + 6) - &granules[0];
    int n = offset;
    assert(n == 6);

    return 0;
}
```

```
State 1 file main.c line 12 column 5 function main thread 0
----------------------------------------------------
  offset = (unsigned long int)((&granules[0] + 6) - &granules[0])

State 2 file main.c line 13 column 5 function main thread 0
----------------------------------------------------
  n = 3 (00000000 00000000 00000000 00000011)

State 3 file main.c line 14 column 5 function main thread 0
----------------------------------------------------
Violated property:
  file main.c line 14 column 5 function main
  assertion n == 6
  n == 6


VERIFICATION FAILED
```

**Comment by fbrausse** [comment]
@Anthonysdu Thanks, you are right. I made a silly mistake in fixing this silly bug. Should be fine now.

**Review by lucasccordeiro — APPROVED** [review]
Thanks for submitting this PR, @fbrausse.

**Comment by lucasccordeiro** [comment]
Master branch 30s (https://github.com/esbmc/esbmc/commit/689902eb4a602257ba816cbbe7c14ef2dd7b6c68):

````
Statistics:          23805 Files
  correct:           14154
    correct true:     7810
    correct false:    6344
  incorrect:            22
    incorrect true:     7
    incorrect false:    15
  unknown:           9629
  Score:             21500 (max: 38482)

GitHub actions: https://github.com/esbmc/esbmc/actions/runs/6562903164
````

This PR for 30s (https://github.com/esbmc/esbmc/commit/abd5e5ac05459578496ffaaeda211cbabda7e1df):

````
Statistics:          23805 Files
   correct:           14107
     correct true:     7793
     correct false:    6314
   incorrect:            21
     incorrect true:      6
     incorrect false:    15
   unknown:            9677
   Score:             21468 (max: 38482)

GitHub actions: https://github.com/esbmc/esbmc/actions/runs/6565537450
````

**Comment by Anthonysdu** [comment]
LGTM

**Pull request merged**
