### PR TITLE
[multi-property] support witness generation

### PR DESCRIPTION
**Pull request by ChenfengWei0**
```sh
esbmc 1.c --generate-testcase

testcase-1.xml
testcase-2.xml
...
```

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
@ChenfengWei0: Some test cases are failing. Could you please check that?

**Comment by ChenfengWei0** [comment]
> @ChenfengWei0: Some test cases are failing. Could you please check that?

Will check

**Comment by lucasccordeiro** [comment]
Thanks for submitting this PR, @ChenfengWei0.

**Comment by lucasccordeiro** [comment]
@ChenfengWei0: could you please update our documentation at https://ssvlab.github.io/esbmc/documentation.html?

**Comment by ChenfengWei0** [comment]
> @ChenfengWei0: could you please update our documentation at https://ssvlab.github.io/esbmc/documentation.html?

Sure. I will update it together with the branch coverage.

**Pull request merged**
