### PR TITLE
[headers]Named implicit trivial ctor

### PR DESCRIPTION
**Pull request by XLiZHI**
Fixed error with uname implicit trivial constructor from Clang C++

https://github.com/esbmc/esbmc/issues/931#issuecomment-1470541439

Added a regression test for pthread.h

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]

**Review by kunjsong01 — CHANGES_REQUESTED** [review]
Since the OM fix in this PR is an alternative to the clang-cpp-frontend patch PR https://github.com/esbmc/esbmc/pull/933 for issue https://github.com/esbmc/esbmc/issues/931,  I believe we first need to revert https://github.com/esbmc/esbmc/pull/933 then test whether the OM fix in this PR resolves the issue.

we want to make sure the new test case added in this PR still passes after reverting https://github.com/esbmc/esbmc/pull/933. 

Also, `esbmc-cpp/OM_sanity_checks` contains only test cases for C++ OMs from `src/cpp/library`. `pthread.h` is not specific to C++. I reckon `regression/esbmc` is the place to add the corresponding test cases.

**Review by kunjsong01 — APPROVED** [review]
LGTM

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
> Since the OM fix in this PR is an alternative to the clang-cpp-frontend patch PR https://github.com/esbmc/esbmc/pull/933 for issue https://github.com/esbmc/esbmc/issues/931, I believe we first need to revert https://github.com/esbmc/esbmc/pull/933 then test whether the OM fix in this PR resolves the issue.

@kunjsong01: Should ESBMC crash because of a wrong OM? We should either fail in the parser or reject the AST. The fix to the OM is okay, but I don't think we should remove the previous fix, which prevents the crash in ESBMC.

**Comment by kunjsong01** [comment]
> > Since the OM fix in this PR is an alternative to the clang-cpp-frontend patch PR #933 for issue #931, I believe we first need to revert #933 then test whether the OM fix in this PR resolves the issue.
> 
> @kunjsong01: Should ESBMC crash because of a wrong OM? We should either fail in the parser or reject the AST. The fix to the OM is okay, but I don't think we should remove the previous fix, which prevents the crash in ESBMC.

@lucasccordeiro ESBMC didn't crash in issue https://github.com/esbmc/esbmc/issues/931. ESBMC indeed failed in the parser and rejeted the AST, also reported the correct error message "ERROR: Declaration has an empty name: CXXConstructorDecl".

**Comment by lucasccordeiro** [comment]
Thanks for this clarification, @kunjsong01.

**Pull request merged**
