### PR TITLE
Added short circuit for one byte types in optimized memset

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
This should partially solve #1458

### CODE REVIEW

**Comment by fbrausse** [comment]
It fixes the crash, thanks. But we'll need to find the proper semantics:
```c
#include <string.h>
#include <assert.h>

typedef _Bool bool;

int main()
{
  bool v;
  memset(&v, 2, sizeof(v));
  assert(!v);
}
```
Compiled with gcc and clang using `-O0`, no assertion error is detected. With `-O1` there is. Appearently it is "illegal" to load from a _Bool that doesn't have value 0 or 1. With `-fsanitize=undefined` both print something like:
```
memset-bool.c:10:3: runtime error: load of value 2, which is not a valid value for type 'bool' (aka '_Bool')
```

**Review by fbrausse — APPROVED** [review]

**Comment by fbrausse** [comment]
I've started an svcomp24 run with this change included: https://github.com/esbmc/esbmc/actions/runs/6834053649

*Edit:* It won't improve the result for the test initially mentioned in #1458 because it takes longer than 30s, but it could be that others will improve.

**Comment by fbrausse** [comment]
Before:
```
Statistics:          30471 Files
  correct:           18038
    correct true:    11190
    correct false:    6848
  incorrect:            37
    incorrect true:     18
    incorrect false:    19
  unknown:           12396
  Score:             28348 (max: 51065)

https://github.com/esbmc/esbmc/actions/runs/6833978190
```
With this PR:
```
Statistics:          30471 Files
  correct:           17968
    correct true:    11134
    correct false:    6834
  incorrect:            38
    incorrect true:     19
    incorrect false:    19
  unknown:           12465
  Score:             28190 (max: 51065)

https://github.com/esbmc/esbmc/actions/runs/6834053649
```
:(

**Comment by rafaelsamenezes** [comment]
Hm, maybe this is causing extra crashes. I will take a look

**Comment by fbrausse** [comment]
Much of the fewer solved ones are timeout fluctutations, but there are also new timeout -> unknown in unreach-call:
- c/seq-pthread/cs_queue-2.i
  Error building smt_convt::get() for nil-expr during simplify(), related: #1353

- c/ldv-consumption/32_7a_cilled_linux-3.8-rc1-32_7a-drivers--block--cciss.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.i
  dereference error in construct_struct_ref_from_const_offset_array() for `union` type

- c/ldv-linux-3.16-rc1/205_9a_array_unsafes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--wireless--ath--wcn36xx--wcn36xx.ko-entry_point.cil.out.i
  error during value_sett::assign() for a struct LHS and RHS is a typecast from an int to the struct type during memset() called at line 12617 The struct in question has 8 bits, so it's this PR:
  ```
  * type : struct
    * members : 
      0: unsignedbv
        * width : 1
      1: unsignedbv
        * width : 2
      2: unsignedbv
        * width : 1
      3: unsignedbv
        * width : 4
  
    * member_names : 
      0: rsvd
      1: aci
      2: acm
      3: aifsn
  
    * member_pretty_names : 
      0: rsvd
      1: aci
      2: acm
      3: aifsn
  
    * typename : struct wcn36xx_hal_aci_aifsn
    * packed : false
  ```

- c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--staging--unisys--visorbus--visorbus.ko-entry_point.cil.out.i
  c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--staging--unisys--visorbus--visorbus.ko-entry_point.cil.out.i
  c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--staging--unisys--visorbus--visorbus.ko-entry_point.cil.out.i
  all same as above: value_sett::assign() breaks on int typecast to struct of 8 bits (different struct here)

- c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--block--mtip32xx--mtip32xx.ko-entry_point.cil.out.i
  c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--mtip32xx--mtip32xx.ko.cil.i
  c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--ide--ide-core.ko.cil.i
  same as above, but this time on an 8-bit union

- c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--scsi--hpsa.ko-entry_point.cil.out.i
  c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--scsi--snic--snic.ko-entry_point.cil.out.i
  c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--scsi--hpsa.ko-entry_point.cil.out.i
  these fail in symex_printf(), wrong assumption about array-typed arguments being symbols; related: #1174

**Comment by fbrausse** [comment]
Checking the struct/union ones that crashed before on the current svcomp24 branch (00acc9c1ccdb2555d2ecc83272874b7373b6aa36) with a Debug build.

Local tests successful or timeout (ca. 10min):
- c/ldv-linux-3.16-rc1/205_9a_array_unsafes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--wireless--ath--wcn36xx--wcn36xx.ko-entry_point.cil.out.i
  c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--block--mtip32xx--mtip32xx.ko-entry_point.cil.out.i
  c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--block--mtip32xx--mtip32xx.ko.cil.i
  c/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--ide--ide-core.ko.cil.i

Local tests still fail:
- c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--staging--unisys--visorbus--visorbus.ko-entry_point.cil.out.i
  c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-32_7a-drivers--staging--unisys--visorbus--visorbus.ko-entry_point.cil.out.i
  c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-43_2a-drivers--staging--unisys--visorbus--visorbus.ko-entry_point.cil.out.i
  dereference error in construct_struct_ref_from_const_offset_array()

Looks good, only seemingly unrelated errors left.

**Review by lucasccordeiro — APPROVED** [review]

**Pull request merged**
