### PR TITLE
Bump minimal required version of clang to 9

### PR DESCRIPTION
**Pull request by mikhailramalho**
Addresses issue #22 and #30.

### CODE REVIEW

**Comment by mikhailramalho** [comment]
Jenkins is failing because it's trying to build esbmc with clang 7.

**Comment by feliperodri** [comment]
> Jenkins is failing because it's trying to build esbmc with clang 7.

@mikhailramalho We are not using Jenkins anymore, but GitHub Actions. Thus, we need to make sure the `.github/build.yml` contains the appropriate clang version setup.

**Review by feliperodri — APPROVED** [review]
LGTM

**Comment by rafaelsamenezes** [comment]
After PR https://github.com/esbmc/esbmc/pull/97 is merged. I will fix the CI/CD and merge this PR.

**Pull request merged**
