### PR TITLE
SV-COMP 22 Tracker

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
This PR will center the patches for the competition. This shouldn't be merged!

Features that were added:

- Wrapper is now using Python3!
- Fixed some witness generation bugs
- Memcleanup mode
- Function deref patch
- interval-analysis fix
- Concurrency now forces incremental-bmc
- fix for __VERIFIER_atomic_*
- Wrapper now checks if the benchmark contains pthread_create and sets the concurrency flags (if its reachability).

### CODE REVIEW

**Comment by mikhailramalho** [comment]
I remember talking with Lucas about the memcleanup category, which we currently don't support: maybe we can support the true case? I don't remember all the details, but I think we discussed the memcleanup holds if there is no memory leak, i.e., it holds if esbmc returns successful with `--memory-leak-check`.

Also, we need to evaluate k-induction and the new value-set option in the memory categories (currently the memory categories force incremental bmc).

**Comment by rafaelsamenezes** [comment]
>  I don't remember all the details, but I think we discussed the memcleanup holds if there is no memory leak, i.e., it holds if esbmc returns successful with --memory-leak-check

You are correct. @kunjsong01 could you work on it?

> Also, we need to evaluate k-induction and the new value-set option in the memory categories (currently the memory categories force incremental bmc).

I will work on that.

**Comment by mikhailramalho** [comment]
Do we have any sv-comp result to evaluate?

**Comment by rafaelsamenezes** [comment]
> Do we have any sv-comp result to evaluate?

Yes, I will forward to your email.

**Comment by mikhailramalho** [comment]
There several new failing cases, do we know what's the issue? 

Is it the new data-race category?

**Comment by rafaelsamenezes** [comment]
> There several new failing cases, do we know what's the issue?

For concurrency it seems that it has some issues. I am unable to detect some basic issues, even with the version from last year. I will try to identify and open an issue for this.

**Comment by rafaelsamenezes** [comment]
Concurrency bugs are caused by this issue: https://github.com/esbmc/esbmc/issues/530

**Comment by rafaelsamenezes** [comment]
This PR is no longer valid.

**Pull request closed without merging**
