### PR TITLE
fixed wrong dump method

### PR DESCRIPTION
**Pull request by rafaelsamenezes**

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Comment by mikhailramalho** [comment]
Can you also fix the ssa print?

**Comment by rafaelsamenezes** [comment]
> Can you also fix the ssa print?

Could you be more specific?

**Comment by mikhailramalho** [comment]
the option --program-too and --program-only

**Comment by mikhailramalho** [comment]
I'm currently using: 
[0001-foo.patch.txt](https://github.com/esbmc/esbmc/files/6886291/0001-foo.patch.txt)

**Review by mikhailramalho — APPROVED** [review]

**Pull request merged**
