### PR TITLE
K-induction fix

### PR DESCRIPTION
**Pull request by ChenfengWei0**
- issue: #1092 
- reuse the regression tests in #1105 

Apart from the example mentioned in the issue, ESBMC shows the wrong result (**"VERIFICATION SUCCESSFUL"**) for this simple example

```c++
#include <assert.h>

int main()
{
  int status = 0;

  int cnt = 4;
  while(cnt--)
  {
  }
  do
  {
    assert(0);
  } while(0);
}
```
command: `$esbmc test.c --k-induction`

This PR at least fixed this case and the case mentioned in the issue, by just removing the `skip` before doing `goto_k_induction()`. I think this will fix all the loop issue that does not involve the `nondet_int()`, though I do not know why this work. This may not be the best way to fix it.

### CODE REVIEW

**Comment by lucasccordeiro** [comment]
@ChenfengWei0: Thanks for submitting this PR.

Can I ask you to run this PR over the SV-COMP benchmarks?

**Comment by ChenfengWei0** [comment]
> @ChenfengWei0: Thanks for submitting this PR.
> 
> Can I ask you to run this PR over the SV-COMP benchmarks?

Yes. I just started a Run Benchexec

**Comment by mikhailramalho** [comment]
Hey @ChenfengWei0 we should at least understand why this fixes the issue, maybe a previous step is adding a skip and the k-induction algorithm is not prepared to handle that?

You can try to print the goto programs before the k-induction calls.

**Comment by ChenfengWei0** [comment]
> Hey @ChenfengWei0 we should at least understand why this fixes the issue, maybe a previous step is adding a skip and the k-induction algorithm is not prepared to handle that?
> 
> You can try to print the goto programs before the k-induction calls.

Thanks for the suggestions. Will investigate.

**Comment by lucasccordeiro** [comment]
This PR:

````
2023-07-25T21:20:04.0355461Z Statistics:          26459 Files
2023-07-25T21:20:04.0356150Z   correct:           14351
2023-07-25T21:20:04.0356580Z     correct true:     8160
2023-07-25T21:20:04.0357150Z     correct false:    6191
2023-07-25T21:20:04.0413650Z   incorrect:            60
2023-07-25T21:20:04.0415053Z     incorrect true:     29
2023-07-25T21:20:04.0415830Z     incorrect false:    31
2023-07-25T21:20:04.0416357Z   unknown:           12048
2023-07-25T21:20:04.0416974Z   Score:             21087 (max: 43043)
````

Master:
````
Statistics:          26459 Files
  correct:           14419
    correct true:     8158
    correct false:    6189
  incorrect:            64
    incorrect true:     29
    incorrect false:    35
  unknown:           12048
  Score:             21017 (max: 43043)
````

**Review by lucasccordeiro — APPROVED** [review]

**Comment by lucasccordeiro** [comment]
@ChenfengWei0 : can I ask you to open an issue to keep the investigation?

**Review by rafaelsamenezes — APPROVED** [review]
I am fine with approving this as the SKIPs should be removed anyway. Could you please open an issue to start investigating the why? This might be a deeper issue.

**Comment by ChenfengWei0** [comment]
> I am fine with approving this as the SKIPs should be removed anyway. Could you please open an issue to start investigating the why? This might be a deeper issue.

Just opened one. #1221

**Comment by lucasccordeiro** [comment]
Many thanks, @ChenfengWei0.

**Comment by fbrausse** [comment]
@lucasccordeiro Could you please link the SV-COMP benchmark runs of <https://github.com/esbmc/esbmc/pull/1218#issuecomment-1651134056>? I'd be interested in looking at the diff.

**Comment by ChenfengWei0** [comment]
> > @ChenfengWei0: Thanks for submitting this PR.
> > Can I ask you to run this PR over the SV-COMP benchmarks?
> 
> Yes. I just started a Run Benchexec

It's https://github.com/esbmc/esbmc/actions/runs/5654842278

**Comment by fbrausse** [comment]
> This PR:
> 
> ```
> 2023-07-25T21:20:04.0355461Z Statistics:          26459 Files
> 2023-07-25T21:20:04.0356150Z   correct:           14351
> 2023-07-25T21:20:04.0356580Z     correct true:     8160
> 2023-07-25T21:20:04.0357150Z     correct false:    6191
> 2023-07-25T21:20:04.0413650Z   incorrect:            60
> 2023-07-25T21:20:04.0415053Z     incorrect true:     29
> 2023-07-25T21:20:04.0415830Z     incorrect false:    31
> 2023-07-25T21:20:04.0416357Z   unknown:           12048
> 2023-07-25T21:20:04.0416974Z   Score:             21087 (max: 43043)
> ```
> 
> Master:
> 
> ```
> Statistics:          26459 Files
>   correct:           14419
>     correct true:     8158
>     correct false:    6189
>   incorrect:            64
>     incorrect true:     29
>     incorrect false:    35
>   unknown:           12048
>   Score:             21017 (max: 43043)
> ```

Sorry, I'm trying to understand from which runs these numbers come in order to be able to look at the diff in order to see whether/how the incorrect ones got solved (or went to timeouts). The "This PR" numbers above come from https://github.com/esbmc/esbmc/actions/runs/5654842278 which was using the `master` branch at d2216f313042db025d452d34904ab8c201e25182 *without* the changes of this PR, before merging it. So the labelling above seems off.

The numbers termed "Master" above I cannot find at all in our Github Actions, though that's exactly the "update stats" commit d2216f313042db025d452d34904ab8c201e25182. Inbetween @rafaelsamenezes' interval PR has been merged, but it also has different numbers: https://github.com/esbmc/esbmc/actions/runs/5643389166/job/15285122088

@lucasccordeiro Could you help to clarify where the numbers labelled "Master" in the quote above came from?

Maybe it makes sense to put the Action Run URL into the stats-30s.txt updates (commit or file) in the future.

**Comment by ChenfengWei0** [comment]
Sorry, it seems I have made a mistake here. I think this benchexec https://github.com/esbmc/esbmc/actions/runs/5668148185 will show the sv-comp result of this PR.

**Comment by fbrausse** [comment]
> Sorry, it seems I have made a mistake here. I think this benchexec https://github.com/esbmc/esbmc/actions/runs/5668148185 will show the sv-comp result of this PR.

OK, great, thank you. Let's wait for those and see how removing skips affect the stats.

**Comment by lucasccordeiro** [comment]
> @lucasccordeiro Could you help to clarify where the numbers labelled "Master" in the quote above came from?

My apologies. As discussed with @fbrausse via Slack, I couldn't find the run where I collected these statistics.  

From now on, I'll also add the link to the run in the stats file so we can always retrieve this information when needed.

**Pull request merged**
