### PR TITLE
ARM64 build

### PR DESCRIPTION
**Pull request by rafaelsamenezes**
This will check if we are able to build the current version of ESBMC in ARM.

Saddly, Github Actions does not have an ARM64 runner and I do not have an ARM64 machine to add as a selfhosted-runner which means that this will use Travis CI and that we won't have automatic releases.

### CODE REVIEW

**Review by lucasccordeiro — APPROVED** [review]
LGTM.

**Comment by pmatos** [comment]
If you need an arm64 box to run tests, feel free to let me know and I can setup a self-hosted runner for your tests.

**Comment by rafaelsamenezes** [comment]
> If you need an arm64 box to run tests, feel free to let me know and I can setup a self-hosted runner for your tests.

@pmatos that would be great!

**Comment by pmatos** [comment]
> > If you need an arm64 box to run tests, feel free to let me know and I can setup a self-hosted runner for your tests.
> 
> @pmatos that would be great!

Do you know how much memory you need?
Is 4Gb enough or do you need 8Gb? Just so I can understand which boards to allocate.

**Comment by rafaelsamenezes** [comment]
> Is 4Gb enough

4GB is enough

**Comment by pmatos** [comment]
> > Is 4Gb enough
> 
> 4GB is enough

OK. I will sync with @lucasccordeiro via phone call to obtain the token to setup the board. Will let you know when it's done.

**Pull request merged**
