### PR TITLE
Fix boolector error

### PR DESCRIPTION
**Pull request by brcfarias**
This PR fixes the error below.  

image

This error occurs when checking btor2c-lazyMod.unsafe_intersymbol_analog_estimation_convergence.c (svcomp) with --ub-shift-check.

### CODE REVIEW

**Review by lucasccordeiro — CHANGES_REQUESTED** [review]
@brcfarias : could you please add some regression tests?

**Comment by brcfarias** [comment]
> @brcfarias : could you please add some regression tests?

Regression test added.

**Review by fbrausse — APPROVED** [review]
LGTM.

**Review by lucasccordeiro — APPROVED** [review]

**Comment by fbrausse** [comment]
@brcfarias To fix the Windows cases please be aware that `long` and `unsigned long` on Windows only have 32 bits. If you want to be sure, `#include <stdint.h>` and use `uint64_t` instead.

**Comment by brcfarias** [comment]
> @brcfarias To fix the Windows cases please be aware that `long` and `unsigned long` on Windows only have 32 bits. If you want to be sure, `#include <stdint.h>` and use `uint64_t` instead.

@fbrausse It worked. Many thanks!

**Comment by lucasccordeiro** [comment]
Many thanks for fixing this issue, @brcfarias.

**Pull request merged**
